// cron_monitor_test.go — WithCronMonitor contract suite (go-fly-http).
//
// Generated by the add-observability skill; lives in the project after
// scaffold so future regenerations can detect breakage.
//
// Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
//
//	D1  — separate-wrapper export
//	D5d — Go composition (innermost: middleware(WithCronMonitor(fn)))
//	D6  — 3-source slug resolution (explicit > env > auto-derive); Go uses
//	      explicit cronExpression option for the auto-derive slot
//	D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig
//	      (2nd arg) on the in_progress checkin only
//	R04 — SENTRY_DEBUG=1 opt-in surface of swallowed errors
//	R05 — captureCheckinFn returns *sentry.EventID (not sentry.EventID); the
//	      stub returns &id and the helper struct stores a *sentry.EventID.
//
// Sentry SDK ingress is swapped at the package-level seam `captureCheckinFn`
// (and the SENTRY_DEBUG surface uses the `debugLogFn` seam). Tests using
// these seams MUST NOT call t.Parallel() — they mutate package-level state.
package {{PACKAGE_NAME}}

import (
	"context"
	"errors"
	"strings"
	"testing"

	sentry "github.com/getsentry/sentry-go"
)

// capturedCheckin is the per-call record produced by captureCheckinStub.
//
// Per R05, EventID is *sentry.EventID (a pointer); the stub returns a non-nil
// pointer so the impl's `checkInID != nil` branches fire correctly.
type capturedCheckin struct {
	EventID       *sentry.EventID
	ID            sentry.EventID // CheckIn.ID forwarded on completion checkins
	MonitorSlug   string
	Status        sentry.CheckInStatus
	MonitorConfig *sentry.MonitorConfig
}

// captureCheckinStub swaps captureCheckinFn for a recording stub.
//
// PER R05: tests using this stub MUST NOT call t.Parallel() — captureCheckinFn
// is package-level state. t.Cleanup restores the prior fn so test isolation
// holds across sequential runs.
func captureCheckinStub(t *testing.T) *[]capturedCheckin {
	t.Helper()
	calls := &[]capturedCheckin{}
	prev := captureCheckinFn
	captureCheckinFn = func(c *sentry.CheckIn, mc *sentry.MonitorConfig) *sentry.EventID {
		id := sentry.EventID("stub-checkin-id")
		*calls = append(*calls, capturedCheckin{
			EventID:       &id,
			ID:            c.ID,
			MonitorSlug:   c.MonitorSlug,
			Status:        c.Status,
			MonitorConfig: mc,
		})
		return &id
	}
	t.Cleanup(func() { captureCheckinFn = prev })
	return calls
}

// debugLogStub swaps debugLogFn for a recording stub. Same parallelism
// constraint as captureCheckinStub (R04 + R05 seam pattern).
func debugLogStub(t *testing.T) *[]string {
	t.Helper()
	msgs := &[]string{}
	prev := debugLogFn
	debugLogFn = func(msg string, err error) {
		if err != nil {
			*msgs = append(*msgs, msg+": "+err.Error())
		} else {
			*msgs = append(*msgs, msg)
		}
	}
	t.Cleanup(func() { debugLogFn = prev })
	return msgs
}

// ─── Cron checkin behavior ────────────────────────────────────────────────────

func TestWithCronMonitorEmitsCheckinsOnHappyPath(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	callsP := captureCheckinStub(t)

	called := false
	err := WithCronMonitor(context.Background(), func() error {
		called = true
		return nil
	}, WithMonitorSlug("fxsa-go-cron"))

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !called {
		t.Fatal("handler fn was not invoked")
	}
	calls := *callsP
	if len(calls) != 2 {
		t.Fatalf("expected 2 checkins (in_progress + ok), got %d", len(calls))
	}
	if calls[0].Status != sentry.CheckInStatusInProgress {
		t.Errorf("call 1 status = %q, want %q", calls[0].Status, sentry.CheckInStatusInProgress)
	}
	if calls[1].Status != sentry.CheckInStatusOK {
		t.Errorf("call 2 status = %q, want %q", calls[1].Status, sentry.CheckInStatusOK)
	}
	if calls[0].MonitorSlug != "fxsa-go-cron" {
		t.Errorf("call 1 slug = %q, want %q", calls[0].MonitorSlug, "fxsa-go-cron")
	}
	if calls[1].MonitorSlug != "fxsa-go-cron" {
		t.Errorf("call 2 slug = %q, want %q", calls[1].MonitorSlug, "fxsa-go-cron")
	}
	// Completion checkin MUST carry the in_progress ID so Sentry correlates
	// the pair. The stub returned "stub-checkin-id" from the first call.
	if calls[1].ID != sentry.EventID("stub-checkin-id") {
		t.Errorf("ok checkin ID = %q, want %q", calls[1].ID, "stub-checkin-id")
	}
}

func TestWithCronMonitorEmitsErrorAndReturnsOriginal(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	callsP := captureCheckinStub(t)

	boom := errors.New("handler exploded")
	err := WithCronMonitor(context.Background(), func() error {
		return boom
	}, WithMonitorSlug("fxsa-go-cron"))

	if err != boom {
		t.Fatalf("expected original error %v re-thrown, got %v", boom, err)
	}
	calls := *callsP
	if len(calls) != 2 {
		t.Fatalf("expected 2 checkins (in_progress + error), got %d", len(calls))
	}
	if calls[0].Status != sentry.CheckInStatusInProgress {
		t.Errorf("call 1 status = %q, want in_progress", calls[0].Status)
	}
	if calls[1].Status != sentry.CheckInStatusError {
		t.Errorf("call 2 status = %q, want error", calls[1].Status)
	}
	if calls[1].ID != sentry.EventID("stub-checkin-id") {
		t.Errorf("error checkin ID = %q, want %q", calls[1].ID, "stub-checkin-id")
	}
}

func TestWithCronMonitorNoopsWhenDSNUnset(t *testing.T) {
	// SENTRY_DSN intentionally unset (use t.Setenv to scope the absence).
	t.Setenv("SENTRY_DSN", "")
	callsP := captureCheckinStub(t)

	called := false
	err := WithCronMonitor(context.Background(), func() error {
		called = true
		return nil
	}, WithMonitorSlug("fxsa-go-cron"))

	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !called {
		t.Fatal("handler fn was not invoked — fail-safe noop must still run fn")
	}
	if calls := *callsP; len(calls) != 0 {
		t.Errorf("DSN unset → expected 0 checkins, got %d", len(calls))
	}
}

// ─── Slug resolution (D6) ─────────────────────────────────────────────────────

func TestSlugExplicitOverridesEnvAndAuto(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	t.Setenv("SENTRY_CRON_MONITOR_SLUG_SCHEDULED", "env-loses")
	t.Setenv("SERVICE_NAME", "auto-loses")
	callsP := captureCheckinStub(t)

	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithMonitorSlug("explicit-wins"),
		WithCronExpression("*/15 * * * *"),
	)
	calls := *callsP
	if len(calls) < 1 {
		t.Fatal("no checkin recorded")
	}
	if calls[0].MonitorSlug != "explicit-wins" {
		t.Errorf("slug = %q, want %q", calls[0].MonitorSlug, "explicit-wins")
	}
}

func TestSlugEnvOverridesAuto(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	// Handler name is "ingest" → env key SENTRY_CRON_MONITOR_SLUG_INGEST.
	t.Setenv("SENTRY_CRON_MONITOR_SLUG_INGEST", "env-wins")
	t.Setenv("SERVICE_NAME", "auto-loses")
	callsP := captureCheckinStub(t)

	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithHandlerName("ingest"),
		WithCronExpression("*/15 * * * *"),
	)
	calls := *callsP
	if len(calls) < 1 {
		t.Fatal("no checkin recorded")
	}
	if calls[0].MonitorSlug != "env-wins" {
		t.Errorf("slug = %q, want %q", calls[0].MonitorSlug, "env-wins")
	}
}

func TestSlugAutoDerivesFromServiceNameAndCronExpression(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	t.Setenv("SERVICE_NAME", "fxsa-go")
	// Unset any env override that could win.
	t.Setenv("SENTRY_CRON_MONITOR_SLUG_SCHEDULED", "")
	callsP := captureCheckinStub(t)

	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithCronExpression("*/15 * * * *"),
	)
	calls := *callsP
	if len(calls) < 1 {
		t.Fatal("no checkin recorded")
	}
	want := "fxsa-go:*/15 * * * *"
	if calls[0].MonitorSlug != want {
		t.Errorf("auto-derived slug = %q, want %q", calls[0].MonitorSlug, want)
	}
}

// ─── monitorConfig forwarding (D12 / R03) ─────────────────────────────────────

func TestMonitorConfigForwardedOnInProgressOnly(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	callsP := captureCheckinStub(t)

	schedule := sentry.CrontabSchedule("*/15 * * * *")
	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithMonitorSlug("x"),
		WithMonitorSchedule(schedule),
		WithMaxRuntimeSeconds(240),
	)
	calls := *callsP
	if len(calls) != 2 {
		t.Fatalf("expected 2 checkins, got %d", len(calls))
	}
	// 1st call (in_progress) MUST carry monitorConfig.
	if calls[0].MonitorConfig == nil {
		t.Fatalf("in_progress monitorConfig was nil; want non-nil with schedule + maxRuntime")
	}
	if calls[0].MonitorConfig.Schedule == nil {
		t.Errorf("in_progress monitorConfig.Schedule was nil")
	}
	if calls[0].MonitorConfig.MaxRuntime != 240 {
		t.Errorf("in_progress monitorConfig.MaxRuntime = %d, want 240", calls[0].MonitorConfig.MaxRuntime)
	}
	// 2nd call (ok) MUST omit monitorConfig — Sentry treats the monitor as
	// already-configured after the in_progress UPSERT.
	if calls[1].MonitorConfig != nil {
		t.Errorf("ok monitorConfig = %+v, want nil", calls[1].MonitorConfig)
	}
}

func TestMonitorConfigOmittedWhenUnset(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	callsP := captureCheckinStub(t)

	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithMonitorSlug("x"),
	)
	calls := *callsP
	if len(calls) < 1 {
		t.Fatal("no checkin recorded")
	}
	if calls[0].MonitorConfig != nil {
		t.Errorf("in_progress monitorConfig = %+v, want nil (no schedule / no maxRuntime configured)", calls[0].MonitorConfig)
	}
}

// ─── SENTRY_DEBUG opt-in logging (R04) ────────────────────────────────────────

func TestSentryDebugSurfacesSwallowedCheckinError(t *testing.T) {
	t.Setenv("SENTRY_DSN", "https://stub@sentry.io/1")
	msgsP := debugLogStub(t)

	// Make captureCheckinFn panic so the safe-recover swallow path fires.
	prev := captureCheckinFn
	captureCheckinFn = func(_ *sentry.CheckIn, _ *sentry.MonitorConfig) *sentry.EventID {
		panic(errors.New("sentry SDK boom"))
	}
	t.Cleanup(func() { captureCheckinFn = prev })

	// SENTRY_DEBUG absent — silent path.
	t.Setenv("SENTRY_DEBUG", "")
	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithMonitorSlug("x"),
	)
	if len(*msgsP) != 0 {
		t.Errorf("SENTRY_DEBUG unset: expected 0 debug messages, got %d (%v)", len(*msgsP), *msgsP)
	}

	// SENTRY_DEBUG=1 — surface path.
	t.Setenv("SENTRY_DEBUG", "1")
	_ = WithCronMonitor(context.Background(), func() error { return nil },
		WithMonitorSlug("x"),
	)
	if len(*msgsP) == 0 {
		t.Fatal("SENTRY_DEBUG=1: expected swallow surface via debugLogFn, got 0 messages")
	}
	// At least one message should mention the SDK error.
	found := false
	for _, m := range *msgsP {
		if strings.Contains(m, "sentry SDK boom") {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected a debug message containing %q, got %v", "sentry SDK boom", *msgsP)
	}
}
