// healthz_snippet_test.go — HealthzHandler contract suite (go-fly-http).
//
// Generated by the add-observability skill; lives in the project after
// scaffold so future regenerations can detect breakage.
//
// Tests the COPY-ONLY healthz template's contract per phase-22 CONTEXT.md
// and PLAN.md REVISIONS R06 + R07:
//
//	D9  — healthz NOT wrapped by withObservability (no span overhead on the
//	      health endpoint).
//	R06 — fail-closed on zero probes configured: returns 503 with
//	      {"status":"degraded","reason":"no probes configured — adapt
//	      healthz_snippet.go to your dependencies","checks":{}}.
//	R07 — top-of-file multi-line WARNING block (plain `//` comments; Go has
//	      no box-drawing convention).
//
// The handler is constructed via a factory `HealthzHandler(deps HealthzDeps)
// http.HandlerFunc` so deps are captured at construction and the returned
// handler matches the standard net/http signature for mounting.
//
// Go adaptation targets:
//   - deps.DB       — anything implementing PingContext(ctx) error
//   - deps.Upstream — anything implementing Get(url) (*http.Response, error)
package {{PACKAGE_NAME}}

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// ─── Stub helpers ─────────────────────────────────────────────────────────────

type stubDB struct{ err error }

func (s *stubDB) PingContext(_ context.Context) error { return s.err }

type stubUpstream struct {
	resp *http.Response
	err  error
}

func (s *stubUpstream) Get(_ string) (*http.Response, error) {
	return s.resp, s.err
}

func newRequest() *http.Request {
	r, _ := http.NewRequest(http.MethodGet, "/healthz", nil)
	return r
}

func decodeBody(t *testing.T, w *httptest.ResponseRecorder) map[string]any {
	t.Helper()
	var body map[string]any
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("decode body: %v\nraw=%q", err, w.Body.String())
	}
	return body
}

// ─── R06 — fail-closed default ────────────────────────────────────────────────

func TestHealthzReturns503WithReasonWhenNoProbesConfigured(t *testing.T) {
	h := HealthzHandler(HealthzDeps{})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want %d, got %d", http.StatusServiceUnavailable, w.Code)
	}
	if ct := w.Header().Get("Content-Type"); !strings.Contains(ct, "application/json") {
		t.Fatalf("content-type: want application/json, got %q", ct)
	}
	body := decodeBody(t, w)
	if body["status"] != "degraded" {
		t.Errorf("status: want degraded, got %v", body["status"])
	}
	wantReason := "no probes configured — adapt healthz_snippet.go to your dependencies"
	if body["reason"] != wantReason {
		t.Errorf("reason: want %q, got %v", wantReason, body["reason"])
	}
	checks, ok := body["checks"].(map[string]any)
	if !ok {
		t.Fatalf("checks: not a map, raw=%v", body["checks"])
	}
	if len(checks) != 0 {
		t.Errorf("checks: want empty, got %v", checks)
	}
}

// ─── Happy path — all probes pass ─────────────────────────────────────────────

func TestHealthzReturns200WhenDBPingSucceeds(t *testing.T) {
	h := HealthzHandler(HealthzDeps{DB: &stubDB{err: nil}})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusOK {
		t.Fatalf("status: want 200, got %d", w.Code)
	}
	body := decodeBody(t, w)
	if body["status"] != "ok" {
		t.Errorf("status: want ok, got %v", body["status"])
	}
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != true {
		t.Errorf("checks.db: want true, got %v", checks["db"])
	}
}

func TestHealthzReturns200WhenDBAndUpstreamBothSucceed(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		DB: &stubDB{err: nil},
		Upstream: &stubUpstream{
			resp: &http.Response{StatusCode: 200, Body: http.NoBody},
			err:  nil,
		},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusOK {
		t.Fatalf("status: want 200, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != true {
		t.Errorf("checks.db: want true, got %v", checks["db"])
	}
	if checks["upstream"] != true {
		t.Errorf("checks.upstream: want true, got %v", checks["upstream"])
	}
}

// ─── Failure paths — any probe failure → degraded ─────────────────────────────

func TestHealthzReturns503WhenDBPingFails(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		DB: &stubDB{err: errors.New("connection refused")},
		Upstream: &stubUpstream{
			resp: &http.Response{StatusCode: 200, Body: http.NoBody},
		},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	if body["status"] != "degraded" {
		t.Errorf("status: want degraded, got %v", body["status"])
	}
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != false {
		t.Errorf("checks.db: want false, got %v", checks["db"])
	}
	if checks["upstream"] != true {
		t.Errorf("checks.upstream: want true, got %v", checks["upstream"])
	}
}

func TestHealthzTreatsUpstream5xxAsFailedProbe(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		Upstream: &stubUpstream{
			resp: &http.Response{StatusCode: 503, Body: http.NoBody},
		},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["upstream"] != false {
		t.Errorf("checks.upstream: want false, got %v", checks["upstream"])
	}
}

func TestHealthzTreatsUpstreamErrorAsFailedProbe(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		Upstream: &stubUpstream{err: errors.New("dial tcp: i/o timeout")},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["upstream"] != false {
		t.Errorf("checks.upstream: want false, got %v", checks["upstream"])
	}
}

// ─── F2 per-probe timeout tests (Phase 23 / D-03 / R-rev-3 narrowed for Go) ──
//
// Go narrowing (R-rev-3 / codex MEDIUM-5):
//   - DB probe uses context.WithTimeout(r.Context(), probeTimeout); DeadlineExceeded → "timeout"
//   - Upstream probe uses a goroutine + select with time.After (race-only, no signal path)
//   - ProbeTimeout field on HealthzDeps; zero value → defaultHealthzProbeTimeout (2s)
//
// Per PLAN honest-docs requirement: Go handler-latency note present in GREEN impl.

// stubHangingDB blocks until ctx is cancelled — simulates a slow DB.
type stubHangingDB struct{}

func (s *stubHangingDB) PingContext(ctx context.Context) error {
	<-ctx.Done()
	return ctx.Err()
}

// stubHangingUpstream blocks indefinitely — simulates a slow upstream.
type stubHangingUpstream struct{}

func (s *stubHangingUpstream) Get(_ string) (*http.Response, error) {
	select {} // block forever
}

// TestF2GoTest1 — fast DB probe resolves within timeout → status ok.
func TestF2GoTest1FastProbeResolvesWithinTimeout(t *testing.T) {
	h := HealthzHandler(HealthzDeps{DB: &stubDB{err: nil}})
	w := httptest.NewRecorder()
	h(w, newRequest())
	if w.Code != http.StatusOK {
		t.Fatalf("status: want 200, got %d", w.Code)
	}
	body := decodeBody(t, w)
	if body["status"] != "ok" {
		t.Errorf("status: want ok, got %v", body["status"])
	}
}

// TestF2GoTest2 — DB probe hanging > default timeout → degraded with "timeout" sentinel.
func TestF2GoTest2DBProbeHangingExceedsDefaultTimeout(t *testing.T) {
	deps := HealthzDeps{
		DB:           &stubHangingDB{},
		ProbeTimeout: 200 * time.Millisecond, // fast override so test doesn't take 2s
	}
	h := HealthzHandler(deps)
	w := httptest.NewRecorder()
	start := time.Now()
	h(w, newRequest())
	elapsed := time.Since(start)

	if elapsed > 600*time.Millisecond {
		t.Errorf("elapsed %v exceeded 600ms (200ms probe timeout + 400ms slack)", elapsed)
	}
	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != "timeout" {
		t.Errorf("checks.db: want \"timeout\", got %v", checks["db"])
	}
}

// TestF2GoTest3 — HealthzDeps.ProbeTimeout overrides the default 2s timeout.
func TestF2GoTest3ProbeTimeoutFieldOverridesDefault(t *testing.T) {
	deps := HealthzDeps{
		DB:           &stubHangingDB{},
		ProbeTimeout: 300 * time.Millisecond,
	}
	h := HealthzHandler(deps)
	w := httptest.NewRecorder()
	start := time.Now()
	h(w, newRequest())
	elapsed := time.Since(start)

	if elapsed > 700*time.Millisecond {
		t.Errorf("elapsed %v; want < 700ms (300ms timeout + 400ms slack)", elapsed)
	}
	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != "timeout" {
		t.Errorf("checks.db: want \"timeout\", got %v", checks["db"])
	}
}

// TestF2GoTest4 — upstream probe hanging > timeout → degraded with "timeout" sentinel.
func TestF2GoTest4UpstreamProbeHangingExceedsTimeout(t *testing.T) {
	deps := HealthzDeps{
		Upstream:     &stubHangingUpstream{},
		ProbeTimeout: 200 * time.Millisecond,
	}
	h := HealthzHandler(deps)
	w := httptest.NewRecorder()
	start := time.Now()
	h(w, newRequest())
	elapsed := time.Since(start)

	if elapsed > 600*time.Millisecond {
		t.Errorf("elapsed %v exceeded 600ms (200ms probe timeout + 400ms slack)", elapsed)
	}
	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["upstream"] != "timeout" {
		t.Errorf("checks.upstream: want \"timeout\", got %v", checks["upstream"])
	}
}

// TestF2GoTest5 — zero ProbeTimeout falls back to defaultHealthzProbeTimeout (2s constant exists).
func TestF2GoTest5ZeroProbeTimeoutFallsBackToDefault(t *testing.T) {
	// Verify the exported constant (or unexported default) exists by using a fast probe —
	// the zero-value HealthzDeps.ProbeTimeout should resolve to defaultHealthzProbeTimeout.
	// We just confirm the handler completes and returns ok (not a timeout) for a fast probe.
	h := HealthzHandler(HealthzDeps{DB: &stubDB{err: nil}})
	w := httptest.NewRecorder()
	h(w, newRequest())
	if w.Code != http.StatusOK {
		t.Fatalf("status: want 200, got %d", w.Code)
	}
	// Also verify defaultHealthzProbeTimeout constant is 2 seconds.
	if defaultHealthzProbeTimeout != 2*time.Second {
		t.Errorf("defaultHealthzProbeTimeout: want 2s, got %v", defaultHealthzProbeTimeout)
	}
}
