// healthz_snippet_test.go — HealthzHandler contract suite (go-fly-http).
//
// Generated by the add-observability skill; lives in the project after
// scaffold so future regenerations can detect breakage.
//
// Tests the COPY-ONLY healthz template's contract per phase-22 CONTEXT.md
// and PLAN.md REVISIONS R06 + R07:
//
//	D9  — healthz NOT wrapped by withObservability (no span overhead on the
//	      health endpoint).
//	R06 — fail-closed on zero probes configured: returns 503 with
//	      {"status":"degraded","reason":"no probes configured — adapt
//	      healthz_snippet.go to your dependencies","checks":{}}.
//	R07 — top-of-file multi-line WARNING block (plain `//` comments; Go has
//	      no box-drawing convention).
//
// The handler is constructed via a factory `HealthzHandler(deps HealthzDeps)
// http.HandlerFunc` so deps are captured at construction and the returned
// handler matches the standard net/http signature for mounting.
//
// Go adaptation targets:
//   - deps.DB       — anything implementing PingContext(ctx) error
//   - deps.Upstream — anything implementing Get(url) (*http.Response, error)
package {{PACKAGE_NAME}}

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// ─── Stub helpers ─────────────────────────────────────────────────────────────

type stubDB struct{ err error }

func (s *stubDB) PingContext(_ context.Context) error { return s.err }

type stubUpstream struct {
	resp *http.Response
	err  error
}

func (s *stubUpstream) Get(_ string) (*http.Response, error) {
	return s.resp, s.err
}

func newRequest() *http.Request {
	r, _ := http.NewRequest(http.MethodGet, "/healthz", nil)
	return r
}

func decodeBody(t *testing.T, w *httptest.ResponseRecorder) map[string]any {
	t.Helper()
	var body map[string]any
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("decode body: %v\nraw=%q", err, w.Body.String())
	}
	return body
}

// ─── R06 — fail-closed default ────────────────────────────────────────────────

func TestHealthzReturns503WithReasonWhenNoProbesConfigured(t *testing.T) {
	h := HealthzHandler(HealthzDeps{})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want %d, got %d", http.StatusServiceUnavailable, w.Code)
	}
	if ct := w.Header().Get("Content-Type"); !strings.Contains(ct, "application/json") {
		t.Fatalf("content-type: want application/json, got %q", ct)
	}
	body := decodeBody(t, w)
	if body["status"] != "degraded" {
		t.Errorf("status: want degraded, got %v", body["status"])
	}
	wantReason := "no probes configured — adapt healthz_snippet.go to your dependencies"
	if body["reason"] != wantReason {
		t.Errorf("reason: want %q, got %v", wantReason, body["reason"])
	}
	checks, ok := body["checks"].(map[string]any)
	if !ok {
		t.Fatalf("checks: not a map, raw=%v", body["checks"])
	}
	if len(checks) != 0 {
		t.Errorf("checks: want empty, got %v", checks)
	}
}

// ─── Happy path — all probes pass ─────────────────────────────────────────────

func TestHealthzReturns200WhenDBPingSucceeds(t *testing.T) {
	h := HealthzHandler(HealthzDeps{DB: &stubDB{err: nil}})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusOK {
		t.Fatalf("status: want 200, got %d", w.Code)
	}
	body := decodeBody(t, w)
	if body["status"] != "ok" {
		t.Errorf("status: want ok, got %v", body["status"])
	}
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != true {
		t.Errorf("checks.db: want true, got %v", checks["db"])
	}
}

func TestHealthzReturns200WhenDBAndUpstreamBothSucceed(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		DB: &stubDB{err: nil},
		Upstream: &stubUpstream{
			resp: &http.Response{StatusCode: 200, Body: http.NoBody},
			err:  nil,
		},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusOK {
		t.Fatalf("status: want 200, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != true {
		t.Errorf("checks.db: want true, got %v", checks["db"])
	}
	if checks["upstream"] != true {
		t.Errorf("checks.upstream: want true, got %v", checks["upstream"])
	}
}

// ─── Failure paths — any probe failure → degraded ─────────────────────────────

func TestHealthzReturns503WhenDBPingFails(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		DB: &stubDB{err: errors.New("connection refused")},
		Upstream: &stubUpstream{
			resp: &http.Response{StatusCode: 200, Body: http.NoBody},
		},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	if body["status"] != "degraded" {
		t.Errorf("status: want degraded, got %v", body["status"])
	}
	checks, _ := body["checks"].(map[string]any)
	if checks["db"] != false {
		t.Errorf("checks.db: want false, got %v", checks["db"])
	}
	if checks["upstream"] != true {
		t.Errorf("checks.upstream: want true, got %v", checks["upstream"])
	}
}

func TestHealthzTreatsUpstream5xxAsFailedProbe(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		Upstream: &stubUpstream{
			resp: &http.Response{StatusCode: 503, Body: http.NoBody},
		},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["upstream"] != false {
		t.Errorf("checks.upstream: want false, got %v", checks["upstream"])
	}
}

func TestHealthzTreatsUpstreamErrorAsFailedProbe(t *testing.T) {
	h := HealthzHandler(HealthzDeps{
		Upstream: &stubUpstream{err: errors.New("dial tcp: i/o timeout")},
	})
	w := httptest.NewRecorder()
	h(w, newRequest())

	if w.Code != http.StatusServiceUnavailable {
		t.Fatalf("status: want 503, got %d", w.Code)
	}
	body := decodeBody(t, w)
	checks, _ := body["checks"].(map[string]any)
	if checks["upstream"] != false {
		t.Errorf("checks.upstream: want false, got %v", checks["upstream"])
	}
}
