// Package {{PACKAGE_NAME}} — AgenticApps observability wrapper, spec §10 v0.2.0.
//
// Service:     {{SERVICE_NAME}}
// Destination: {{DESTINATION}}
//
// Generated by the add-observability skill. Edits to this file should be
// mirrored into the skill template if they're general; project-specific
// helpers belong in a sibling _ext.go file.
//
// CONTRACT (per spec §10):
//
//	LogEvent(ctx, envelope)        non-blocking emission of a structured event
//	CaptureError(ctx, err, env)    record an error with envelope context
//	StartSpan(ctx, name, attrs)    open a span; returns (ctx, *Span)
//
// Application code MUST NOT import getsentry/sentry-go directly. Use the
// three exports above. See policy.md for redaction and sampling rules.
package {{PACKAGE_NAME}}

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	mrand "math/rand/v2"
	"os"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/getsentry/sentry-go"
)

// ─── Public types ──────────────────────────────────────────────────────────

type Severity string

const (
	SeverityDebug Severity = "debug"
	SeverityInfo  Severity = "info"
	SeverityWarn  Severity = "warn"
	SeverityError Severity = "error"
	SeverityFatal Severity = "fatal"
)

type SpanStatus string

const (
	StatusOK    SpanStatus = "ok"
	StatusError SpanStatus = "error"
)

// Envelope is the application-supplied portion of an event. The wrapper
// fills trace_id, span_id, service, env, and timestamp before emission.
type Envelope struct {
	Event    string
	Severity Severity
	Attrs    map[string]any
}

// TraceContext is the W3C trace context bound to a request.
type TraceContext struct {
	TraceID      string // 32 hex chars
	SpanID       string // 16 hex chars (current span)
	ParentSpanID string // 16 hex chars (parent span; empty for root)
	Flags        byte
}

// Span represents a unit of work. Must be ended with End() or
// EndWithStatus(...) to emit the span event.
type Span struct {
	traceID   string
	spanID    string
	parentID  string
	flags     byte
	name      string
	startedAt time.Time
	attrs     map[string]any
	status    SpanStatus
	statusSet bool
	mu        sync.Mutex
	ended     bool
}

func (s *Span) TraceID() string { return s.traceID }
func (s *Span) SpanID() string  { return s.spanID }

func (s *Span) SetAttribute(key string, value any) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.attrs[key] = redactValue(key, value)
}

func (s *Span) SetStatus(status SpanStatus) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.status = status
	s.statusSet = true
}

// End emits the span event. Idempotent.
func (s *Span) End() {
	s.endWith("")
}

// EndWithStatus is a convenience for setting status and ending in one call.
func (s *Span) EndWithStatus(status SpanStatus) {
	s.endWith(status)
}

func (s *Span) endWith(status SpanStatus) {
	s.mu.Lock()
	if s.ended {
		s.mu.Unlock()
		return
	}
	s.ended = true
	if status != "" {
		s.status = status
		s.statusSet = true
	}
	if !s.statusSet {
		s.status = StatusOK
	}
	finalStatus := s.status
	attrs := make(map[string]any, len(s.attrs)+2)
	for k, v := range s.attrs {
		attrs[k] = v
	}
	attrs["duration_ms"] = time.Since(s.startedAt).Milliseconds()
	attrs["span_status"] = string(finalStatus)
	name := s.name
	traceID := s.traceID
	spanID := s.spanID
	s.mu.Unlock()

	sev := SeverityInfo
	if finalStatus == StatusError {
		sev = SeverityError
	}
	emit(Envelope{Event: name, Severity: sev, Attrs: attrs}, &TraceContext{
		TraceID: traceID,
		SpanID:  spanID,
		Flags:   s.flags,
	})
}

// ─── Module state (set by Init) ────────────────────────────────────────────

var (
	initOnce        sync.Once
	serviceName     = "{{SERVICE_NAME}}"
	deployEnv       = "dev"
	debugSampleRate = {{DEBUG_SAMPLE_RATE}}
	traceSampleRate = {{TRACE_SAMPLE_RATE}}
	logger          = slog.New(slog.NewJSONHandler(os.Stdout, nil))
	sentryReady     bool
)

// Init initializes the wrapper and the destination SDK. Idempotent;
// subsequent calls are no-ops.
//
// Reads from env. Use os.Getenv directly; the function does not depend on
// any framework convention.
func Init() {
	initOnce.Do(func() {
		if v := os.Getenv("{{ENV_VAR_SERVICE}}"); v != "" {
			serviceName = v
		}
		if v := os.Getenv("{{ENV_VAR_ENV}}"); v != "" {
			deployEnv = v
		}
		dsn := os.Getenv("{{ENV_VAR_DSN}}")
		if dsn != "" {
			err := sentry.Init(sentry.ClientOptions{
				Dsn:              dsn,
				Environment:      deployEnv,
				Release:          serviceName,
				EnableTracing:    true,
				TracesSampleRate: traceSampleRate,
				SendDefaultPII:   false,
			})
			if err != nil {
				logger.Warn("observability: sentry init failed", "err", err.Error())
			} else {
				sentryReady = true
			}
		}
	})
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

var traceparentRE = regexp.MustCompile(`^([0-9a-fA-F]{2})-([0-9a-fA-F]{32})-([0-9a-fA-F]{16})-([0-9a-fA-F]{2})$`)

func randHex(nBytes int) string {
	buf := make([]byte, nBytes)
	if _, err := rand.Read(buf); err != nil {
		// Fall back to math/rand — never block emission on randomness.
		for i := range buf {
			buf[i] = byte(mrand.IntN(256))
		}
	}
	return hex.EncodeToString(buf)
}

// ParseTraceparent parses an inbound traceparent header.
func ParseTraceparent(header string) (*TraceContext, bool) {
	header = strings.TrimSpace(header)
	if header == "" {
		return nil, false
	}
	m := traceparentRE.FindStringSubmatch(header)
	if m == nil {
		return nil, false
	}
	flags, _ := strconv.ParseUint(strings.ToLower(m[4]), 16, 8)
	return &TraceContext{
		TraceID:      strings.ToLower(m[2]),
		SpanID:       randHex(8), // local hop's new span_id
		ParentSpanID: strings.ToLower(m[3]),
		Flags:        byte(flags),
	}, true
}

// NewRootContext generates a fresh trace context (no inbound traceparent).
func NewRootContext() *TraceContext {
	return &TraceContext{
		TraceID: randHex(16),
		SpanID:  randHex(8),
		Flags:   0x01,
	}
}

// FormatTraceparent formats a context for outbound traceparent header.
func FormatTraceparent(c *TraceContext) string {
	return fmt.Sprintf("00-%s-%s-%02x", c.TraceID, c.SpanID, c.Flags)
}

// ─── Context plumbing ──────────────────────────────────────────────────────

type ctxKey struct{}

// WithContext binds a TraceContext into ctx. Used by the middleware; not
// normally called from application code.
func WithContext(ctx context.Context, tc *TraceContext) context.Context {
	return context.WithValue(ctx, ctxKey{}, tc)
}

// FromContext returns the active TraceContext, or nil.
func FromContext(ctx context.Context) *TraceContext {
	tc, _ := ctx.Value(ctxKey{}).(*TraceContext)
	return tc
}

// ─── StartSpan ─────────────────────────────────────────────────────────────

// StartSpan opens a span representing a unit of work and returns a child
// context whose active span is the new span. Caller MUST End() the span.
//
// Nested startSpan creates a child whose ParentSpanID is the active span
// at the time of the call. The returned context's TraceContext.SpanID is
// the new span's id, so subsequent outbound calls propagate the child id.
func StartSpan(ctx context.Context, name string, attrs map[string]any) (context.Context, *Span) {
	parent := FromContext(ctx)
	var tc *TraceContext
	if parent != nil {
		tc = &TraceContext{
			TraceID:      parent.TraceID,
			SpanID:       randHex(8),
			ParentSpanID: parent.SpanID,
			Flags:        parent.Flags,
		}
	} else {
		tc = NewRootContext()
	}

	cleanedAttrs := make(map[string]any, len(attrs))
	for k, v := range attrs {
		cleanedAttrs[k] = redactValue(k, v)
	}

	s := &Span{
		traceID:   tc.TraceID,
		spanID:    tc.SpanID,
		parentID:  tc.ParentSpanID,
		flags:     tc.Flags,
		name:      name,
		startedAt: time.Now(),
		attrs:     cleanedAttrs,
	}
	return WithContext(ctx, tc), s
}

// ─── LogEvent ──────────────────────────────────────────────────────────────

// LogEvent emits a structured event. Non-blocking; never returns error.
func LogEvent(ctx context.Context, env Envelope) {
	emit(env, FromContext(ctx))
}

// ─── CaptureError ──────────────────────────────────────────────────────────

// CaptureError records err with envelope context. Non-blocking; never
// returns error. The active span (if any) has its status flipped to
// StatusError but is not ended — the caller still controls span lifecycle.
func CaptureError(ctx context.Context, err error, env Envelope) {
	if err == nil {
		return
	}
	tc := FromContext(ctx)

	if sentryReady {
		safeFireAndForget(func() {
			hub := sentry.CurrentHub().Clone()
			hub.WithScope(func(scope *sentry.Scope) {
				scope.SetTag("event", env.Event)
				scope.SetTag("service", serviceName)
				scope.SetTag("env", deployEnv)
				if tc != nil {
					scope.SetTag("trace_id", tc.TraceID)
					scope.SetTag("span_id", tc.SpanID)
				}
				if env.Attrs != nil {
					scope.SetContext("attrs", redactObject(env.Attrs))
				}
				hub.CaptureException(err)
			})
		})
	}

	sev := env.Severity
	if sev == "" {
		sev = SeverityError
	}
	merged := mergeAttrs(env.Attrs, map[string]any{"error": err.Error()})
	emit(Envelope{Event: env.Event, Severity: sev, Attrs: merged}, tc)
}

// ─── Internal: emit ────────────────────────────────────────────────────────

func emit(env Envelope, tc *TraceContext) {
	sev := env.Severity
	if sev == "" {
		sev = SeverityInfo
	}
	if sev == SeverityDebug && mrand.Float64() > debugSampleRate {
		return
	}

	traceID := ""
	spanID := ""
	if tc != nil {
		traceID = tc.TraceID
		spanID = tc.SpanID
	} else {
		traceID = randHex(16)
		spanID = randHex(8)
	}

	event := map[string]any{
		"trace_id": traceID,
		"span_id":  spanID,
		"service":  serviceName,
		"env":      deployEnv,
		"event":    env.Event,
		"severity": string(sev),
		"attrs":    redactObject(env.Attrs),
		"ts":       time.Now().UnixMilli(),
	}

	// stdout mirror — visible in `fly logs`. Use slog so format is stable.
	switch sev {
	case SeverityError, SeverityFatal:
		emitJSON("error", event)
	case SeverityWarn:
		emitJSON("warn", event)
	default:
		emitJSON("info", event)
	}

	// Sentry breadcrumb so the next captureException carries this context.
	if sentryReady && sev != SeverityDebug {
		safeFireAndForget(func() {
			sentry.AddBreadcrumb(&sentry.Breadcrumb{
				Category: env.Event,
				Level:    sentryLevel(sev),
				Data:     redactObject(env.Attrs),
			})
		})
	}
}

func emitJSON(level string, event map[string]any) {
	b, err := json.Marshal(event)
	if err != nil {
		// Last-resort fallback; never let observability throw.
		logger.Warn("observability: marshal failed", "err", err.Error())
		return
	}
	switch level {
	case "error":
		logger.Error(string(b))
	case "warn":
		logger.Warn(string(b))
	default:
		logger.Info(string(b))
	}
}

func sentryLevel(s Severity) sentry.Level {
	switch s {
	case SeverityDebug:
		return sentry.LevelDebug
	case SeverityInfo:
		return sentry.LevelInfo
	case SeverityWarn:
		return sentry.LevelWarning
	case SeverityError:
		return sentry.LevelError
	case SeverityFatal:
		return sentry.LevelFatal
	default:
		return sentry.LevelInfo
	}
}

// safeFireAndForget runs fn in a goroutine and recovers any panic so
// observability errors never bubble out to the request path.
func safeFireAndForget(fn func()) {
	go func() {
		defer func() {
			if r := recover(); r != nil {
				logger.Warn("observability: emission panic recovered", "err", fmt.Sprint(r))
			}
		}()
		fn()
	}()
}

// ─── Redaction ────────────────────────────────────────────────────────────

var redactedKeys = []string{
	{{REDACTED_KEYS}}
}

func redactValue(key string, value any) any {
	k := strings.ToLower(key)
	for _, r := range redactedKeys {
		if strings.Contains(k, r) {
			return "[redacted]"
		}
	}
	return value
}

func redactObject(in map[string]any) map[string]any {
	if in == nil {
		return nil
	}
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[k] = redactValue(k, v)
	}
	return out
}

func mergeAttrs(base, extra map[string]any) map[string]any {
	out := make(map[string]any, len(base)+len(extra))
	for k, v := range base {
		out[k] = v
	}
	for k, v := range extra {
		if _, ok := out[k]; !ok {
			out[k] = v
		}
	}
	return out
}
