// Contract roundtrip test for the observability wrapper.
// Generated by the add-observability skill; lives in the project after
// scaffold so future regenerations can detect breakage.
//
// Tests verify the spec §10 contract WITHOUT requiring Sentry init —
// the wrapper must work standalone (stdout-only) when SENTRY_DSN is unset.
package {{PACKAGE_NAME}}

import (
	"context"
	"errors"
	"strings"
	"testing"
)

// ─── §10.3 traceparent roundtrip ──────────────────────────────────────────

func TestTraceparentRoundtrip(t *testing.T) {
	// Format → parse → format produces identical trace_id and parent_id.
	root := NewRootContext()
	header := FormatTraceparent(root)
	parsed, ok := ParseTraceparent(header)
	if !ok {
		t.Fatalf("ParseTraceparent rejected our own FormatTraceparent output: %q", header)
	}
	if parsed.TraceID != root.TraceID {
		t.Errorf("trace_id roundtrip: got %q want %q", parsed.TraceID, root.TraceID)
	}
	if parsed.ParentSpanID != root.SpanID {
		t.Errorf("parent_span_id roundtrip: got %q want %q", parsed.ParentSpanID, root.SpanID)
	}
}

func TestParseTraceparentMalformed(t *testing.T) {
	for _, header := range []string{
		"",
		"not-a-traceparent",
		"00-tooshort-tooshort-01",
		"00-XYZ-not-hex-01",
	} {
		_, ok := ParseTraceparent(header)
		if ok {
			t.Errorf("ParseTraceparent accepted malformed input: %q", header)
		}
	}
}

func TestParseTraceparentValid(t *testing.T) {
	// Canonical example from the W3C spec.
	header := "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01"
	tc, ok := ParseTraceparent(header)
	if !ok {
		t.Fatalf("rejected canonical W3C example: %q", header)
	}
	if tc.TraceID != "4bf92f3577b34da6a3ce929d0e0e4736" {
		t.Errorf("trace_id: got %q", tc.TraceID)
	}
	if tc.ParentSpanID != "00f067aa0ba902b7" {
		t.Errorf("parent_span_id: got %q", tc.ParentSpanID)
	}
	if len(tc.SpanID) != 16 {
		t.Errorf("local span_id should be 16 hex chars, got %d", len(tc.SpanID))
	}
	if tc.SpanID == tc.ParentSpanID {
		t.Errorf("local span_id should differ from parent (got both %q)", tc.SpanID)
	}
}

// ─── §10.5 PII discipline ─────────────────────────────────────────────────

// TestRedactionScrubsDefaultKeys asserts only against the keys that are
// guaranteed to be in the v0.2.1 default policy. Projects extend the list
// in policy.md (e.g. cparx adds "authorization", "jwt", "secret"); those
// project-specific extensions are tested by the project's own test fixture,
// not this generated one.
func TestRedactionScrubsDefaultKeys(t *testing.T) {
	cases := []struct {
		key  string
		want bool // true = should be redacted
	}{
		{"password", true},
		{"Password", true},           // case-insensitive
		{"user_password_hash", true}, // substring match
		{"api_key", true},
		{"card_number", true},
		{"ssn", true},
		{"user_id", false},
		{"email", false}, // not redacted by default; project may add
		{"event", false},
	}
	for _, c := range cases {
		got := redactValue(c.key, "secretvalue")
		isRedacted := got == "[redacted]"
		if isRedacted != c.want {
			t.Errorf("redactValue(%q): got redacted=%v, want %v", c.key, isRedacted, c.want)
		}
	}
}

func TestRedactObjectPreservesNonRedacted(t *testing.T) {
	in := map[string]any{
		"user_id":  "u_123",
		"password": "supersecret",
		"action":   "signup",
	}
	out := redactObject(in)
	if out["user_id"] != "u_123" {
		t.Errorf("user_id should pass through, got %v", out["user_id"])
	}
	if out["password"] != "[redacted]" {
		t.Errorf("password should be redacted, got %v", out["password"])
	}
	if out["action"] != "signup" {
		t.Errorf("action should pass through, got %v", out["action"])
	}
}

// ─── §10.5 fail-safe ──────────────────────────────────────────────────────

func TestEmitDoesNotPanicWithoutSentry(t *testing.T) {
	// Sentry is not initialized in this test; emit must still work via stdout.
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("emit panicked without Sentry init: %v", r)
		}
	}()
	emit(Envelope{
		Event:    "test_event",
		Severity: SeverityInfo,
		Attrs:    map[string]any{"k": "v"},
	}, nil)
}

func TestCaptureErrorWithNilErrIsNoop(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("CaptureError(nil) panicked: %v", r)
		}
	}()
	CaptureError(context.Background(), nil, Envelope{Event: "noop"})
}

func TestLogEventWithoutInitDoesNotThrow(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("LogEvent without Init panicked: %v", r)
		}
	}()
	LogEvent(context.Background(), Envelope{
		Event:    "test_event",
		Severity: SeverityInfo,
	})
}

// ─── §10.1 span lifecycle ─────────────────────────────────────────────────

func TestStartSpanReturnsChildContext(t *testing.T) {
	parentCtx := WithContext(context.Background(), NewRootContext())
	parent := FromContext(parentCtx)

	childCtx, span := StartSpan(parentCtx, "child", map[string]any{"k": "v"})
	defer span.End()

	child := FromContext(childCtx)
	if child == nil {
		t.Fatal("StartSpan returned context without active TraceContext")
	}
	if child.TraceID != parent.TraceID {
		t.Errorf("child trace_id should match parent: got %q want %q", child.TraceID, parent.TraceID)
	}
	if child.SpanID == parent.SpanID {
		t.Errorf("child span_id should differ from parent (both %q)", child.SpanID)
	}
	if child.ParentSpanID != parent.SpanID {
		t.Errorf("child parent_span_id should be parent's span_id: got %q want %q", child.ParentSpanID, parent.SpanID)
	}
}

func TestSpanEndIsIdempotent(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("double-end panicked: %v", r)
		}
	}()
	_, span := StartSpan(context.Background(), "test", nil)
	span.End()
	span.End() // should be a no-op, not a panic
}

func TestSpanEndWithStatusError(t *testing.T) {
	_, span := StartSpan(context.Background(), "test", nil)
	span.EndWithStatus(StatusError)
	// No assertion on emission shape — verifying that this path doesn't panic
	// and that a subsequent End() is a no-op (idempotency).
	span.End()
}

// ─── §10.2 envelope shape (smoke test) ────────────────────────────────────

func TestCaptureErrorAttachesErrorMessage(t *testing.T) {
	// We can't easily intercept emit() output without a test seam, but we
	// can verify CaptureError does not throw when given a real error and
	// attaches the error string into the merged attrs.
	err := errors.New("boom: " + strings.Repeat("x", 100))
	defer func() {
		if r := recover(); r != nil {
			t.Errorf("CaptureError panicked on real error: %v", r)
		}
	}()
	CaptureError(context.Background(), err, Envelope{
		Event:    "test_capture",
		Severity: SeverityError,
		Attrs:    map[string]any{"k": "v"},
	})
}
