/**
 * Observability wrapper — AgenticApps spec §10 v0.2.0
 *
 * Service:     test-service
 * Destination: sentry
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong below the "Project-specific extensions" section.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)     non-blocking emission of a structured event
 *  - captureError(err, env) record an error with envelope context
 *  - startSpan(name, attrs) open a span representing a unit of work
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 */
export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";
export interface Envelope {
    event: string;
    severity?: Severity;
    attrs?: Record<string, unknown>;
}
export interface Span {
    setAttribute(key: string, value: unknown): void;
    setStatus(status: SpanStatus): void;
    end(opts?: {
        status?: SpanStatus;
    }): void;
    readonly traceId: string;
    readonly spanId: string;
}
export interface TraceContext {
    traceId: string;
    spanId: string;
    parentSpanId?: string;
    flags: number;
}
export interface InitEnv {
    SENTRY_DSN?: string;
    DEPLOY_ENV?: string;
    SERVICE_NAME?: string;
}
/**
 * Initialize the wrapper. Called once per Worker invocation by the
 * `withObservability` middleware (see middleware.ts). Idempotent.
 *
 * Sentry SDK initialisation is handled by `withSentry(optionsFactory, handler)`
 * at the entry-file site (see INIT.md Phase 5 detail). `@sentry/cloudflare`
 * v8 removed `Sentry.init`; the per-request `withSentry` wrap is the
 * canonical setup point. This function only sets local module state
 * (service name, deploy env, waitUntil binding) and records whether a
 * DSN was present so downstream `Sentry.withScope` / `captureException`
 * / `addBreadcrumb` calls in this module can be gated on the same flag.
 */
export declare function init(env: InitEnv, ctx: ExecutionContext): void;
/**
 * Parse an inbound traceparent header. Returns a TraceContext with a
 * fresh local span_id (the local hop's span); parentSpanId is the
 * span_id from the inbound header.
 */
export declare function parseTraceparent(header: string | null | undefined): TraceContext | null;
/** Generate a fresh root TraceContext (no inbound traceparent). */
export declare function newRootContext(): TraceContext;
/** Format a TraceContext for outbound traceparent header. */
export declare function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string;
/**
 * Run `fn` with the given trace context as the active span. Used by the
 * middleware to bind a request to its trace; not normally called from
 * application code.
 */
export declare function runWithContext<T>(ctx: TraceContext, name: string, fn: () => T): T;
/** Read the active TraceContext, if any. */
export declare function getActiveContext(): TraceContext | null;
/**
 * Open a span representing a unit of work. The returned Span MUST be
 * .end()-ed; ending the span emits a span event.
 *
 * Note: nested startSpan calls produce sibling spans under the active
 * trace. Their parent_span_id is the active span's span_id at the time
 * startSpan was called. Cloudflare Workers' AsyncLocalStorage cannot
 * mutate the active context without a callback, so for full nested-span
 * tracing prefer Sentry.startSpan(...) callback style. Spec §10.1
 * accepts either shape.
 */
export declare function startSpan(name: string, attributes?: Record<string, unknown>): Span;
export declare function logEvent(envelope: Envelope): void;
export declare function captureError(err: unknown, envelope: Envelope): void;
