#!/usr/bin/env bash
# Fixture 12 — codex M-2 negative case. Seeds dist/server/{index.ts, middleware.ts}
# — a typed compiled output that happens to contain BOTH the index.ts anchor AND
# the middleware.ts co-anchor adjacent. Without the dist-path filter, Plan 02's
# sibling-anchor check (alone) would PASS this candidate to classify_stack. The
# dist-path filter (codex M-2) drops it before classification. Engine must exit 0,
# NOT write cron-monitor.ts under dist/server/, version still bumps to 1.18.0.
set -eu
. "$FIXTURES_ROOT/common-setup.sh"

# Simulate Worker bundler typed-output shape: a server/ subdir under dist/
# that contains both index.ts (the compiled entry) and middleware.ts (e.g.,
# a stub generated by a build tool). Real-world precedent: esbuild/wrangler
# may emit such pairs for monorepos with multiple Worker entries.
mkdir -p dist/server
cat > dist/server/index.ts <<'EOF'
// Compiled bundle entry — NOT a wrapper. Has sibling middleware.ts but is dist/.
export default { fetch: () => new Response("compiled bundle") };
EOF
cat > dist/server/middleware.ts <<'EOF'
// Compiled bundle middleware stub — NOT a wrapper.
export const middlewareNoop = () => undefined;
EOF

# No real wrapper anywhere else — engine sees only the dist/server pair.
# Project at v1.17.0; engine should hit no-wrapper-found path and bump to 1.18.0.
