/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-cloudflare-worker).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
 *   D1 — separate-wrapper export
 *   D5a — innermost composition under withSentry(withObservabilityScheduled(...))
 *   D6 — 3-source slug resolution (explicit > env > auto-derive)
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (2nd arg)
 *         on the in_progress checkin only
 *   R04 (PLAN revisions) — SENTRY_DEBUG=1 opt-in console.error in catch blocks
 *
 * Phase 23 / ADR-0029 — Guarded Shape A refactor:
 *   D-08 — withCronMonitor now composes Sentry.withMonitor instead of hand-rolling
 *           captureCheckIn lifecycle. Tests updated to assert withMonitor invocation
 *           contract + handlerStarted guard behaviour.
 *
 * Sentry SDK is mocked at the module boundary so SDK shape doesn't matter at
 * test-time — only the invocation contract does.
 */

import { describe, it, expect, vi, beforeEach, afterEach, expectTypeOf } from "vitest";
// MonitorConfig lives in @sentry/core (not re-exported from @sentry/cloudflare's public API).
// Using @sentry/core directly for the Pitfall 4 type-pin firewall (D-16).
import type { MonitorConfig as SentryMonitorConfig } from "@sentry/core";
import { withCronMonitor, type CronMonitorSchedule } from "./cron-monitor";

const withMonitor = vi.fn();
vi.mock("@sentry/cloudflare", () => ({
  withMonitor: (...args: unknown[]) => withMonitor(...args),
}));

const fakeController = { scheduledTime: 0, cron: "*/15 * * * *" } as ScheduledController;
const fakeCtx = { waitUntil: vi.fn(), passThroughOnException: vi.fn() } as unknown as ExecutionContext;

beforeEach(() => {
  withMonitor.mockReset();
  // Default: withMonitor calls its callback and returns the result.
  withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => cb());
});

describe("withCronMonitor — Guarded Shape A (ADR-0029 / D-08)", () => {
  it("calls Sentry.withMonitor with resolved slug and monitorConfig on happy path", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "fxsa-ingest-15min",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(withMonitor).toHaveBeenCalledOnce();
    expect(withMonitor).toHaveBeenCalledWith(
      "fxsa-ingest-15min",
      expect.any(Function),
      { schedule: { type: "crontab", value: "*/15 * * * *" }, maxRuntime: 240 },
    );
    expect(handler).toHaveBeenCalledOnce();
  });

  it("handler return value propagates through withMonitor callback", async () => {
    const handler = vi.fn(async () => "result-value");
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);
    expect(handler).toHaveBeenCalledOnce();
  });

  it("handler exception re-throws from withMonitor (post-callback error propagates)", async () => {
    const boom = new Error("handler exploded");
    const handler = vi.fn(async () => { throw boom; });
    // withMonitor calls cb() and re-throws whatever it throws
    withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => cb());
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await expect(
      wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx),
    ).rejects.toBe(boom);

    expect(handler).toHaveBeenCalledOnce();
  });

  it("no-ops cleanly when SENTRY_DSN is unset (R02 fail-safe preserved)", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await wrapped(fakeController, {} as Record<string, unknown>, fakeCtx);

    expect(handler).toHaveBeenCalledOnce();
    expect(withMonitor).not.toHaveBeenCalled();
  });

  // Guarded Shape A — core guard: pre-callback transport throw → handler runs unmonitored.
  it("D-08 guard: withMonitor throws BEFORE callback runs → handler still executes unmonitored", async () => {
    const handler = vi.fn(async () => {});
    // withMonitor throws without ever invoking the callback (simulates transport failure
    // on the in_progress check-in sent before the callback is called).
    withMonitor.mockRejectedValue(new Error("Sentry transport failure"));

    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    // Must NOT throw — falls back to unmonitored handler.
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(handler).toHaveBeenCalledOnce();
  });

  it("D-08 guard: withMonitor throws AFTER callback ran → error propagates (post-callback)", async () => {
    const handler = vi.fn(async () => {});
    // withMonitor calls callback then throws (simulates post-callback transport failure).
    withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => {
      await cb(); // callback ran — handlerStarted = true
      throw new Error("post-callback transport failure");
    });

    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    await expect(
      wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx),
    ).rejects.toThrow("post-callback transport failure");

    expect(handler).toHaveBeenCalledOnce();
  });
});

describe("withCronMonitor — slug resolution (D6)", () => {
  it("uses explicit config.monitorSlug above all sources", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith("explicit-wins", expect.any(Function), undefined);
  });

  it("falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler); // no explicit slug

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-wins",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith("env-wins", expect.any(Function), undefined);
  });

  it("falls back to auto-derived ${SERVICE_NAME}:${controller.cron} when neither set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler);

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SERVICE_NAME: "fxsa-worker",
    } as Record<string, unknown>, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith("fxsa-worker:*/15 * * * *", expect.any(Function), undefined);
  });
});

describe("withCronMonitor — monitorConfig forwarding (D12 / ADR-0029)", () => {
  it("passes monitorConfig as 3rd arg to withMonitor when schedule + maxRuntimeSeconds set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });

    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith(
      "x",
      expect.any(Function),
      { schedule: { type: "crontab", value: "*/15 * * * *" }, maxRuntime: 240 },
    );
  });

  it("passes undefined as 3rd arg when neither schedule nor maxRuntimeSeconds configured", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);
    expect(withMonitor).toHaveBeenCalledWith("x", expect.any(Function), undefined);
  });
});

// ─── Phase 25 D-16 — type-level firewall (Pitfall 4 / ADR-0032) ─────────────
// The template test harness's tsconfig.json writes `skipLibCheck: true`,
// which means Sentry-type compatibility (the WHOLE POINT of D-03) is NOT
// asserted at typecheck time. These two assertions are the explicit firewall:
//   (1) expectTypeOf checks against our own type literally
//   (2) `const _: Sentry.MonitorConfig['schedule'] = ourSchedule` pins
//       structural compatibility against the real Sentry type at module-load
//       time (no skipLibCheck bypass because the value-level binding forces
//       the type-check).

describe("CronMonitorSchedule — D-16 type-level firewall (Pitfall 4)", () => {
  it("crontab variant accepts { type: 'crontab', value: string } (regression)", () => {
    const schedule: CronMonitorSchedule = { type: "crontab", value: "*/15 * * * *" };
    expect(schedule.type).toBe("crontab");
  });

  it("interval variant requires value: number + unit (D-03 / ADR-0032)", () => {
    type IntervalVariant = Extract<CronMonitorSchedule, { type: "interval" }>;
    expectTypeOf<IntervalVariant>().toHaveProperty("value").toBeNumber();
    expectTypeOf<IntervalVariant>().toHaveProperty("unit").toEqualTypeOf<
      "minute" | "hour" | "day" | "week" | "month" | "year"
    >();
  });

  it("interval variant REJECTS value: string at typecheck time (D-03 firewall)", () => {
    // @ts-expect-error — interval requires value: number, not string. If this
    // line ever stops erroring, D-03 has regressed (CronMonitorSchedule reverted
    // to the broken interface shape).
    const bad: CronMonitorSchedule = { type: "interval", value: "5", unit: "minute" };
    void bad;
  });

  it("is structurally assignable to SentryMonitorConfig['schedule'] (Pitfall 4 pin)", () => {
    // This is the explicit firewall against the harness's skipLibCheck blind spot.
    // Uses @sentry/core MonitorConfig (where the type lives; not re-exported from @sentry/cloudflare).
    const ourCrontab: CronMonitorSchedule = { type: "crontab", value: "*/15 * * * *" };
    const ourInterval: CronMonitorSchedule = { type: "interval", value: 5, unit: "minute" };
    const _checkCrontab: SentryMonitorConfig["schedule"] = ourCrontab;
    const _checkInterval: SentryMonitorConfig["schedule"] = ourInterval;
    void _checkCrontab;
    void _checkInterval;
  });
});

// ─── Phase 25 D-16 (D-05 strict-Env subset — cf-worker ONLY) ────────────────
// Verifies that withCronMonitor accepts a strict-typed Env interface (no index
// signature). Pre-D-05, the constraint `E extends Record<string, unknown>`
// rejected such interfaces unless callers added `[key: string]: unknown` or
// cast at every call site. After D-05 (narrowed scope: cf-worker only), this
// compiles natively.

interface CallbotEnv {
  SENTRY_DSN: string;
  SERVICE_NAME: string;
  SUPABASE_URL: string;
  // NO index signature.
}

describe("withCronMonitor — D-16 strict-Env generic narrowing (cf-worker only)", () => {
  it("accepts a strict-typed Env interface without index signature", async () => {
    const handler = vi.fn(async () => {});
    // This call must compile against the narrowed generic (D-05). If the
    // generic regresses to `Record<string, unknown>`, this line fails type-check.
    const wrapped = withCronMonitor<CallbotEnv>(handler, { monitorSlug: "callbot:ingest" });
    await wrapped(
      fakeController,
      { SENTRY_DSN: "https://stub@sentry.io/1", SERVICE_NAME: "callbot", SUPABASE_URL: "https://s.co" },
      fakeCtx,
    );
    expect(handler).toHaveBeenCalledOnce();
  });
});
