/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-cloudflare-worker).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
 *   D1 — separate-wrapper export
 *   D5a — innermost composition under withSentry(withObservabilityScheduled(...))
 *   D6 — 3-source slug resolution (explicit > env > auto-derive)
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (2nd arg)
 *         on the in_progress checkin only
 *   R04 (PLAN revisions) — SENTRY_DEBUG=1 opt-in console.error in catch blocks
 *
 * Phase 23 / ADR-0029 — Guarded Shape A refactor:
 *   D-08 — withCronMonitor now composes Sentry.withMonitor instead of hand-rolling
 *           captureCheckIn lifecycle. Tests updated to assert withMonitor invocation
 *           contract + handlerStarted guard behaviour.
 *
 * Sentry SDK is mocked at the module boundary so SDK shape doesn't matter at
 * test-time — only the invocation contract does.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { withCronMonitor } from "./cron-monitor";

const withMonitor = vi.fn();
vi.mock("@sentry/cloudflare", () => ({
  withMonitor: (...args: unknown[]) => withMonitor(...args),
}));

const fakeController = { scheduledTime: 0, cron: "*/15 * * * *" } as ScheduledController;
const fakeCtx = { waitUntil: vi.fn(), passThroughOnException: vi.fn() } as unknown as ExecutionContext;

beforeEach(() => {
  withMonitor.mockReset();
  // Default: withMonitor calls its callback and returns the result.
  withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => cb());
});

describe("withCronMonitor — Guarded Shape A (ADR-0029 / D-08)", () => {
  it("calls Sentry.withMonitor with resolved slug and monitorConfig on happy path", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "fxsa-ingest-15min",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(withMonitor).toHaveBeenCalledOnce();
    expect(withMonitor).toHaveBeenCalledWith(
      "fxsa-ingest-15min",
      expect.any(Function),
      { schedule: { type: "crontab", value: "*/15 * * * *" }, maxRuntime: 240 },
    );
    expect(handler).toHaveBeenCalledOnce();
  });

  it("handler return value propagates through withMonitor callback", async () => {
    const handler = vi.fn(async () => "result-value");
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);
    expect(handler).toHaveBeenCalledOnce();
  });

  it("handler exception re-throws from withMonitor (post-callback error propagates)", async () => {
    const boom = new Error("handler exploded");
    const handler = vi.fn(async () => { throw boom; });
    // withMonitor calls cb() and re-throws whatever it throws
    withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => cb());
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await expect(
      wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx),
    ).rejects.toBe(boom);

    expect(handler).toHaveBeenCalledOnce();
  });

  it("no-ops cleanly when SENTRY_DSN is unset (R02 fail-safe preserved)", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await wrapped(fakeController, {} as Record<string, unknown>, fakeCtx);

    expect(handler).toHaveBeenCalledOnce();
    expect(withMonitor).not.toHaveBeenCalled();
  });

  // Guarded Shape A — core guard: pre-callback transport throw → handler runs unmonitored.
  it("D-08 guard: withMonitor throws BEFORE callback runs → handler still executes unmonitored", async () => {
    const handler = vi.fn(async () => {});
    // withMonitor throws without ever invoking the callback (simulates transport failure
    // on the in_progress check-in sent before the callback is called).
    withMonitor.mockRejectedValue(new Error("Sentry transport failure"));

    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    // Must NOT throw — falls back to unmonitored handler.
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(handler).toHaveBeenCalledOnce();
  });

  it("D-08 guard: withMonitor throws AFTER callback ran → error propagates (post-callback)", async () => {
    const handler = vi.fn(async () => {});
    // withMonitor calls callback then throws (simulates post-callback transport failure).
    withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => {
      await cb(); // callback ran — handlerStarted = true
      throw new Error("post-callback transport failure");
    });

    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    await expect(
      wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx),
    ).rejects.toThrow("post-callback transport failure");

    expect(handler).toHaveBeenCalledOnce();
  });
});

describe("withCronMonitor — slug resolution (D6)", () => {
  it("uses explicit config.monitorSlug above all sources", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith("explicit-wins", expect.any(Function), undefined);
  });

  it("falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler); // no explicit slug

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-wins",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith("env-wins", expect.any(Function), undefined);
  });

  it("falls back to auto-derived ${SERVICE_NAME}:${controller.cron} when neither set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler);

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SERVICE_NAME: "fxsa-worker",
    } as Record<string, unknown>, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith("fxsa-worker:*/15 * * * *", expect.any(Function), undefined);
  });
});

describe("withCronMonitor — monitorConfig forwarding (D12 / ADR-0029)", () => {
  it("passes monitorConfig as 3rd arg to withMonitor when schedule + maxRuntimeSeconds set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });

    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(withMonitor).toHaveBeenCalledWith(
      "x",
      expect.any(Function),
      { schedule: { type: "crontab", value: "*/15 * * * *" }, maxRuntime: 240 },
    );
  });

  it("passes undefined as 3rd arg when neither schedule nor maxRuntimeSeconds configured", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);
    expect(withMonitor).toHaveBeenCalledWith("x", expect.any(Function), undefined);
  });
});
