/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-cloudflare-worker).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
 *   D1 — separate-wrapper export
 *   D5a — innermost composition under withSentry(withObservabilityScheduled(...))
 *   D6 — 3-source slug resolution (explicit > env > auto-derive)
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (2nd arg)
 *         on the in_progress checkin only
 *   R04 (PLAN revisions) — SENTRY_DEBUG=1 opt-in console.error in catch blocks
 *
 * Sentry SDK is mocked at the module boundary so SDK shape doesn't matter at
 * test-time — only the invocation contract does.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { withCronMonitor } from "./cron-monitor";

const captureCheckIn = vi.fn();
vi.mock("@sentry/cloudflare", () => ({
  captureCheckIn: (...args: unknown[]) => captureCheckIn(...args),
}));

const fakeController = { scheduledTime: 0, cron: "*/15 * * * *" } as ScheduledController;
const fakeCtx = { waitUntil: vi.fn(), passThroughOnException: vi.fn() } as unknown as ExecutionContext;

beforeEach(() => {
  captureCheckIn.mockReset();
  captureCheckIn.mockReturnValueOnce("checkin-abc"); // 1st call returns checkInId
});

describe("withCronMonitor — cron checkin behavior", () => {
  it("emits in_progress + ok on happy path", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(handler).toHaveBeenCalledOnce();
    expect(captureCheckIn).toHaveBeenCalledTimes(2);
    expect(captureCheckIn).toHaveBeenNthCalledWith(1, { monitorSlug: "fxsa-ingest-15min", status: "in_progress" });
    expect(captureCheckIn).toHaveBeenNthCalledWith(2, { checkInId: "checkin-abc", monitorSlug: "fxsa-ingest-15min", status: "ok" });
  });

  it("emits in_progress + error and re-throws on handler exception", async () => {
    const boom = new Error("handler exploded");
    const handler = vi.fn(async () => { throw boom; });
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await expect(
      wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx),
    ).rejects.toBe(boom);

    expect(captureCheckIn).toHaveBeenCalledTimes(2);
    expect(captureCheckIn).toHaveBeenNthCalledWith(1, { monitorSlug: "fxsa-ingest-15min", status: "in_progress" });
    expect(captureCheckIn).toHaveBeenNthCalledWith(2, { checkInId: "checkin-abc", monitorSlug: "fxsa-ingest-15min", status: "error" });
  });

  it("no-ops cleanly when SENTRY_DSN is unset", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await wrapped(fakeController, {} as Record<string, unknown>, fakeCtx);

    expect(handler).toHaveBeenCalledOnce();
    expect(captureCheckIn).not.toHaveBeenCalled();
  });
});

describe("withCronMonitor — slug resolution (D6)", () => {
  it("uses explicit config.monitorSlug above all sources", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>, fakeCtx);

    expect(captureCheckIn).toHaveBeenNthCalledWith(1, expect.objectContaining({ monitorSlug: "explicit-wins" }));
  });

  it("falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler); // no explicit slug

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-wins",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>, fakeCtx);

    expect(captureCheckIn).toHaveBeenNthCalledWith(1, expect.objectContaining({ monitorSlug: "env-wins" }));
  });

  it("falls back to auto-derived ${SERVICE_NAME}:${controller.cron} when neither set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler);

    await wrapped(fakeController, {
      SENTRY_DSN: "https://stub@sentry.io/1",
      SERVICE_NAME: "fxsa-worker",
    } as Record<string, unknown>, fakeCtx);

    expect(captureCheckIn).toHaveBeenNthCalledWith(1, expect.objectContaining({ monitorSlug: "fxsa-worker:*/15 * * * *" }));
  });
});

describe("withCronMonitor — monitorConfig forwarding (D12 / R03)", () => {
  it("forwards monitorConfig on in_progress, omits on completion", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });

    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);

    expect(captureCheckIn).toHaveBeenCalledTimes(2);
    // 1st call (in_progress) — 2nd arg is monitorConfig with schedule + maxRuntime
    expect(vi.mocked(captureCheckIn).mock.calls[0][1]).toEqual({
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntime: 240,
    });
    // 2nd call (ok) — 2nd arg is undefined (Sentry already has monitor config)
    expect(vi.mocked(captureCheckIn).mock.calls[1][1]).toBeUndefined();
  });

  it("omits monitorConfig entirely when neither schedule nor maxRuntimeSeconds is configured", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);
    expect(vi.mocked(captureCheckIn).mock.calls[0][1]).toBeUndefined();
  });
});

describe("withCronMonitor — SENTRY_DEBUG opt-in logging (R04)", () => {
  let errorSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
  });

  afterEach(() => {
    errorSpy.mockRestore();
  });

  it("logs swallowed errors when SENTRY_DEBUG=1, silent otherwise", async () => {
    // Make captureCheckIn throw on every call so the swallow-catch fires.
    captureCheckIn.mockReset();
    captureCheckIn.mockImplementation(() => { throw new Error("sentry SDK boom"); });

    const handler = vi.fn(async () => {});

    // SENTRY_DEBUG absent → silent
    const wrappedSilent = withCronMonitor(handler, { monitorSlug: "x" });
    await wrappedSilent(fakeController, { SENTRY_DSN: "https://stub@sentry.io/1" }, fakeCtx);
    expect(errorSpy).not.toHaveBeenCalled();

    // SENTRY_DEBUG=1 → console.error called
    const wrappedDebug = withCronMonitor(handler, { monitorSlug: "x" });
    await wrappedDebug(
      fakeController,
      { SENTRY_DSN: "https://stub@sentry.io/1", SENTRY_DEBUG: "1" } as Record<string, unknown>,
      fakeCtx,
    );
    expect(errorSpy).toHaveBeenCalled();
    expect(errorSpy.mock.calls[0]).toEqual(expect.arrayContaining([expect.any(Error)]));
  });
});
