/**
 * healthz-snippet.test.ts — healthz handler contract suite (ts-cloudflare-worker).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the COPY-ONLY healthz template's contract per phase-22 CONTEXT.md
 * and PLAN.md REVISIONS R06 + R07:
 *
 *   D9  — healthz NOT wrapped by withObservability (no span overhead on the
 *         health endpoint; trivial dep-probe payload + structured JSON).
 *   R06 — fail-closed on zero probes configured: returns 503 with
 *         `{status:"degraded", reason:"no probes configured — adapt
 *         healthz-snippet.ts to your dependencies", checks:{}}`.
 *   R07 — top-of-file multi-line WARNING block on every snippet (presence
 *         asserted structurally via the impl file's first bytes when GREEN).
 *
 * The handler is a COPY-ONLY template: the test exercises the shape the
 * operator gets BEFORE adaptation (no probes wired) and AFTER adaptation
 * (probes wired via env bindings).
 *
 * Worker stack bindings used as adaptation targets:
 *   - OBSERVABILITY_KV  — KV namespace; probe = `get("healthz-probe")`
 *   - SERVICE_BINDING   — service binding; probe = `fetch("/healthz")`
 */

import { describe, it, expect, vi } from "vitest";
import { healthzHandler } from "./healthz-snippet";

describe("healthzHandler — fail-closed default (R06)", () => {
  it("returns 503 status:degraded with reason when no probes configured", async () => {
    const res = await healthzHandler(new Request("https://stub/healthz"), {});
    expect(res.status).toBe(503);
    expect(res.headers.get("content-type")).toMatch(/application\/json/);
    const body = await res.json();
    expect(body).toEqual({
      status: "degraded",
      reason: "no probes configured — adapt healthz-snippet.ts to your dependencies",
      checks: {},
    });
  });
});

describe("healthzHandler — all probes pass", () => {
  it("returns 200 status:ok with per-check breakdown when KV probe succeeds", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockResolvedValue(null) },
    };
    const res = await healthzHandler(new Request("https://stub/healthz"), env);
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({ status: "ok", checks: { kv: true } });
  });

  it("returns 200 status:ok when both KV and service binding pass (binding returns 200)", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockResolvedValue(null) },
      SERVICE_BINDING: {
        fetch: vi.fn().mockResolvedValue(new Response("ok", { status: 200 })),
      },
    };
    const res = await healthzHandler(new Request("https://stub/healthz"), env);
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({
      status: "ok",
      checks: { kv: true, serviceBinding: true },
    });
  });
});

describe("healthzHandler — any probe failure → degraded", () => {
  it("returns 503 status:degraded with per-check breakdown when KV throws", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockRejectedValue(new Error("kv down")) },
      SERVICE_BINDING: {
        fetch: vi.fn().mockResolvedValue(new Response("ok", { status: 200 })),
      },
    };
    const res = await healthzHandler(new Request("https://stub/healthz"), env);
    expect(res.status).toBe(503);
    const body = await res.json();
    expect(body).toEqual({
      status: "degraded",
      checks: { kv: false, serviceBinding: true },
    });
  });

  it("treats 5xx from service binding as a failed probe", async () => {
    const env = {
      SERVICE_BINDING: {
        fetch: vi.fn().mockResolvedValue(new Response("nope", { status: 503 })),
      },
    };
    const res = await healthzHandler(new Request("https://stub/healthz"), env);
    expect(res.status).toBe(503);
    const body = await res.json();
    expect(body).toEqual({
      status: "degraded",
      checks: { serviceBinding: false },
    });
  });

  it("treats service binding fetch throw as a failed probe", async () => {
    const env = {
      SERVICE_BINDING: {
        fetch: vi.fn().mockRejectedValue(new Error("network gone")),
      },
    };
    const res = await healthzHandler(new Request("https://stub/healthz"), env);
    expect(res.status).toBe(503);
    const body = await res.json();
    expect(body).toEqual({
      status: "degraded",
      checks: { serviceBinding: false },
    });
  });
});
