/**
 * Observability wrapper — AgenticApps spec §10 v0.2.0
 *
 * Service:     {{SERVICE_NAME}}
 * Destination: {{DESTINATION}}
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong below the "Project-specific extensions" section.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)     non-blocking emission of a structured event
 *  - captureError(err, env) record an error with envelope context
 *  - startSpan(name, attrs) open a span representing a unit of work
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import * as Sentry from "@sentry/cloudflare";

// ─── Types ─────────────────────────────────────────────────────────────────

export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";

export interface Envelope {
  event: string;
  severity?: Severity;
  attrs?: Record<string, unknown>;
}

export interface Span {
  setAttribute(key: string, value: unknown): void;
  setStatus(status: SpanStatus): void;
  end(opts?: { status?: SpanStatus }): void;
  readonly traceId: string;
  readonly spanId: string;
}

export interface TraceContext {
  traceId: string;       // 32 hex chars (W3C trace-id)
  spanId: string;        // 16 hex chars (W3C span-id of current span)
  parentSpanId?: string; // 16 hex chars (W3C parent-id)
  flags: number;         // W3C trace flags byte
}

interface InternalSpanContext extends TraceContext {
  startedAt: number;
  name: string;
  attributes: Record<string, unknown>;
  status: SpanStatus | "unset";
}

// ─── Static config (parameterized at generation time) ─────────────────────

const SERVICE_DEFAULT = "{{SERVICE_NAME}}";
const DEBUG_SAMPLE_RATE = {{DEBUG_SAMPLE_RATE}};
const TRACE_SAMPLE_RATE = {{TRACE_SAMPLE_RATE}};

// REDACTED_KEYS is inlined from policy.md by the generator. Keys whose
// names contain any of these substrings (case-insensitive) are scrubbed
// before emission.
const REDACTED_KEYS: ReadonlyArray<string> = [
  {{REDACTED_KEYS}}
];

// ─── Module state ─────────────────────────────────────────────────────────

const spanStorage = new AsyncLocalStorage<InternalSpanContext>();

let initialized = false;
let serviceName: string = SERVICE_DEFAULT;
let deployEnv: string = "dev";
let waitUntilFn: ((p: Promise<unknown>) => void) | null = null;

// ─── Initialization ───────────────────────────────────────────────────────

export interface InitEnv {
  {{ENV_VAR_DSN}}?: string;
  {{ENV_VAR_ENV}}?: string;
  {{ENV_VAR_SERVICE}}?: string;
}

/**
 * Initialize the wrapper. Called once per Worker invocation by the
 * `withObservability` middleware (see middleware.ts). Idempotent.
 */
export function init(env: InitEnv, ctx: ExecutionContext): void {
  serviceName = env.{{ENV_VAR_SERVICE}} ?? SERVICE_DEFAULT;
  deployEnv = env.{{ENV_VAR_ENV}} ?? "dev";

  // Capture waitUntil so emission can be fire-and-forget without
  // blocking the response. Wrapping in try/catch so a missing ctx
  // (out-of-request emission) degrades to drop, not throw.
  try {
    waitUntilFn = (p) => ctx.waitUntil(p);
  } catch {
    waitUntilFn = null;
  }

  if (initialized) return;
  const dsn = env.{{ENV_VAR_DSN}};
  if (dsn) {
    Sentry.init({
      dsn,
      environment: deployEnv,
      release: serviceName,
      tracesSampleRate: TRACE_SAMPLE_RATE,
      sendDefaultPii: false,
    });
  }
  initialized = true;
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

const TRACEPARENT_RE = /^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/i;

function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Parse an inbound traceparent header. Returns a TraceContext with a
 * fresh local span_id (the local hop's span); parentSpanId is the
 * span_id from the inbound header.
 */
export function parseTraceparent(header: string | null | undefined): TraceContext | null {
  if (!header) return null;
  const m = TRACEPARENT_RE.exec(header.trim());
  if (!m) return null;
  return {
    traceId: m[2].toLowerCase(),
    spanId: randHex(8),
    parentSpanId: m[3].toLowerCase(),
    flags: parseInt(m[4], 16),
  };
}

/** Generate a fresh root TraceContext (no inbound traceparent). */
export function newRootContext(): TraceContext {
  return {
    traceId: randHex(16),
    spanId: randHex(8),
    flags: 1,
  };
}

/** Format a TraceContext for outbound traceparent header. */
export function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string {
  return `00-${c.traceId}-${c.spanId}-${c.flags.toString(16).padStart(2, "0")}`;
}

// ─── Run-with-context (used by middleware) ────────────────────────────────

/**
 * Run `fn` with the given trace context as the active span. Used by the
 * middleware to bind a request to its trace; not normally called from
 * application code.
 */
export function runWithContext<T>(ctx: TraceContext, name: string, fn: () => T): T {
  const internal: InternalSpanContext = {
    ...ctx,
    startedAt: Date.now(),
    name,
    attributes: {},
    status: "unset",
  };
  return spanStorage.run(internal, fn);
}

/** Read the active TraceContext, if any. */
export function getActiveContext(): TraceContext | null {
  const c = spanStorage.getStore();
  return c ? { traceId: c.traceId, spanId: c.spanId, parentSpanId: c.parentSpanId, flags: c.flags } : null;
}

// ─── startSpan ────────────────────────────────────────────────────────────

/**
 * Open a span representing a unit of work. The returned Span MUST be
 * .end()-ed; ending the span emits a span event.
 *
 * Note: nested startSpan calls produce sibling spans under the active
 * trace. Their parent_span_id is the active span's span_id at the time
 * startSpan was called. Cloudflare Workers' AsyncLocalStorage cannot
 * mutate the active context without a callback, so for full nested-span
 * tracing prefer Sentry.startSpan(...) callback style. Spec §10.1
 * accepts either shape.
 */
export function startSpan(name: string, attributes: Record<string, unknown> = {}): Span {
  const parent = spanStorage.getStore();
  const ctx: TraceContext = parent
    ? { traceId: parent.traceId, spanId: randHex(8), parentSpanId: parent.spanId, flags: parent.flags }
    : newRootContext();

  const startedAt = Date.now();
  const attrs: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(attributes)) attrs[k] = redactValue(k, v);

  let status: SpanStatus | "unset" = "unset";
  let ended = false;

  const span: Span = {
    setAttribute(key, value) {
      attrs[key] = redactValue(key, value);
    },
    setStatus(s) {
      status = s;
    },
    end(opts) {
      if (ended) return;
      ended = true;
      if (opts?.status) status = opts.status;
      const finalStatus: SpanStatus = status === "unset" ? "ok" : status;
      emit(
        {
          event: name,
          severity: finalStatus === "error" ? "error" : "info",
          attrs: { ...attrs, duration_ms: Date.now() - startedAt, span_status: finalStatus },
        },
        ctx,
      );
    },
    get traceId() { return ctx.traceId; },
    get spanId() { return ctx.spanId; },
  };
  return span;
}

// ─── logEvent ─────────────────────────────────────────────────────────────

export function logEvent(envelope: Envelope): void {
  const ctx = spanStorage.getStore();
  emit(envelope, ctx ?? null);
}

// ─── captureError ─────────────────────────────────────────────────────────

export function captureError(err: unknown, envelope: Envelope): void {
  const ctx = spanStorage.getStore();
  if (ctx) ctx.status = "error";

  if (initialized && err instanceof Error) {
    safeFireAndForget(() => {
      Sentry.withScope((scope) => {
        scope.setTag("event", envelope.event);
        scope.setTag("service", serviceName);
        scope.setTag("env", deployEnv);
        if (ctx) {
          scope.setTag("trace_id", ctx.traceId);
          scope.setTag("span_id", ctx.spanId);
        }
        if (envelope.attrs) {
          scope.setContext("attrs", redactObject(envelope.attrs));
        }
        Sentry.captureException(err);
      });
    });
  }

  emit({ ...envelope, severity: envelope.severity ?? "error" }, ctx ?? null);
}

// ─── Internal: emit ───────────────────────────────────────────────────────

function emit(envelope: Envelope, ctx: TraceContext | null): void {
  const severity: Severity = envelope.severity ?? "info";

  // Sampling: error/fatal/warn always pass; debug sampled; info always.
  if (severity === "debug" && Math.random() > DEBUG_SAMPLE_RATE) return;

  const event = {
    trace_id: ctx?.traceId ?? randHex(16),
    span_id: ctx?.spanId ?? randHex(8),
    service: serviceName,
    env: deployEnv,
    event: envelope.event,
    severity,
    attrs: redactObject(envelope.attrs ?? {}),
    ts: Date.now(),
  };

  // Console mirror — visible in `wrangler tail`, useful when Sentry is down.
  const line = JSON.stringify(event);
  if (severity === "error" || severity === "fatal") console.error(line);
  else if (severity === "warn") console.warn(line);
  else console.log(line);

  // Breadcrumb so the next captureException carries this context.
  if (initialized && severity !== "debug") {
    safeFireAndForget(() => {
      Sentry.addBreadcrumb({
        category: event.event,
        level: sentryLevel(severity),
        data: event.attrs as { [k: string]: unknown },
      });
    });
  }
}

function sentryLevel(s: Severity): Sentry.SeverityLevel {
  return s === "warn" ? "warning" : (s as Sentry.SeverityLevel);
}

function safeFireAndForget(fn: () => void): void {
  try {
    const p = Promise.resolve().then(fn).catch(() => {
      /* observability MUST NOT throw */
    });
    if (waitUntilFn) waitUntilFn(p);
  } catch {
    /* swallow */
  }
}

// ─── Redaction ────────────────────────────────────────────────────────────

function redactValue(key: string, value: unknown): unknown {
  const k = key.toLowerCase();
  if (REDACTED_KEYS.some((r) => k.includes(r))) return "[redacted]";
  return value;
}

function redactObject(obj: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = redactValue(k, v);
  return out;
}

// ─── Project-specific extensions ──────────────────────────────────────────
// Add project-specific helpers below this line. The generator never edits
// below this comment when re-running init.
