/**
 * Contract roundtrip test for the observability wrapper.
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests verify the spec §10 contract WITHOUT requiring Sentry init —
 * the wrapper must work standalone (stdout-only) when SENTRY_DSN is unset.
 *
 * Test runner: vitest. If the project uses jest or another runner, the
 * generator substitutes the imports; the assertions are framework-agnostic.
 */

import { describe, it, expect, vi } from "vitest";
import {
  parseTraceparent,
  newRootContext,
  formatTraceparent,
  startSpan,
  logEvent,
  captureError,
  runWithContext,
  getActiveContext,
  type Severity,
} from "./index";

// ─── §10.3 traceparent roundtrip ────────────────────────────────────────────

describe("§10.3 traceparent", () => {
  it("roundtrips: format → parse → identical trace_id and parent_id", () => {
    const root = newRootContext();
    const header = formatTraceparent(root);
    const parsed = parseTraceparent(header);
    expect(parsed).not.toBeNull();
    expect(parsed!.traceId).toBe(root.traceId);
    expect(parsed!.parentSpanId).toBe(root.spanId);
  });

  it("rejects malformed inputs", () => {
    for (const header of [
      "",
      "not-a-traceparent",
      "00-tooshort-tooshort-01",
      "00-XYZ-not-hex-01",
    ]) {
      expect(parseTraceparent(header), `expected reject for ${header}`).toBeNull();
    }
  });

  it("accepts the canonical W3C example", () => {
    const header = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";
    const tc = parseTraceparent(header);
    expect(tc).not.toBeNull();
    expect(tc!.traceId).toBe("4bf92f3577b34da6a3ce929d0e0e4736");
    expect(tc!.parentSpanId).toBe("00f067aa0ba902b7");
    expect(tc!.spanId).toHaveLength(16);
    expect(tc!.spanId).not.toBe(tc!.parentSpanId);
  });
});

// ─── §10.5 fail-safe ────────────────────────────────────────────────────────

describe("§10.5 fail-safe", () => {
  it("logEvent does not throw without init", () => {
    expect(() => logEvent({ event: "test", severity: "info" })).not.toThrow();
  });

  it("captureError does not throw with a real Error", () => {
    expect(() =>
      captureError(new Error("boom"), { event: "test_capture", severity: "error" }),
    ).not.toThrow();
  });

  it("captureError does not throw with a non-Error value", () => {
    expect(() => captureError("string error", { event: "test" })).not.toThrow();
    expect(() => captureError({ weird: "object" }, { event: "test" })).not.toThrow();
    expect(() => captureError(undefined, { event: "test" })).not.toThrow();
  });
});

// ─── §10.1 span lifecycle ───────────────────────────────────────────────────

describe("§10.1 startSpan", () => {
  it("returns a span with traceId and spanId", () => {
    const span = startSpan("test", { k: "v" });
    expect(span.traceId).toMatch(/^[0-9a-f]{32}$/);
    expect(span.spanId).toMatch(/^[0-9a-f]{16}$/);
    span.end();
  });

  it("end() is idempotent", () => {
    const span = startSpan("test");
    span.end();
    expect(() => span.end()).not.toThrow();
  });

  it("setStatus + end emits without throwing", () => {
    const span = startSpan("test");
    span.setStatus("error");
    expect(() => span.end()).not.toThrow();
  });

  it("setAttribute on a span doesn't throw", () => {
    const span = startSpan("test");
    expect(() => span.setAttribute("k", "v")).not.toThrow();
    expect(() => span.setAttribute("password", "leaked")).not.toThrow(); // redacted internally
    span.end();
  });
});

// ─── §10.3 runWithContext / getActiveContext ────────────────────────────────

describe("§10.3 active-context propagation", () => {
  it("getActiveContext returns null outside runWithContext", () => {
    expect(getActiveContext()).toBeNull();
  });

  it("getActiveContext returns the bound context inside runWithContext", () => {
    const root = newRootContext();
    runWithContext(root, "test", () => {
      const active = getActiveContext();
      expect(active).not.toBeNull();
      expect(active!.traceId).toBe(root.traceId);
      expect(active!.spanId).toBe(root.spanId);
    });
  });

  it("nested runWithContext scopes correctly", () => {
    const outer = newRootContext();
    const inner = newRootContext();
    runWithContext(outer, "outer", () => {
      expect(getActiveContext()!.traceId).toBe(outer.traceId);
      runWithContext(inner, "inner", () => {
        expect(getActiveContext()!.traceId).toBe(inner.traceId);
      });
      // outer scope restored after inner exits
      expect(getActiveContext()!.traceId).toBe(outer.traceId);
    });
  });
});

// ─── §10.5 console mirror smoke test ────────────────────────────────────────

describe("§10.5 stdout mirror", () => {
  it("error severity writes to console.error", () => {
    const spy = vi.spyOn(console, "error").mockImplementation(() => {});
    logEvent({ event: "test_error", severity: "error" });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });

  it("info severity writes to console.log", () => {
    const spy = vi.spyOn(console, "log").mockImplementation(() => {});
    logEvent({ event: "test_info", severity: "info" });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });
});
