/**
 * Observability wrapper — AgenticApps spec §10 v0.2.0
 *
 * Service:     {{SERVICE_NAME}}
 * Destination: {{DESTINATION}}
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong below the "Project-specific extensions" section.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)     non-blocking emission of a structured event
 *  - captureError(err, env) record an error with envelope context
 *  - startSpan(name, attrs) open a span representing a unit of work
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import { buildRegistry, resolveConfig, type Registry } from "./destinations/registry";
import { SENTRY_RESERVED_ATTRS } from "./destinations/sentry";

// ─── Types ─────────────────────────────────────────────────────────────────

export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";

export interface Envelope {
  event: string;
  severity?: Severity;
  attrs?: Record<string, unknown>;
}

export interface Span {
  setAttribute(key: string, value: unknown): void;
  setStatus(status: SpanStatus): void;
  end(opts?: { status?: SpanStatus }): void;
  readonly traceId: string;
  readonly spanId: string;
}

export interface TraceContext {
  traceId: string;       // 32 hex chars (W3C trace-id)
  spanId: string;        // 16 hex chars (W3C span-id of current span)
  parentSpanId?: string; // 16 hex chars (W3C parent-id)
  flags: number;         // W3C trace flags byte
}

interface InternalSpanContext extends TraceContext {
  startedAt: number;
  name: string;
  attributes: Record<string, unknown>;
  status: SpanStatus | "unset";
}

// ─── Static config (parameterized at generation time) ─────────────────────

const SERVICE_DEFAULT = "{{SERVICE_NAME}}";
const DEBUG_SAMPLE_RATE = {{DEBUG_SAMPLE_RATE}};
const TRACE_SAMPLE_RATE = {{TRACE_SAMPLE_RATE}};

// REDACTED_KEYS is inlined from policy.md by the generator. Keys whose
// names contain any of these substrings (case-insensitive) are scrubbed
// before emission.
const REDACTED_KEYS: ReadonlyArray<string> = [
  {{REDACTED_KEYS}}
];

// ─── Module state ─────────────────────────────────────────────────────────

const spanStorage = new AsyncLocalStorage<InternalSpanContext>();

let serviceName: string = SERVICE_DEFAULT;
let deployEnv: string = "dev";

// Role-based destination registry, built once per invocation in `init`.
// logEvent dispatches to the LOGS adapter; captureError to the ERRORS adapter.
// Null until init runs (or when no destinations resolve). All SDK-specific
// behaviour (Sentry capture/breadcrumb, Axiom POST) now lives behind the
// adapters; this wrapper only owns the console mirror + sampling + dispatch.
let registry: Registry | null = null;

// ─── Initialization ───────────────────────────────────────────────────────

export interface InitEnv {
  {{ENV_VAR_DSN}}?: string;
  {{ENV_VAR_ENV}}?: string;
  {{ENV_VAR_SERVICE}}?: string;
}

/**
 * Initialize the wrapper. Called once per Worker invocation by the
 * `withObservability` middleware (see middleware.ts). Idempotent.
 *
 * Sentry SDK initialisation is handled by `withSentry(optionsFactory, handler)`
 * at the entry-file site (see INIT.md Phase 5 detail). `@sentry/cloudflare`
 * v8 removed `Sentry.init`; the per-request `withSentry` wrap is the
 * canonical setup point. This function only sets local module state
 * (service name, deploy env, waitUntil binding) and records whether a
 * DSN was present so downstream `Sentry.withScope` / `captureException`
 * / `addBreadcrumb` calls in this module can be gated on the same flag.
 */
export function init(env: InitEnv, ctx: ExecutionContext): void {
  serviceName = env.{{ENV_VAR_SERVICE}} ?? SERVICE_DEFAULT;
  deployEnv = env.{{ENV_VAR_ENV}} ?? "dev";

  // Build the role-based destination registry once per invocation. Each
  // configured named adapter is init()-ed (and captures its own waitUntil
  // binding from `ctx` for fire-and-forget egress); logEvent/captureError
  // dispatch by role. resolveConfig is fail-closed (errors can never resolve
  // to Axiom). `withSentry` at the entry-file site populates the Sentry hub
  // when a DSN is configured; the sentry adapter gates its own calls on the
  // same DSN-present signal via isConfigured/init.
  registry = buildRegistry(resolveConfig(env), env, ctx);
}

// ─── Sentry options helper (D-01 Phase 26) ────────────────────────────────

export interface SentryOptions {
  dsn: string | undefined;
  environment: string;
  release: string;
  tracesSampleRate: number;
  sendDefaultPii: false;
}

/**
 * Build the options object for `withSentry(optionsFactory, handler)`.
 *
 * ENV-PURE: reads ONLY from `env` plus the scaffold-time `TRACE_SAMPLE_RATE`
 * constant. Reads ZERO module-scope singletons. This matters because the
 * `withSentry` wrapper invokes its options factory per-request BEFORE the
 * inner handler runs — and the inner handler is what calls `init(env, ctx)`
 * (which sets the `serviceName` / `deployEnv` singletons). If this helper
 * read from singletons, it would see default/stale values. Reading from
 * `env` directly mirrors the env-derived pattern openrouter-monitor's own
 * entry file uses manually (see openrouter-monitor/src/index.ts:47-57).
 *
 * Call at the entry-file site:
 *   export default withSentry(env => buildSentryOptions(env), withObservability(handler));
 *
 * TRACE_SAMPLE_RATE (baked at scaffold time from meta.yaml) is the
 * authoritative traces sample rate; this helper surfaces it to the
 * Sentry SDK that `withSentry` initialises per-request. Phase 26 DEF-1.
 *
 * Runtime model: Cloudflare reuses Worker isolates across requests for
 * performance; module state persists across requests within an isolate.
 * The contract that makes this helper safe is its env-purity, NOT any
 * assumption about init() running first. See
 * docs/decisions/0034-observability-init-singleton-invariant.md.
 */
export function buildSentryOptions(env: InitEnv): SentryOptions {
  return {
    dsn: env.{{ENV_VAR_DSN}},
    environment: env.{{ENV_VAR_ENV}} ?? "dev",
    release: env.{{ENV_VAR_SERVICE}} ?? SERVICE_DEFAULT,
    tracesSampleRate: TRACE_SAMPLE_RATE,
    sendDefaultPii: false,
  };
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

const TRACEPARENT_RE = /^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/i;

function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Parse an inbound traceparent header. Returns a TraceContext with a
 * fresh local span_id (the local hop's span); parentSpanId is the
 * span_id from the inbound header.
 */
export function parseTraceparent(header: string | null | undefined): TraceContext | null {
  if (!header) return null;
  const m = TRACEPARENT_RE.exec(header.trim());
  if (!m) return null;
  const version = m[1].toLowerCase();
  const traceId = m[2].toLowerCase();
  const parentId = m[3].toLowerCase();
  // #49 gap 4: the regex gates shape; these gate W3C semantics — reject the
  // reserved "ff" version and the all-zero trace-id / parent-id that downstream
  // collectors (Sentry/Tempo/Honeycomb) discard or mis-attribute. Higher
  // versions (01–fe) stay forward-compatible: parse the known v0 fields rather
  // than drop the inbound trace.
  if (version === "ff") return null;
  if (/^0+$/.test(traceId) || /^0+$/.test(parentId)) return null;
  return {
    traceId,
    spanId: randHex(8),
    parentSpanId: parentId,
    flags: parseInt(m[4], 16),
  };
}

/** Generate a fresh root TraceContext (no inbound traceparent). */
export function newRootContext(): TraceContext {
  return {
    traceId: randHex(16),
    spanId: randHex(8),
    flags: 1,
  };
}

/** Format a TraceContext for outbound traceparent header. */
export function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string {
  return `00-${c.traceId}-${c.spanId}-${c.flags.toString(16).padStart(2, "0")}`;
}

// ─── Run-with-context (used by middleware) ────────────────────────────────

/**
 * Run `fn` with the given trace context as the active span. Used by the
 * middleware to bind a request to its trace; not normally called from
 * application code.
 */
export function runWithContext<T>(ctx: TraceContext, name: string, fn: () => T): T {
  const internal: InternalSpanContext = {
    ...ctx,
    startedAt: Date.now(),
    name,
    attributes: {},
    status: "unset",
  };
  return spanStorage.run(internal, fn);
}

/** Read the active TraceContext, if any. */
export function getActiveContext(): TraceContext | null {
  const c = spanStorage.getStore();
  return c ? { traceId: c.traceId, spanId: c.spanId, parentSpanId: c.parentSpanId, flags: c.flags } : null;
}

// ─── startSpan ────────────────────────────────────────────────────────────

/**
 * Open a span representing a unit of work. The returned Span MUST be
 * .end()-ed; ending the span emits a span event.
 *
 * Note: nested startSpan calls produce sibling spans under the active
 * trace. Their parent_span_id is the active span's span_id at the time
 * startSpan was called. Cloudflare Workers' AsyncLocalStorage cannot
 * mutate the active context without a callback, so for full nested-span
 * tracing prefer Sentry.startSpan(...) callback style. Spec §10.1
 * accepts either shape.
 */
export function startSpan(name: string, attributes: Record<string, unknown> = {}): Span {
  const parent = spanStorage.getStore();
  const ctx: TraceContext = parent
    ? { traceId: parent.traceId, spanId: randHex(8), parentSpanId: parent.spanId, flags: parent.flags }
    : newRootContext();

  const startedAt = Date.now();
  const attrs: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(attributes)) attrs[k] = redactValue(k, v);

  let status: SpanStatus | "unset" = "unset";
  let ended = false;

  const span: Span = {
    setAttribute(key, value) {
      attrs[key] = redactValue(key, value);
    },
    setStatus(s) {
      status = s;
    },
    end(opts) {
      if (ended) return;
      ended = true;
      if (opts?.status) status = opts.status;
      const finalStatus: SpanStatus = status === "unset" ? "ok" : status;
      const enriched = emit(
        {
          event: name,
          severity: finalStatus === "error" ? "error" : "info",
          attrs: { ...attrs, duration_ms: Date.now() - startedAt, span_status: finalStatus },
        },
        ctx,
      );
      // Spans stay Sentry-native: a span-end breadcrumb on the ERRORS
      // destination, NEVER routed to the Axiom logs sink (D-span). No-op
      // when errors is unconfigured / non-Sentry.
      if (enriched) registry?.forRole("errors")?.emit(enriched);
    },
    get traceId() { return ctx.traceId; },
    get spanId() { return ctx.spanId; },
  };
  return span;
}

// ─── logEvent ─────────────────────────────────────────────────────────────

export function logEvent(envelope: Envelope): void {
  const ctx = spanStorage.getStore();
  // Console mirror + sampling. Returns the enriched+redacted envelope ready
  // for adapter dispatch, or null when the event was sampled out.
  const enriched = emit(envelope, ctx ?? null);
  if (!enriched) return;
  // Dispatch to the LOGS destination (e.g. Axiom POST). No-op when logs is
  // unconfigured ("none"). Attrs are already redacted (D6) — adapters never
  // see raw attrs.
  registry?.forRole("logs")?.emit(enriched);
  // Breadcrumb on the ERRORS destination (Sentry) so the next captureException
  // carries this context. No-op when errors is unconfigured / non-Sentry.
  registry?.forRole("errors")?.emit(enriched);
}

// ─── captureError ─────────────────────────────────────────────────────────

export function captureError(err: unknown, envelope: Envelope): void {
  const ctx = spanStorage.getStore();
  if (ctx) ctx.status = "error";

  // #49 gap 2: captureError must be visible regardless of caller severity.
  // Coerce to "error" (preserving an explicit "fatal") so emit's sample-rate
  // gate can never silently drop the exception.
  const severity: Severity = envelope.severity === "fatal" ? "fatal" : "error";
  const enriched = emit({ ...envelope, severity }, ctx ?? null);

  // Dispatch to the ERRORS destination (Sentry scoped captureException). No-op
  // when errors is unconfigured. By the fail-closed registry contract this can
  // NEVER reach the logs-only Axiom adapter (its captureException is a no-op
  // anyway). The enriched envelope carries service/env/trace under reserved
  // attrs so the adapter can rebuild Sentry scope tags without this module's
  // AsyncLocalStorage.
  if (enriched) registry?.forRole("errors")?.captureException(err, enriched);
}

// ─── Internal: emit ───────────────────────────────────────────────────────
//
// Owns the console mirror + sampling, and builds the enriched+redacted
// envelope handed to destination adapters. Returns null when the event was
// sampled out (so callers skip dispatch). All SDK-specific egress (Sentry
// breadcrumb/capture, Axiom POST) lives in the adapters.

function emit(envelope: Envelope, ctx: TraceContext | null): Envelope | null {
  const severity: Severity = envelope.severity ?? "info";

  // Sampling: error/fatal/warn always pass; debug sampled; info always.
  if (severity === "debug" && Math.random() > DEBUG_SAMPLE_RATE) return null;

  const traceId = ctx?.traceId ?? randHex(16);
  const spanId = ctx?.spanId ?? randHex(8);
  const redactedAttrs = redactObject(envelope.attrs ?? {});

  const event = {
    trace_id: traceId,
    span_id: spanId,
    service: serviceName,
    env: deployEnv,
    event: envelope.event,
    severity,
    attrs: redactedAttrs,
    ts: Date.now(),
  };

  // Console mirror — visible in `wrangler tail`, useful when a sink is down.
  const line = JSON.stringify(event);
  if (severity === "error" || severity === "fatal") console.error(line);
  else if (severity === "warn") console.warn(line);
  else console.log(line);

  // Enriched envelope for adapter dispatch: redacted user attrs plus reserved
  // correlation keys (service/env/trace) the Sentry adapter reads for scope
  // tags. The reserved keys also give Axiom log/trace correlation for free.
  return {
    event: envelope.event,
    severity,
    attrs: {
      ...redactedAttrs,
      [SENTRY_RESERVED_ATTRS.service]: serviceName,
      [SENTRY_RESERVED_ATTRS.env]: deployEnv,
      [SENTRY_RESERVED_ATTRS.traceId]: traceId,
      [SENTRY_RESERVED_ATTRS.spanId]: spanId,
    },
  };
}

// ─── Redaction ────────────────────────────────────────────────────────────

function redactValue(key: string, value: unknown, seen: WeakSet<object> = new WeakSet()): unknown {
  const k = key.toLowerCase();
  if (REDACTED_KEYS.some((r) => k.includes(r))) return "[redacted]";
  return redactDeep(value, seen);
}

// #49 gap 1: recurse into plain objects and arrays so secrets nested below the
// top level (attrs.request.headers.secret, arrays of objects) are scrubbed too.
// null and non-plain objects (Date, class instances) pass through unchanged; new
// containers are constructed, so the caller's input is never mutated. `seen` is
// an ancestor stack (add before recursing, delete after) so a true cycle
// short-circuits to "[circular]" instead of overflowing the stack, while shared
// (DAG) references are still fully redacted.
function redactDeep(value: unknown, seen: WeakSet<object>): unknown {
  if (value === null || typeof value !== "object") return value;
  if (seen.has(value)) return "[circular]";
  seen.add(value);
  try {
    if (Array.isArray(value)) return value.map((v) => redactDeep(v, seen));
    if (isPlainObject(value)) return redactObject(value, seen);
    return value;
  } finally {
    seen.delete(value);
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function redactObject(obj: Record<string, unknown>, seen: WeakSet<object> = new WeakSet()): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = redactValue(k, v, seen);
  return out;
}

// ─── Project-specific extensions ──────────────────────────────────────────
// Add project-specific helpers below this line. The generator never edits
// below this comment when re-running init.
