/**
 * llm-response-meta.test.ts — recordLLMResponseMeta contract suite (ts-cloudflare-worker).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the post-processing helper for OpenAI-SDK-against-OpenRouter calls.
 * Phase 24 / ADR-0030 — SDK-first integration: helper captures the two
 * signals AI Monitoring doesn't surface (rate-limit headroom + cache_ratio).
 *
 * Helper takes logEvent by dependency injection (§10.6 destination-independence),
 * so the test just constructs a capturing logEvent fn and inspects the emitted
 * envelope shape — no module mock needed.
 *
 * Run via `add-observability/templates/run-template-tests.sh ts-cloudflare-worker`
 * (vitest harness; materialises lib-observability.ts → index.ts so the helper's
 * `./index` import resolves).
 */

import { describe, it, expect } from "vitest";
import { recordLLMResponseMeta } from "./llm-response-meta";
import type { Envelope } from "./index";

// Helper: capture every emitted envelope into an array.
function makeCapture(): {
  envelopes: Envelope[];
  logEvent: (e: Envelope) => void;
} {
  const envelopes: Envelope[] = [];
  return { envelopes, logEvent: (e) => envelopes.push(e) };
}

describe("recordLLMResponseMeta", () => {
  it("(1) cache hit produces correct cache_ratio", () => {
    const { envelopes, logEvent } = makeCapture();
    const response = new Response("", {
      headers: { "x-ratelimit-remaining": "42", "x-ratelimit-reset": "1700000000" },
    });
    recordLLMResponseMeta(
      logEvent,
      response,
      {
        prompt_tokens: 1000,
        completion_tokens: 200,
        prompt_tokens_details: { cached_tokens: 800 },
      },
      { model: "anthropic/claude-3.5-sonnet" },
    );
    expect(envelopes).toHaveLength(1);
    expect(envelopes[0].event).toBe("llm.call_meta");
    expect(envelopes[0].severity).toBe("info");
    expect(envelopes[0].attrs).toMatchObject({
      model: "anthropic/claude-3.5-sonnet",
      service: "openrouter",
      rate_remaining: "42",
      rate_reset: "1700000000",
      cached_tokens: 800,
      prompt_tokens: 1000,
      completion_tokens: 200,
      cache_ratio: 0.8,
    });
  });

  it("(2) cache miss produces cache_ratio = 0", () => {
    const { envelopes, logEvent } = makeCapture();
    recordLLMResponseMeta(
      logEvent,
      new Response(""),
      {
        prompt_tokens: 1000,
        completion_tokens: 200,
        prompt_tokens_details: { cached_tokens: 0 },
      },
      { model: "openai/gpt-4" },
    );
    expect(envelopes[0].attrs?.cache_ratio).toBe(0);
    expect(envelopes[0].attrs?.cached_tokens).toBe(0);
  });

  it("(3) divide-by-zero safety — prompt_tokens=0 produces cache_ratio=0, no NaN", () => {
    const { envelopes, logEvent } = makeCapture();
    recordLLMResponseMeta(
      logEvent,
      new Response(""),
      { prompt_tokens: 0, completion_tokens: 0 },
      { model: "openai/gpt-4" },
    );
    expect(envelopes[0].attrs?.cache_ratio).toBe(0);
    expect(Number.isNaN(envelopes[0].attrs?.cache_ratio as number)).toBe(false);
  });

  it("(4) missing usage fields default to 0", () => {
    const { envelopes, logEvent } = makeCapture();
    recordLLMResponseMeta(logEvent, new Response(""), {}, { model: "openai/gpt-4" });
    expect(envelopes[0].attrs).toMatchObject({
      cached_tokens: 0,
      prompt_tokens: 0,
      completion_tokens: 0,
      cache_ratio: 0,
    });
  });

  it("(5) missing rate-limit headers pass through as null", () => {
    const { envelopes, logEvent } = makeCapture();
    recordLLMResponseMeta(
      logEvent,
      new Response(""), // no headers
      { prompt_tokens: 100 },
      { model: "openai/gpt-4" },
    );
    expect(envelopes[0].attrs?.rate_remaining).toBeNull();
    expect(envelopes[0].attrs?.rate_reset).toBeNull();
  });

  it('(6) service defaults to "openrouter" when ctx.service is omitted', () => {
    const { envelopes, logEvent } = makeCapture();
    recordLLMResponseMeta(
      logEvent,
      new Response(""),
      { prompt_tokens: 100 },
      { model: "openai/gpt-4" },
    );
    expect(envelopes[0].attrs?.service).toBe("openrouter");
  });

  it("(7) service override is respected", () => {
    const { envelopes, logEvent } = makeCapture();
    recordLLMResponseMeta(
      logEvent,
      new Response(""),
      { prompt_tokens: 100 },
      { model: "llama-3.1-70b", service: "groq" },
    );
    expect(envelopes[0].attrs?.service).toBe("groq");
  });
});
