/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-supabase-edge).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
 *   D1  — separate-wrapper export
 *   D5b — Composes as `withObservability(withCronMonitor(handler))` for the
 *         Supabase Edge stack (no `withSentry`, no `withObservabilityScheduled`;
 *         Sentry init is inline in the wrapper's existing `init()`).
 *   D6  — 3-source slug resolution (explicit > env > auto-derive)
 *         Supabase-edge auto-shape: `${SERVICE_NAME}:${handlerName ?? "scheduled"}`.
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (2nd
 *         arg) on the in_progress checkin only
 *   R04 (PLAN revisions) — SENTRY_DEBUG=1 opt-in console.error in catch blocks
 *
 * The wrapper exposes a test seam `_setCaptureCheckInForTest` (mirroring the
 * existing `_resetForTest` convention in this stack's index.ts) so the Sentry
 * SDK boundary call can be substituted without monkey-patching `npm:` modules.
 * Env access is stubbed by replacing `globalThis.Deno.env` for the test, then
 * restored.
 *
 * Run with: deno test -A --no-check cron-monitor.test.ts
 */

import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { withCronMonitor, _setCaptureCheckInForTest } from "./cron-monitor.ts";

// ─── Call-recorder for the Sentry SDK boundary ────────────────────────────────

interface CheckInCall {
  arg0: Record<string, unknown>;
  arg1: unknown;
}

interface Recorder {
  calls: CheckInCall[];
  returns: unknown[];
  impl: ((...args: unknown[]) => unknown) | null;
}

function makeRecorder(): Recorder {
  return { calls: [], returns: [], impl: null };
}

function bindRecorder(r: Recorder): void {
  _setCaptureCheckInForTest((arg0: Record<string, unknown>, arg1?: unknown) => {
    r.calls.push({ arg0, arg1 });
    if (r.impl) return r.impl(arg0, arg1);
    if (r.returns.length > 0) return r.returns.shift();
    return undefined;
  });
}

function resetRecorder(): void {
  _setCaptureCheckInForTest(null);
}

// ─── Deno.env stubbing ────────────────────────────────────────────────────────

let stubEnv: Record<string, string> = {};
let originalDeno: unknown;

function installEnvStub(env: Record<string, string>): void {
  stubEnv = env;
  // deno-lint-ignore no-explicit-any
  originalDeno = (globalThis as any).Deno;
  // deno-lint-ignore no-explicit-any
  (globalThis as any).Deno = {
    env: {
      get: (k: string): string | undefined => stubEnv[k],
    },
  };
}

function restoreEnv(): void {
  // deno-lint-ignore no-explicit-any
  (globalThis as any).Deno = originalDeno;
}

// ─── §22.D1/D5b cron checkin behavior ─────────────────────────────────────────

Deno.test("withCronMonitor: emits in_progress + ok on happy path", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnvStub({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => {
      called += 1;
      return new Response("ok");
    };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });
    const res = await wrapped(new Request("https://stub/cron"));

    assertEquals(res.status, 200);
    assertEquals(called, 1);
    assertEquals(rec.calls.length, 2);
    assertEquals(rec.calls[0].arg0, { monitorSlug: "callbot-sweep", status: "in_progress" });
    assertEquals(rec.calls[1].arg0, { checkInId: "checkin-abc", monitorSlug: "callbot-sweep", status: "ok" });
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: emits in_progress + error and re-throws on handler exception", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnvStub({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const boom = new Error("handler exploded");
    const handler = async (_req: Request): Promise<Response> => { throw boom; };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });

    let caught: unknown;
    try {
      await wrapped(new Request("https://stub/cron"));
    } catch (e) {
      caught = e;
    }
    assertEquals(caught, boom);
    assertEquals(rec.calls.length, 2);
    assertEquals(rec.calls[0].arg0, { monitorSlug: "callbot-sweep", status: "in_progress" });
    assertEquals(rec.calls[1].arg0, { checkInId: "checkin-abc", monitorSlug: "callbot-sweep", status: "error" });
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: no-ops cleanly when SENTRY_DSN is unset", async () => {
  const rec = makeRecorder();
  bindRecorder(rec);
  installEnvStub({}); // no SENTRY_DSN
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => {
      called += 1;
      return new Response("ok");
    };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });
    const res = await wrapped(new Request("https://stub/cron"));

    assertEquals(res.status, 200);
    assertEquals(called, 1);
    assertEquals(rec.calls.length, 0);
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

// ─── §22.D6 slug resolution ──────────────────────────────────────────────────

Deno.test("withCronMonitor: uses explicit config.monitorSlug above all sources", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnvStub({
    SENTRY_DSN: "https://stub@sentry.io/1",
    SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses",
    SERVICE_NAME: "auto-loses",
  });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg0.monitorSlug, "explicit-wins");
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  // handlerName "ingest-15min" → env key SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN
  // (hyphens become underscores per D6).
  installEnvStub({
    SENTRY_DSN: "https://stub@sentry.io/1",
    SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN: "env-wins",
    SERVICE_NAME: "auto-loses",
  });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { handlerName: "ingest-15min" });
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg0.monitorSlug, "env-wins");
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: falls back to auto-derived ${SERVICE_NAME}:${handlerName} (default 'scheduled') when neither set", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnvStub({
    SENTRY_DSN: "https://stub@sentry.io/1",
    SERVICE_NAME: "callbot-edge",
  });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler);
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg0.monitorSlug, "callbot-edge:scheduled");
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

// ─── §22.D12 / R03 monitorConfig forwarding ──────────────────────────────────

Deno.test("withCronMonitor: forwards monitorConfig on in_progress, omits on completion", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnvStub({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped(new Request("https://stub/cron"));

    assertEquals(rec.calls.length, 2);
    // 1st call (in_progress) — 2nd arg is monitorConfig with schedule + maxRuntime
    assertEquals(rec.calls[0].arg1, {
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntime: 240,
    });
    // 2nd call (ok) — 2nd arg is undefined (Sentry already has monitor config)
    assertEquals(rec.calls[1].arg1, undefined);
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: omits monitorConfig entirely when neither schedule nor maxRuntimeSeconds is configured", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnvStub({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg1, undefined);
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

// ─── R04 SENTRY_DEBUG opt-in logging ─────────────────────────────────────────

Deno.test("withCronMonitor: logs swallowed errors when SENTRY_DEBUG=1, silent otherwise", async () => {
  // Make captureCheckIn throw on every call so the swallow-catch fires.
  const rec = makeRecorder();
  rec.impl = () => { throw new Error("sentry SDK boom"); };
  bindRecorder(rec);

  const origError = console.error;
  let errorCalls: unknown[][] = [];
  console.error = (...args: unknown[]) => { errorCalls.push(args); };

  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");

    // SENTRY_DEBUG absent → silent
    installEnvStub({ SENTRY_DSN: "https://stub@sentry.io/1" });
    const wrappedSilent = withCronMonitor(handler, { monitorSlug: "x" });
    await wrappedSilent(new Request("https://stub/cron"));
    assertEquals(errorCalls.length, 0);
    restoreEnv();

    // SENTRY_DEBUG=1 → console.error called
    errorCalls = [];
    installEnvStub({ SENTRY_DSN: "https://stub@sentry.io/1", SENTRY_DEBUG: "1" });
    const wrappedDebug = withCronMonitor(handler, { monitorSlug: "x" });
    await wrappedDebug(new Request("https://stub/cron"));
    assert(errorCalls.length > 0, "expected console.error to be called when SENTRY_DEBUG=1");
    // At least one error-call's arg list contains an Error instance.
    const sawError = errorCalls.some((args) => args.some((a) => a instanceof Error));
    assert(sawError, "expected an Error instance among console.error arguments");
  } finally {
    console.error = origError;
    resetRecorder();
    restoreEnv();
  }
});
