/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-supabase-edge).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract:
 *   D1  — separate-wrapper export
 *   D5b — Composes as `withObservability(withCronMonitor(handler))` for the
 *         Supabase Edge stack (no `withSentry`, no `withObservabilityScheduled`).
 *   D6  — 3-source slug resolution (explicit > env > auto-derive)
 *         Supabase-edge auto-shape: `${SERVICE_NAME}:${handlerName ?? "scheduled"}`.
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (3rd
 *         arg to Sentry.withMonitor)
 *
 * Phase 23 / ADR-0029 — Guarded Shape A refactor:
 *   D-08 — withCronMonitor now composes Sentry.withMonitor (via _setWithMonitorForTest
 *           seam) instead of hand-rolling captureCheckIn lifecycle.
 *   codex MEDIUM-4 / R-rev-6 — Deno-friendly seam: no module-boundary mocking.
 *
 * Test seam: `_setWithMonitorForTest` injects a fake withMonitor implementation.
 * `Deno.env.set/delete` for per-test env mutation.
 *
 * Run with: deno test -A --no-check cron-monitor.test.ts
 */

import { assert, assertEquals, assertRejects } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { withCronMonitor, _setCaptureCheckInForTest, _setWithMonitorForTest } from "./cron-monitor.ts";

// ─── withMonitor mock helpers ─────────────────────────────────────────────────

interface WithMonitorRecordedCall {
  slug: string;
  // deno-lint-ignore no-explicit-any
  monitorConfig: any;
}

function makeWithMonitorMock(behavior: "passthrough" | "throw-before" | "throw-after") {
  const calls: WithMonitorRecordedCall[] = [];
  // deno-lint-ignore no-explicit-any
  const impl = async (slug: string, cb: () => any, monitorConfig?: unknown): Promise<unknown> => {
    calls.push({ slug, monitorConfig });
    if (behavior === "throw-before") {
      throw new Error("Sentry transport failure (pre-callback)");
    }
    const result = await cb();
    if (behavior === "throw-after") {
      throw new Error("post-callback transport failure");
    }
    return result;
  };
  return { calls, impl };
}

// deno-lint-ignore no-explicit-any
function resetWithMonitor(): void {
  // Restore to a passthrough default so subsequent tests are isolated.
  // deno-lint-ignore no-explicit-any
  _setWithMonitorForTest(async (_slug: string, cb: () => any) => cb());
}

// Keep _setCaptureCheckInForTest import alive (exported from cron-monitor.ts,
// no longer needed for test assertions after Guarded Shape A refactor, but
// the export must remain to avoid breaking the module contract).
const _legacyCaptureCheckInSeam = _setCaptureCheckInForTest;

// ─── Env management ───────────────────────────────────────────────────────────
// Deno.env.set / delete is the only mutation surface — the `Deno` object
// itself is read-only. Tests track the keys they wrote so teardown can scrub
// them cleanly (no other test relies on these vars persisting).

const TEST_ENV_KEYS = [
  "SENTRY_DSN",
  "SENTRY_DEBUG",
  "SERVICE_NAME",
  "SENTRY_CRON_MONITOR_SLUG_SCHEDULED",
  "SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN",
];

function installEnv(env: Record<string, string>): void {
  // Reset all known keys first, then apply.
  for (const k of TEST_ENV_KEYS) {
    try { Deno.env.delete(k); } catch { /* ignore */ }
  }
  for (const [k, v] of Object.entries(env)) {
    Deno.env.set(k, v);
  }
}

function restoreEnv(): void {
  for (const k of TEST_ENV_KEYS) {
    try { Deno.env.delete(k); } catch { /* ignore */ }
  }
}

// ─── §22.D1/D5b / Phase 23 ADR-0029 — cron monitor behavior ──────────────────

Deno.test("withCronMonitor: calls withMonitor with slug + handler + monitorConfig on happy path", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "callbot-sweep",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    const res = await wrapped(new Request("https://stub/cron"));

    assertEquals(res.status, 200);
    assertEquals(called, 1);
    assertEquals(mock.calls.length, 1);
    assertEquals(mock.calls[0].slug, "callbot-sweep");
    assertEquals(mock.calls[0].monitorConfig, {
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntime: 240,
    });
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: handler exception re-throws (post-callback error propagates)", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const boom = new Error("handler exploded");
    const handler = async (_req: Request): Promise<Response> => { throw boom; };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });

    let caught: unknown;
    try { await wrapped(new Request("https://stub/cron")); } catch (e) { caught = e; }
    assertEquals(caught, boom);
    assertEquals(mock.calls.length, 1);
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: no-ops cleanly when SENTRY_DSN is unset (R02 fail-safe)", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({}); // no SENTRY_DSN
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });
    const res = await wrapped(new Request("https://stub/cron"));
    assertEquals(res.status, 200);
    assertEquals(called, 1);
    assertEquals(mock.calls.length, 0);
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

// ─── §22.D6 slug resolution ──────────────────────────────────────────────────

Deno.test("withCronMonitor: uses explicit config.monitorSlug above all sources", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1", SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses", SERVICE_NAME: "auto-loses" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });
    await wrapped(new Request("https://stub/cron"));
    assert(mock.calls.length >= 1);
    assertEquals(mock.calls[0].slug, "explicit-wins");
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1", SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN: "env-wins", SERVICE_NAME: "auto-loses" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { handlerName: "ingest-15min" });
    await wrapped(new Request("https://stub/cron"));
    assert(mock.calls.length >= 1);
    assertEquals(mock.calls[0].slug, "env-wins");
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: falls back to auto-derived ${SERVICE_NAME}:${handlerName} (default 'scheduled') when neither set", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1", SERVICE_NAME: "callbot-edge" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler);
    await wrapped(new Request("https://stub/cron"));
    assert(mock.calls.length >= 1);
    assertEquals(mock.calls[0].slug, "callbot-edge:scheduled");
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

// ─── §22.D12 / ADR-0029 monitorConfig forwarding ─────────────────────────────

Deno.test("withCronMonitor: passes monitorConfig as 3rd arg to withMonitor when schedule + maxRuntimeSeconds set", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped(new Request("https://stub/cron"));
    assertEquals(mock.calls.length, 1);
    assertEquals(mock.calls[0].monitorConfig, {
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntime: 240,
    });
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: passes undefined monitorConfig when neither schedule nor maxRuntimeSeconds configured", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(new Request("https://stub/cron"));
    assert(mock.calls.length >= 1);
    assertEquals(mock.calls[0].monitorConfig, undefined);
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

// ─── Phase 23 / ADR-0029 / D-08 — Guarded Shape A guards ────────────────────

Deno.test("F5.6 — D-08 guard: withMonitor throws BEFORE callback → handler still executes unmonitored", async () => {
  const mock = makeWithMonitorMock("throw-before");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    // Must NOT throw — falls back to unmonitored handler.
    const res = await wrapped(new Request("https://stub/cron"));
    assertEquals(called, 1);
    assertEquals(res.status, 200);
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

Deno.test("F5.7 — D-08 guard: withMonitor throws AFTER callback ran → error propagates", async () => {
  const mock = makeWithMonitorMock("throw-after");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await assertRejects(
      () => wrapped(new Request("https://stub/cron")),
      Error,
      "post-callback transport failure",
    );
    assertEquals(called, 1);
  } finally {
    resetWithMonitor();
    restoreEnv();
  }
});

// Suppress unused-import warning: _setCaptureCheckInForTest is exported from
// cron-monitor.ts and must remain importable; verify it is still exported.
Deno.test("_setCaptureCheckInForTest export still present (contract check)", () => {
  assert(typeof _legacyCaptureCheckInSeam === "function", "_setCaptureCheckInForTest must remain exported");
});
