/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-supabase-edge).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
 *   D1  — separate-wrapper export
 *   D5b — Composes as `withObservability(withCronMonitor(handler))` for the
 *         Supabase Edge stack (no `withSentry`, no `withObservabilityScheduled`;
 *         Sentry init is inline in the wrapper's existing `init()`).
 *   D6  — 3-source slug resolution (explicit > env > auto-derive)
 *         Supabase-edge auto-shape: `${SERVICE_NAME}:${handlerName ?? "scheduled"}`.
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (2nd
 *         arg) on the in_progress checkin only
 *   R04 (PLAN revisions) — SENTRY_DEBUG=1 opt-in console.error in catch blocks
 *
 * Two test seams are used:
 *   - `_setCaptureCheckInForTest`: substitutes the Sentry SDK boundary call.
 *     Mirrors the existing `_resetForTest` convention in this stack's
 *     `index.ts` — avoids monkey-patching the `npm:@sentry/deno` module
 *     under `deno test`, which has no `vi.mock` equivalent.
 *   - `Deno.env.set/delete`: per-test env mutation. Deno's global `Deno`
 *     namespace is read-only and cannot be reassigned, but its env API
 *     exposes `set`/`delete` — the idiomatic stub.
 *
 * Run with: deno test -A --no-check cron-monitor.test.ts
 */

import { assert, assertEquals, assertRejects } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { withCronMonitor, _setCaptureCheckInForTest, _setWithMonitorForTest } from "./cron-monitor.ts";

// ─── Call-recorder for the Sentry SDK boundary ────────────────────────────────

interface CheckInCall {
  arg0: Record<string, unknown>;
  arg1: unknown;
}

interface Recorder {
  calls: CheckInCall[];
  returns: unknown[];
  impl: ((...args: unknown[]) => unknown) | null;
}

function makeRecorder(): Recorder {
  return { calls: [], returns: [], impl: null };
}

function bindRecorder(r: Recorder): void {
  _setCaptureCheckInForTest((arg0: Record<string, unknown>, arg1?: unknown) => {
    r.calls.push({ arg0, arg1 });
    if (r.impl) return r.impl(arg0, arg1);
    if (r.returns.length > 0) return r.returns.shift();
    return undefined;
  });
}

function resetRecorder(): void {
  _setCaptureCheckInForTest(null);
}

// ─── Env management ───────────────────────────────────────────────────────────
// Deno.env.set / delete is the only mutation surface — the `Deno` object
// itself is read-only. Tests track the keys they wrote so teardown can scrub
// them cleanly (no other test relies on these vars persisting).

const TEST_ENV_KEYS = [
  "SENTRY_DSN",
  "SENTRY_DEBUG",
  "SERVICE_NAME",
  "SENTRY_CRON_MONITOR_SLUG_SCHEDULED",
  "SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN",
];

function installEnv(env: Record<string, string>): void {
  // Reset all known keys first, then apply.
  for (const k of TEST_ENV_KEYS) {
    try { Deno.env.delete(k); } catch { /* ignore */ }
  }
  for (const [k, v] of Object.entries(env)) {
    Deno.env.set(k, v);
  }
}

function restoreEnv(): void {
  for (const k of TEST_ENV_KEYS) {
    try { Deno.env.delete(k); } catch { /* ignore */ }
  }
}

// ─── §22.D1/D5b cron checkin behavior ─────────────────────────────────────────

Deno.test("withCronMonitor: emits in_progress + ok on happy path", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => {
      called += 1;
      return new Response("ok");
    };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });
    const res = await wrapped(new Request("https://stub/cron"));

    assertEquals(res.status, 200);
    assertEquals(called, 1);
    assertEquals(rec.calls.length, 2);
    assertEquals(rec.calls[0].arg0, { monitorSlug: "callbot-sweep", status: "in_progress" });
    assertEquals(rec.calls[1].arg0, { checkInId: "checkin-abc", monitorSlug: "callbot-sweep", status: "ok" });
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: emits in_progress + error and re-throws on handler exception", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const boom = new Error("handler exploded");
    const handler = async (_req: Request): Promise<Response> => { throw boom; };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });

    let caught: unknown;
    try {
      await wrapped(new Request("https://stub/cron"));
    } catch (e) {
      caught = e;
    }
    assertEquals(caught, boom);
    assertEquals(rec.calls.length, 2);
    assertEquals(rec.calls[0].arg0, { monitorSlug: "callbot-sweep", status: "in_progress" });
    assertEquals(rec.calls[1].arg0, { checkInId: "checkin-abc", monitorSlug: "callbot-sweep", status: "error" });
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: no-ops cleanly when SENTRY_DSN is unset", async () => {
  const rec = makeRecorder();
  bindRecorder(rec);
  installEnv({}); // no SENTRY_DSN
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => {
      called += 1;
      return new Response("ok");
    };
    const wrapped = withCronMonitor(handler, { monitorSlug: "callbot-sweep" });
    const res = await wrapped(new Request("https://stub/cron"));

    assertEquals(res.status, 200);
    assertEquals(called, 1);
    assertEquals(rec.calls.length, 0);
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

// ─── §22.D6 slug resolution ──────────────────────────────────────────────────

Deno.test("withCronMonitor: uses explicit config.monitorSlug above all sources", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnv({
    SENTRY_DSN: "https://stub@sentry.io/1",
    SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses",
    SERVICE_NAME: "auto-loses",
  });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg0.monitorSlug, "explicit-wins");
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  // handlerName "ingest-15min" → env key SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN
  // (hyphens become underscores per D6).
  installEnv({
    SENTRY_DSN: "https://stub@sentry.io/1",
    SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN: "env-wins",
    SERVICE_NAME: "auto-loses",
  });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { handlerName: "ingest-15min" });
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg0.monitorSlug, "env-wins");
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: falls back to auto-derived ${SERVICE_NAME}:${handlerName} (default 'scheduled') when neither set", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnv({
    SENTRY_DSN: "https://stub@sentry.io/1",
    SERVICE_NAME: "callbot-edge",
  });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler);
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg0.monitorSlug, "callbot-edge:scheduled");
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

// ─── §22.D12 / R03 monitorConfig forwarding ──────────────────────────────────

Deno.test("withCronMonitor: forwards monitorConfig on in_progress, omits on completion", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped(new Request("https://stub/cron"));

    assertEquals(rec.calls.length, 2);
    // 1st call (in_progress) — 2nd arg is monitorConfig with schedule + maxRuntime
    assertEquals(rec.calls[0].arg1, {
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntime: 240,
    });
    // 2nd call (ok) — 2nd arg is undefined (Sentry already has monitor config)
    assertEquals(rec.calls[1].arg1, undefined);
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

Deno.test("withCronMonitor: omits monitorConfig entirely when neither schedule nor maxRuntimeSeconds is configured", async () => {
  const rec = makeRecorder();
  rec.returns.push("checkin-abc");
  bindRecorder(rec);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(new Request("https://stub/cron"));

    assert(rec.calls.length >= 1);
    assertEquals(rec.calls[0].arg1, undefined);
  } finally {
    resetRecorder();
    restoreEnv();
  }
});

// ─── R04 SENTRY_DEBUG opt-in logging ─────────────────────────────────────────

// ─── Phase 23 / ADR-0029 / D-08 — Guarded Shape A (F5.supabase) ──────────────
//
// These tests verify that withCronMonitor uses _withMonitorImpl (injectable via
// _setWithMonitorForTest) instead of the hand-rolled captureCheckIn lifecycle.
// The seam avoids module-boundary mocking which `deno test` doesn't support.
//
// F5.1 — withMonitor called with correct slug + monitorConfig
// F5.2 — handler return value propagates
// F5.3 — handler exception re-throws (post-callback propagation)
// F5.4 — R02 fail-safe: no SENTRY_DSN → withMonitor not called
// F5.6 — pre-callback transport throw → handler runs unmonitored (GUARD)
// F5.7 — post-callback transport throw → error propagates

interface WithMonitorCall {
  slug: string;
  // deno-lint-ignore no-explicit-any
  monitorConfig: any;
}

function makeWithMonitorMock(behavior: "passthrough" | "throw-before" | "throw-after") {
  const calls: WithMonitorCall[] = [];
  // deno-lint-ignore no-explicit-any
  const impl = async (slug: string, cb: () => any, monitorConfig?: unknown): Promise<unknown> => {
    calls.push({ slug, monitorConfig });
    if (behavior === "throw-before") {
      throw new Error("Sentry transport failure (pre-callback)");
    }
    const result = await cb();
    if (behavior === "throw-after") {
      throw new Error("post-callback transport failure");
    }
    return result;
  };
  return { calls, impl };
}

Deno.test("F5.1 — withMonitor called with resolved slug and monitorConfig on happy path", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => {
      called += 1;
      return new Response("ok");
    };
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "callbot-sweep",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped(new Request("https://stub/cron"));

    assertEquals(called, 1);
    assertEquals(mock.calls.length, 1);
    assertEquals(mock.calls[0].slug, "callbot-sweep");
    assertEquals(mock.calls[0].monitorConfig, {
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntime: 240,
    });
  } finally {
    // deno-lint-ignore no-explicit-any
    _setWithMonitorForTest((_s: string, cb: () => any) => cb());
    restoreEnv();
  }
});

Deno.test("F5.2 — handler return value propagates through withMonitor callback", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const handler = async (_req: Request): Promise<Response> => new Response("result-body", { status: 201 });
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    const res = await wrapped(new Request("https://stub/cron"));
    assertEquals(res.status, 201);
  } finally {
    // deno-lint-ignore no-explicit-any
    _setWithMonitorForTest((_s: string, cb: () => any) => cb());
    restoreEnv();
  }
});

Deno.test("F5.3 — handler exception re-throws from withMonitor (post-callback error propagates)", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    const boom = new Error("handler exploded");
    const handler = async (_req: Request): Promise<Response> => { throw boom; };
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await assertRejects(
      () => wrapped(new Request("https://stub/cron")),
      Error,
      "handler exploded",
    );
    assertEquals(mock.calls.length, 1);
  } finally {
    // deno-lint-ignore no-explicit-any
    _setWithMonitorForTest((_s: string, cb: () => any) => cb());
    restoreEnv();
  }
});

Deno.test("F5.4 — R02 fail-safe: no SENTRY_DSN → withMonitor not called", async () => {
  const mock = makeWithMonitorMock("passthrough");
  _setWithMonitorForTest(mock.impl);
  installEnv({}); // no SENTRY_DSN
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped(new Request("https://stub/cron"));
    assertEquals(called, 1);
    assertEquals(mock.calls.length, 0);
  } finally {
    // deno-lint-ignore no-explicit-any
    _setWithMonitorForTest((_s: string, cb: () => any) => cb());
    restoreEnv();
  }
});

Deno.test("F5.6 — D-08 guard: withMonitor throws BEFORE callback → handler still executes unmonitored", async () => {
  const mock = makeWithMonitorMock("throw-before");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    // Must NOT throw — falls back to unmonitored handler.
    const res = await wrapped(new Request("https://stub/cron"));
    assertEquals(called, 1);
    assertEquals(res.status, 200);
  } finally {
    // deno-lint-ignore no-explicit-any
    _setWithMonitorForTest((_s: string, cb: () => any) => cb());
    restoreEnv();
  }
});

Deno.test("F5.7 — D-08 guard: withMonitor throws AFTER callback ran → error propagates", async () => {
  const mock = makeWithMonitorMock("throw-after");
  _setWithMonitorForTest(mock.impl);
  installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
  try {
    let called = 0;
    const handler = async (_req: Request): Promise<Response> => { called += 1; return new Response("ok"); };
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await assertRejects(
      () => wrapped(new Request("https://stub/cron")),
      Error,
      "post-callback transport failure",
    );
    assertEquals(called, 1);
  } finally {
    // deno-lint-ignore no-explicit-any
    _setWithMonitorForTest((_s: string, cb: () => any) => cb());
    restoreEnv();
  }
});

Deno.test("withCronMonitor: logs swallowed errors when SENTRY_DEBUG=1, silent otherwise", async () => {
  // Make captureCheckIn throw on every call so the swallow-catch fires.
  const rec = makeRecorder();
  rec.impl = () => { throw new Error("sentry SDK boom"); };
  bindRecorder(rec);

  const origError = console.error;
  let errorCalls: unknown[][] = [];
  console.error = (...args: unknown[]) => { errorCalls.push(args); };

  try {
    const handler = async (_req: Request): Promise<Response> => new Response("ok");

    // SENTRY_DEBUG absent → silent
    installEnv({ SENTRY_DSN: "https://stub@sentry.io/1" });
    const wrappedSilent = withCronMonitor(handler, { monitorSlug: "x" });
    await wrappedSilent(new Request("https://stub/cron"));
    assertEquals(errorCalls.length, 0);

    // SENTRY_DEBUG=1 → console.error called
    errorCalls = [];
    installEnv({ SENTRY_DSN: "https://stub@sentry.io/1", SENTRY_DEBUG: "1" });
    const wrappedDebug = withCronMonitor(handler, { monitorSlug: "x" });
    await wrappedDebug(new Request("https://stub/cron"));
    assert(errorCalls.length > 0, "expected console.error to be called when SENTRY_DEBUG=1");
    // At least one error-call's arg list contains an Error instance.
    const sawError = errorCalls.some((args) => args.some((a) => a instanceof Error));
    assert(sawError, "expected an Error instance among console.error arguments");
  } finally {
    console.error = origError;
    resetRecorder();
    restoreEnv();
  }
});
