/**
 * healthz-snippet.test.ts — healthz handler contract suite (ts-supabase-edge).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the COPY-ONLY healthz template's contract per phase-22 CONTEXT.md
 * and PLAN.md REVISIONS R06 + R07:
 *
 *   D9  — healthz NOT wrapped by withObservability (no span overhead).
 *   R06 — fail-closed on zero probes configured.
 *   R07 — top-of-file multi-line WARNING block.
 *
 * Supabase Edge runs Deno; tests use Deno's built-in `Deno.test` runner
 * (no vitest, no vi.mock — see CONTEXT R03 lesson from T04). The handler
 * is invoked directly with a Request and a deps object; the supabase
 * client is INJECTED via `deps.supabase` (not pulled from the module
 * graph) so the test can supply a stub without monkey-patching.
 *
 * Supabase adaptation target:
 *   - `deps.supabase` — supabase-js client; probe = `from(table).select(s).limit(0)`
 *
 * Run with: deno test -A --no-check healthz-snippet.test.ts
 */

import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import healthzHandler from "./healthz-snippet.ts";

// ─── Stub builders ────────────────────────────────────────────────────────────

interface ProbeResult { error: unknown }

function makeSupabaseStub(result: ProbeResult | Error): {
  from: (t: string) => {
    select: (s: string) => {
      limit: (n: number) => Promise<ProbeResult>;
    };
  };
  _fromCalls: string[];
  _selectCalls: string[];
  _limitCalls: number[];
} {
  const fromCalls: string[] = [];
  const selectCalls: string[] = [];
  const limitCalls: number[] = [];
  return {
    from(table: string) {
      fromCalls.push(table);
      return {
        select(s: string) {
          selectCalls.push(s);
          return {
            limit(n: number) {
              limitCalls.push(n);
              if (result instanceof Error) return Promise.reject(result);
              return Promise.resolve(result);
            },
          };
        },
      };
    },
    _fromCalls: fromCalls,
    _selectCalls: selectCalls,
    _limitCalls: limitCalls,
  };
}

function req(): Request {
  return new Request("https://stub/healthz");
}

// ─── R06 fail-closed default ──────────────────────────────────────────────────

Deno.test("R06 — returns 503 status:degraded with reason when no probes configured", async () => {
  const res = await healthzHandler(req(), {});
  assertEquals(res.status, 503);
  assert(
    (res.headers.get("content-type") ?? "").includes("application/json"),
    "content-type should be JSON",
  );
  const body = await res.json();
  assertEquals(body, {
    status: "degraded",
    reason: "no probes configured — adapt healthz-snippet.ts to your dependencies",
    checks: {},
  });
});

// ─── Happy path ───────────────────────────────────────────────────────────────

Deno.test("returns 200 status:ok when supabase probe succeeds", async () => {
  const stub = makeSupabaseStub({ error: null });
  const res = await healthzHandler(req(), { supabase: stub });
  assertEquals(res.status, 200);
  const body = await res.json();
  assertEquals(body, { status: "ok", checks: { supabase: true } });
  // Sanity: probe was actually invoked with the canonical shape.
  assertEquals(stub._selectCalls, ["*"]);
  assertEquals(stub._limitCalls, [0]);
});

// ─── Failure paths ────────────────────────────────────────────────────────────

Deno.test("returns 503 status:degraded when supabase probe returns error object (PostgREST shape)", async () => {
  const stub = makeSupabaseStub({ error: { message: "relation does not exist" } });
  const res = await healthzHandler(req(), { supabase: stub });
  assertEquals(res.status, 503);
  const body = await res.json();
  assertEquals(body, { status: "degraded", checks: { supabase: false } });
});

Deno.test("returns 503 status:degraded when supabase probe throws", async () => {
  const stub = makeSupabaseStub(new Error("supabase down"));
  const res = await healthzHandler(req(), { supabase: stub });
  assertEquals(res.status, 503);
  const body = await res.json();
  assertEquals(body, { status: "degraded", checks: { supabase: false } });
});
