/**
 * Contract roundtrip test for the observability wrapper (Supabase Edge / Deno).
 *
 * Generated by the add-observability skill. Run with Deno's built-in test
 * runner:
 *
 *   deno test --allow-env supabase/functions/_shared/observability/index.test.ts
 *
 * Tests verify the spec §10 contract WITHOUT requiring Sentry init —
 * the wrapper must work standalone (console-only) when SENTRY_DSN is unset.
 */

import { assert, assertEquals, assertNotEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import {
  parseTraceparent,
  newRootContext,
  formatTraceparent,
  startSpan,
  logEvent,
  captureError,
  runWithContext,
  getActiveContext,
} from "./index.ts";

// ─── §10.3 traceparent roundtrip ────────────────────────────────────────────

Deno.test("§10.3 traceparent: format → parse roundtrip", () => {
  const root = newRootContext();
  const header = formatTraceparent(root);
  const parsed = parseTraceparent(header);
  assert(parsed !== null);
  assertEquals(parsed!.traceId, root.traceId);
  assertEquals(parsed!.parentSpanId, root.spanId);
});

Deno.test("§10.3 traceparent: rejects malformed inputs", () => {
  for (const header of ["", "not-a-traceparent", "00-tooshort-tooshort-01", "00-XYZ-not-hex-01"]) {
    assertEquals(parseTraceparent(header), null, `expected reject for ${header}`);
  }
});

Deno.test("§10.3 traceparent: accepts canonical W3C example", () => {
  const header = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";
  const tc = parseTraceparent(header);
  assert(tc !== null);
  assertEquals(tc!.traceId, "4bf92f3577b34da6a3ce929d0e0e4736");
  assertEquals(tc!.parentSpanId, "00f067aa0ba902b7");
  assertEquals(tc!.spanId.length, 16);
  assertNotEquals(tc!.spanId, tc!.parentSpanId);
});

// ─── §10.5 fail-safe ────────────────────────────────────────────────────────

Deno.test("§10.5 fail-safe: logEvent does not throw without init", () => {
  logEvent({ event: "test", severity: "info" });
  // no throw = pass
});

Deno.test("§10.5 fail-safe: captureError handles real errors", () => {
  captureError(new Error("boom"), { event: "test", severity: "error" });
});

Deno.test("§10.5 fail-safe: captureError handles non-Error values", () => {
  captureError("string error", { event: "test" });
  captureError({ weird: "object" }, { event: "test" });
  captureError(undefined, { event: "test" });
});

// ─── §10.1 span lifecycle ───────────────────────────────────────────────────

Deno.test("§10.1 startSpan: returns valid IDs", () => {
  const span = startSpan("test", { k: "v" });
  assert(/^[0-9a-f]{32}$/.test(span.traceId));
  assert(/^[0-9a-f]{16}$/.test(span.spanId));
  span.end();
});

Deno.test("§10.1 startSpan: end() is idempotent", () => {
  const span = startSpan("test");
  span.end();
  span.end(); // no throw = pass
});

Deno.test("§10.1 startSpan: setStatus + end works", () => {
  const span = startSpan("test");
  span.setStatus("error");
  span.end();
});

// ─── §10.3 runWithContext / getActiveContext ────────────────────────────────

Deno.test("§10.3 active context: null outside runWithContext", () => {
  assertEquals(getActiveContext(), null);
});

Deno.test("§10.3 active context: bound inside runWithContext", () => {
  const root = newRootContext();
  runWithContext(root, "test", () => {
    const active = getActiveContext();
    assert(active !== null);
    assertEquals(active!.traceId, root.traceId);
    assertEquals(active!.spanId, root.spanId);
  });
});

Deno.test("§10.3 active context: nested scopes correctly", () => {
  const outer = newRootContext();
  const inner = newRootContext();
  runWithContext(outer, "outer", () => {
    assertEquals(getActiveContext()!.traceId, outer.traceId);
    runWithContext(inner, "inner", () => {
      assertEquals(getActiveContext()!.traceId, inner.traceId);
    });
    assertEquals(getActiveContext()!.traceId, outer.traceId);
  });
});
