/**
 * Observability wrapper — AgenticApps spec §10 v0.2.1 (Supabase Edge / Deno)
 *
 * Service:     {{SERVICE_NAME}}
 * Destination: {{DESTINATION}}
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong in a sibling `extensions.ts`.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)
 *  - captureError(err, env)
 *  - startSpan(name, attrs) → Span
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 *
 * DENO / SUPABASE NOTES:
 *
 * - Imports use Deno's npm: specifier for the Sentry SDK and node:
 *   specifier for AsyncLocalStorage (Supabase Edge Functions support
 *   Deno's Node-compat layer).
 * - Env vars come from `Deno.env.get(...)`, not `process.env` or
 *   `import.meta.env`. Set via `supabase secrets set` for production
 *   and `supabase/.env` for local dev.
 * - No per-request `waitUntil` — emission is best-effort with a flush
 *   call at the end of each handler invocation. Use
 *   `withObservability(handler)` from `./middleware.ts` to wire this.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import { buildRegistry, resolveConfig, type Registry } from "./destinations/registry.ts";
import { SENTRY_RESERVED_ATTRS } from "./destinations/sentry.ts";

// ─── Types ─────────────────────────────────────────────────────────────────

export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";

export interface Envelope {
  event: string;
  severity?: Severity;
  attrs?: Record<string, unknown>;
}

export interface Span {
  setAttribute(key: string, value: unknown): void;
  setStatus(status: SpanStatus): void;
  end(opts?: { status?: SpanStatus }): void;
  readonly traceId: string;
  readonly spanId: string;
}

export interface TraceContext {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  flags: number;
}

interface InternalSpanContext extends TraceContext {
  startedAt: number;
  name: string;
  attributes: Record<string, unknown>;
  status: SpanStatus | "unset";
}

// ─── Static config (parameterized at generation time) ─────────────────────

const SERVICE_DEFAULT = "{{SERVICE_NAME}}";
const DEBUG_SAMPLE_RATE = {{DEBUG_SAMPLE_RATE}};
const TRACE_SAMPLE_RATE = {{TRACE_SAMPLE_RATE}};

const REDACTED_KEYS: ReadonlyArray<string> = [
  {{REDACTED_KEYS}}
];

// ─── Module state ─────────────────────────────────────────────────────────

const spanStorage = new AsyncLocalStorage<InternalSpanContext>();

let initialized = false;
let serviceName: string = SERVICE_DEFAULT;
let deployEnv: string = "dev";

/** @internal — test-only seam. Never set in production code. */
let _testEnv: InitEnv | null = null;

// Role-based destination registry, built once in `init`. logEvent dispatches
// to the LOGS adapter; captureError to the ERRORS adapter. Null until init
// runs. All SDK-specific behaviour (Sentry init/capture/breadcrumb, Axiom
// POST) now lives behind the adapters; this wrapper owns the console mirror +
// sampling + dispatch.
let registry: Registry | null = null;

// ─── Initialization ───────────────────────────────────────────────────────

/**
 * The configuration source the destination adapters read. On Supabase Edge
 * this is assembled from `Deno.env.get(...)`; tests pass an override so they
 * can inject the egress fetch (`__fetch`) and `OBS_DESTINATIONS` without
 * mutating the real Deno.env. Index-signature so adapters can read AXIOM_* /
 * SENTRY_DSN / OBS_DESTINATIONS / __fetch generically.
 */
export interface InitEnv {
  SENTRY_DSN?: string;
  DEPLOY_ENV?: string;
  SERVICE_NAME?: string;
  AXIOM_TOKEN?: string;
  AXIOM_DATASET?: string;
  AXIOM_INGEST_URL?: string;
  OBS_DESTINATIONS?: string;
  [key: string]: unknown;
}

/** Assemble an InitEnv from Deno.env (string vars only). */
function envFromDeno(): InitEnv {
  const get = (k: string): string | undefined => {
    try {
      return Deno.env.get(k) ?? undefined;
    } catch {
      return undefined;
    }
  };
  return {
    SENTRY_DSN: get("{{ENV_VAR_DSN}}"),
    DEPLOY_ENV: get("{{ENV_VAR_ENV}}"),
    SERVICE_NAME: get("{{ENV_VAR_SERVICE}}"),
    AXIOM_TOKEN: get("AXIOM_TOKEN"),
    AXIOM_DATASET: get("AXIOM_DATASET"),
    AXIOM_INGEST_URL: get("AXIOM_INGEST_URL"),
    OBS_DESTINATIONS: get("OBS_DESTINATIONS"),
  };
}

/**
 * Reset module state and inject a test environment override. Call this
 * BEFORE `init()` in each test case so the next `init()` rebuilds the
 * registry with the injected env instead of reading `Deno.env`.
 *
 * @internal — test-only export. Never call from production code.
 */
export function _resetForTest(env?: InitEnv): void {
  _testEnv = env ?? null;
  initialized = false;
  registry = null;
}

/**
 * Initialize the wrapper. Idempotent (zero-arg; env is read from `Deno.env`
 * unless a test has pre-loaded `_testEnv` via `_resetForTest`). In
 * production, this is called once per handler invocation by the middleware.
 *
 * Builds the role-based destination registry: each configured named adapter is
 * init()-ed (the Sentry adapter calls `Sentry.init` when a DSN is present, the
 * Axiom adapter caches token/dataset/ingest + egress fetch). resolveConfig is
 * fail-closed (errors can never resolve to Axiom). There is no Cloudflare
 * `ctx` on Edge, so ctx is undefined; the Axiom adapter uses
 * `EdgeRuntime.waitUntil` (guarded) for fire-and-forget egress.
 */
export function init(): void {
  if (initialized) return;

  const env = _testEnv ?? envFromDeno();
  serviceName = env.SERVICE_NAME ?? SERVICE_DEFAULT;
  deployEnv = env.DEPLOY_ENV ?? "dev";

  registry = buildRegistry(resolveConfig(env), env);
  initialized = true;
}

/**
 * Best-effort flush. Edge Functions do not have a `waitUntil` — call
 * this at the end of each handler invocation (the middleware does it
 * automatically) so events buffered by the Sentry SDK are sent before
 * the function isolate is torn down. Delegates to the ERRORS adapter's
 * `flush` (Sentry). Events lost beyond the cap are acceptable per §10.5.
 */
export async function flush(timeoutMs: number = 2000): Promise<void> {
  if (!initialized) return;
  try {
    await registry?.forRole("errors")?.flush?.(timeoutMs);
  } catch {
    /* observability MUST NOT throw */
  }
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

const TRACEPARENT_RE = /^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/i;

function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

export function parseTraceparent(header: string | null | undefined): TraceContext | null {
  if (!header) return null;
  const m = TRACEPARENT_RE.exec(header.trim());
  if (!m) return null;
  return {
    traceId: m[2].toLowerCase(),
    spanId: randHex(8),
    parentSpanId: m[3].toLowerCase(),
    flags: parseInt(m[4], 16),
  };
}

export function newRootContext(): TraceContext {
  return { traceId: randHex(16), spanId: randHex(8), flags: 1 };
}

export function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string {
  return `00-${c.traceId}-${c.spanId}-${c.flags.toString(16).padStart(2, "0")}`;
}

// ─── Run-with-context (used by middleware) ────────────────────────────────

export function runWithContext<T>(ctx: TraceContext, name: string, fn: () => T): T {
  const internal: InternalSpanContext = {
    ...ctx,
    startedAt: Date.now(),
    name,
    attributes: {},
    status: "unset",
  };
  return spanStorage.run(internal, fn);
}

export function getActiveContext(): TraceContext | null {
  const c = spanStorage.getStore();
  return c ? { traceId: c.traceId, spanId: c.spanId, parentSpanId: c.parentSpanId, flags: c.flags } : null;
}

// ─── startSpan ────────────────────────────────────────────────────────────

export function startSpan(name: string, attributes: Record<string, unknown> = {}): Span {
  const parent = spanStorage.getStore();
  const ctx: TraceContext = parent
    ? { traceId: parent.traceId, spanId: randHex(8), parentSpanId: parent.spanId, flags: parent.flags }
    : newRootContext();

  const startedAt = Date.now();
  const attrs: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(attributes)) attrs[k] = redactValue(k, v);

  let status: SpanStatus | "unset" = "unset";
  let ended = false;

  return {
    setAttribute(key, value) {
      attrs[key] = redactValue(key, value);
    },
    setStatus(s) {
      status = s;
    },
    end(opts) {
      if (ended) return;
      ended = true;
      if (opts?.status) status = opts.status;
      const finalStatus: SpanStatus = status === "unset" ? "ok" : status;
      const enriched = emit(
        {
          event: name,
          severity: finalStatus === "error" ? "error" : "info",
          attrs: { ...attrs, duration_ms: Date.now() - startedAt, span_status: finalStatus },
        },
        ctx,
      );
      // Spans stay Sentry-native: a span-end breadcrumb on the ERRORS
      // destination, NEVER routed to the Axiom logs sink. No-op when errors is
      // unconfigured / non-Sentry.
      if (enriched) registry?.forRole("errors")?.emit(enriched);
    },
    get traceId() { return ctx.traceId; },
    get spanId() { return ctx.spanId; },
  };
}

// ─── logEvent / captureError ──────────────────────────────────────────────

export function logEvent(envelope: Envelope): void {
  const enriched = emit(envelope, spanStorage.getStore() ?? null);
  if (!enriched) return;
  // Dispatch to the LOGS destination (e.g. Axiom POST). No-op when logs is
  // "none". Attrs are already redacted — adapters never see raw attrs.
  registry?.forRole("logs")?.emit(enriched);
  // Breadcrumb on the ERRORS destination (Sentry) so the next captureException
  // carries this context. No-op when errors is unconfigured / non-Sentry.
  registry?.forRole("errors")?.emit(enriched);
}

export function captureError(err: unknown, envelope: Envelope): void {
  const ctx = spanStorage.getStore();
  if (ctx) ctx.status = "error";

  const enriched = emit({ ...envelope, severity: envelope.severity ?? "error" }, ctx ?? null);

  // Dispatch to the ERRORS destination (Sentry scoped captureException). No-op
  // when errors is unconfigured. By the fail-closed registry contract this can
  // NEVER reach the logs-only Axiom adapter (its captureException is a no-op
  // anyway). The enriched envelope carries service/env/trace under reserved
  // attrs so the adapter can rebuild Sentry scope tags.
  if (enriched) registry?.forRole("errors")?.captureException(err, enriched);
}

// ─── Internal: emit ───────────────────────────────────────────────────────
//
// Owns the console mirror + sampling, and builds the enriched+redacted
// envelope handed to destination adapters. Returns null when the event was
// sampled out (so callers skip dispatch).

function emit(envelope: Envelope, ctx: TraceContext | null): Envelope | null {
  const severity: Severity = envelope.severity ?? "info";
  if (severity === "debug" && Math.random() > DEBUG_SAMPLE_RATE) return null;

  const traceId = ctx?.traceId ?? randHex(16);
  const spanId = ctx?.spanId ?? randHex(8);
  const redactedAttrs = redactObject(envelope.attrs ?? {});

  const event = {
    trace_id: traceId,
    span_id: spanId,
    service: serviceName,
    env: deployEnv,
    event: envelope.event,
    severity,
    attrs: redactedAttrs,
    ts: Date.now(),
  };

  const line = JSON.stringify(event);
  if (severity === "error" || severity === "fatal") console.error(line);
  else if (severity === "warn") console.warn(line);
  else console.log(line);

  // Enriched envelope for adapter dispatch: redacted user attrs plus reserved
  // correlation keys (service/env/trace) the Sentry adapter reads for scope
  // tags. The reserved keys also give Axiom log/trace correlation for free.
  return {
    event: envelope.event,
    severity,
    attrs: {
      ...redactedAttrs,
      [SENTRY_RESERVED_ATTRS.service]: serviceName,
      [SENTRY_RESERVED_ATTRS.env]: deployEnv,
      [SENTRY_RESERVED_ATTRS.traceId]: traceId,
      [SENTRY_RESERVED_ATTRS.spanId]: spanId,
    },
  };
}

function redactValue(key: string, value: unknown): unknown {
  const k = key.toLowerCase();
  if (REDACTED_KEYS.some((r) => k.includes(r))) return "[redacted]";
  return value;
}

function redactObject(obj: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = redactValue(k, v);
  return out;
}

// ─── Project-specific extensions ──────────────────────────────────────────
