/**
 * Observability wrapper — AgenticApps spec §10 v0.2.1 (Supabase Edge / Deno)
 *
 * Service:     {{SERVICE_NAME}}
 * Destination: {{DESTINATION}}
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong in a sibling `extensions.ts`.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)
 *  - captureError(err, env)
 *  - startSpan(name, attrs) → Span
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 *
 * DENO / SUPABASE NOTES:
 *
 * - Imports use Deno's npm: specifier for the Sentry SDK and node:
 *   specifier for AsyncLocalStorage (Supabase Edge Functions support
 *   Deno's Node-compat layer).
 * - Env vars come from `Deno.env.get(...)`, not `process.env` or
 *   `import.meta.env`. Set via `supabase secrets set` for production
 *   and `supabase/.env` for local dev.
 * - No per-request `waitUntil` — emission is best-effort with a flush
 *   call at the end of each handler invocation. Use
 *   `withObservability(handler)` from `./middleware.ts` to wire this.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import * as Sentry from "npm:@sentry/deno@^8.0.0";

// ─── Types ─────────────────────────────────────────────────────────────────

export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";

export interface Envelope {
  event: string;
  severity?: Severity;
  attrs?: Record<string, unknown>;
}

export interface Span {
  setAttribute(key: string, value: unknown): void;
  setStatus(status: SpanStatus): void;
  end(opts?: { status?: SpanStatus }): void;
  readonly traceId: string;
  readonly spanId: string;
}

export interface TraceContext {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  flags: number;
}

interface InternalSpanContext extends TraceContext {
  startedAt: number;
  name: string;
  attributes: Record<string, unknown>;
  status: SpanStatus | "unset";
}

// ─── Static config (parameterized at generation time) ─────────────────────

const SERVICE_DEFAULT = "{{SERVICE_NAME}}";
const DEBUG_SAMPLE_RATE = {{DEBUG_SAMPLE_RATE}};
const TRACE_SAMPLE_RATE = {{TRACE_SAMPLE_RATE}};

const REDACTED_KEYS: ReadonlyArray<string> = [
  {{REDACTED_KEYS}}
];

// ─── Module state ─────────────────────────────────────────────────────────

const spanStorage = new AsyncLocalStorage<InternalSpanContext>();

let initialized = false;
let serviceName: string = SERVICE_DEFAULT;
let deployEnv: string = "dev";

// ─── Initialization ───────────────────────────────────────────────────────

export function init(): void {
  if (initialized) return;

  serviceName = Deno.env.get("{{ENV_VAR_SERVICE}}") ?? SERVICE_DEFAULT;
  deployEnv = Deno.env.get("{{ENV_VAR_ENV}}") ?? "dev";
  const dsn = Deno.env.get("{{ENV_VAR_DSN}}");

  if (dsn) {
    Sentry.init({
      dsn,
      environment: deployEnv,
      release: serviceName,
      tracesSampleRate: TRACE_SAMPLE_RATE,
      sendDefaultPii: false,
    });
  }
  initialized = true;
}

/**
 * Best-effort flush. Edge Functions do not have a `waitUntil` — call
 * this at the end of each handler invocation (the middleware does it
 * automatically) so events buffered by the Sentry SDK are sent before
 * the function isolate is torn down.
 *
 * Sentry's flush returns a promise; we cap the wait to 2 seconds to
 * avoid blocking the response. Events lost beyond the cap are
 * acceptable per §10.5 ("a broken or slow observability destination
 * MUST NOT degrade end-user latency or availability").
 */
export async function flush(timeoutMs: number = 2000): Promise<void> {
  if (!initialized) return;
  try {
    await Sentry.flush(timeoutMs);
  } catch {
    /* observability MUST NOT throw */
  }
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

const TRACEPARENT_RE = /^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/i;

function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

export function parseTraceparent(header: string | null | undefined): TraceContext | null {
  if (!header) return null;
  const m = TRACEPARENT_RE.exec(header.trim());
  if (!m) return null;
  return {
    traceId: m[2].toLowerCase(),
    spanId: randHex(8),
    parentSpanId: m[3].toLowerCase(),
    flags: parseInt(m[4], 16),
  };
}

export function newRootContext(): TraceContext {
  return { traceId: randHex(16), spanId: randHex(8), flags: 1 };
}

export function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string {
  return `00-${c.traceId}-${c.spanId}-${c.flags.toString(16).padStart(2, "0")}`;
}

// ─── Run-with-context (used by middleware) ────────────────────────────────

export function runWithContext<T>(ctx: TraceContext, name: string, fn: () => T): T {
  const internal: InternalSpanContext = {
    ...ctx,
    startedAt: Date.now(),
    name,
    attributes: {},
    status: "unset",
  };
  return spanStorage.run(internal, fn);
}

export function getActiveContext(): TraceContext | null {
  const c = spanStorage.getStore();
  return c ? { traceId: c.traceId, spanId: c.spanId, parentSpanId: c.parentSpanId, flags: c.flags } : null;
}

// ─── startSpan ────────────────────────────────────────────────────────────

export function startSpan(name: string, attributes: Record<string, unknown> = {}): Span {
  const parent = spanStorage.getStore();
  const ctx: TraceContext = parent
    ? { traceId: parent.traceId, spanId: randHex(8), parentSpanId: parent.spanId, flags: parent.flags }
    : newRootContext();

  const startedAt = Date.now();
  const attrs: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(attributes)) attrs[k] = redactValue(k, v);

  let status: SpanStatus | "unset" = "unset";
  let ended = false;

  return {
    setAttribute(key, value) {
      attrs[key] = redactValue(key, value);
    },
    setStatus(s) {
      status = s;
    },
    end(opts) {
      if (ended) return;
      ended = true;
      if (opts?.status) status = opts.status;
      const finalStatus: SpanStatus = status === "unset" ? "ok" : status;
      emit(
        {
          event: name,
          severity: finalStatus === "error" ? "error" : "info",
          attrs: { ...attrs, duration_ms: Date.now() - startedAt, span_status: finalStatus },
        },
        ctx,
      );
    },
    get traceId() { return ctx.traceId; },
    get spanId() { return ctx.spanId; },
  };
}

// ─── logEvent / captureError ──────────────────────────────────────────────

export function logEvent(envelope: Envelope): void {
  emit(envelope, spanStorage.getStore() ?? null);
}

export function captureError(err: unknown, envelope: Envelope): void {
  const ctx = spanStorage.getStore();
  if (ctx) ctx.status = "error";

  if (initialized && err instanceof Error) {
    safeFireAndForget(() => {
      Sentry.withScope((scope) => {
        scope.setTag("event", envelope.event);
        scope.setTag("service", serviceName);
        scope.setTag("env", deployEnv);
        if (ctx) {
          scope.setTag("trace_id", ctx.traceId);
          scope.setTag("span_id", ctx.spanId);
        }
        if (envelope.attrs) {
          scope.setContext("attrs", redactObject(envelope.attrs));
        }
        Sentry.captureException(err);
      });
    });
  }

  emit({ ...envelope, severity: envelope.severity ?? "error" }, ctx ?? null);
}

// ─── Internal: emit ───────────────────────────────────────────────────────

function emit(envelope: Envelope, ctx: TraceContext | null): void {
  const severity: Severity = envelope.severity ?? "info";
  if (severity === "debug" && Math.random() > DEBUG_SAMPLE_RATE) return;

  const event = {
    trace_id: ctx?.traceId ?? randHex(16),
    span_id: ctx?.spanId ?? randHex(8),
    service: serviceName,
    env: deployEnv,
    event: envelope.event,
    severity,
    attrs: redactObject(envelope.attrs ?? {}),
    ts: Date.now(),
  };

  const line = JSON.stringify(event);
  if (severity === "error" || severity === "fatal") console.error(line);
  else if (severity === "warn") console.warn(line);
  else console.log(line);

  if (initialized && severity !== "debug") {
    safeFireAndForget(() => {
      Sentry.addBreadcrumb({
        category: event.event,
        level: sentryLevel(severity),
        data: event.attrs as { [k: string]: unknown },
      });
    });
  }
}

function sentryLevel(s: Severity): Sentry.SeverityLevel {
  return s === "warn" ? "warning" : (s as Sentry.SeverityLevel);
}

function safeFireAndForget(fn: () => void): void {
  try {
    Promise.resolve().then(fn).catch(() => {});
  } catch {
    /* swallow */
  }
}

function redactValue(key: string, value: unknown): unknown {
  const k = key.toLowerCase();
  if (REDACTED_KEYS.some((r) => k.includes(r))) return "[redacted]";
  return value;
}

function redactObject(obj: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = redactValue(k, v);
  return out;
}

// ─── Project-specific extensions ──────────────────────────────────────────
