/**
 * llm-response-meta.test.ts — recordLLMResponseMeta contract suite (ts-supabase-edge).
 *
 * Generated by the add-observability skill. Run with Deno's built-in test
 * runner:
 *
 *   deno test --allow-net supabase/functions/_shared/observability/llm-response-meta.test.ts
 *
 * Tests the post-processing helper for OpenAI-SDK-against-OpenRouter calls.
 * Phase 24 / ADR-0030 — SDK-first integration: helper captures the two
 * signals AI Monitoring doesn't surface (rate-limit headroom + cache_ratio).
 *
 * Helper takes logEvent by dependency injection (§10.6 destination-independence).
 * Mirrors ts-cloudflare-worker's 7 fixtures, ported to Deno's test API.
 *
 * Note: import path uses Deno explicit-extension `./index.ts` (NOT `./index` —
 * Deno doesn't apply bundler resolution). Per CONTEXT D-04a.
 */

import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import { recordLLMResponseMeta } from "./llm-response-meta.ts";
import type { Envelope } from "./index.ts";

// Helper: capture every emitted envelope into an array.
function makeCapture(): {
  envelopes: Envelope[];
  logEvent: (e: Envelope) => void;
} {
  const envelopes: Envelope[] = [];
  return { envelopes, logEvent: (e: Envelope) => envelopes.push(e) };
}

Deno.test("recordLLMResponseMeta (1) cache hit produces correct cache_ratio", () => {
  const { envelopes, logEvent } = makeCapture();
  const response = new Response("", {
    headers: { "x-ratelimit-remaining": "42", "x-ratelimit-reset": "1700000000" },
  });
  recordLLMResponseMeta(
    logEvent,
    response,
    {
      prompt_tokens: 1000,
      completion_tokens: 200,
      prompt_tokens_details: { cached_tokens: 800 },
    },
    { model: "anthropic/claude-3.5-sonnet" },
  );
  assertEquals(envelopes.length, 1);
  assertEquals(envelopes[0].event, "llm.call_meta");
  assertEquals(envelopes[0].severity, "info");
  assertEquals(envelopes[0].attrs?.model, "anthropic/claude-3.5-sonnet");
  assertEquals(envelopes[0].attrs?.service, "openrouter");
  assertEquals(envelopes[0].attrs?.rate_remaining, "42");
  assertEquals(envelopes[0].attrs?.rate_reset, "1700000000");
  assertEquals(envelopes[0].attrs?.cached_tokens, 800);
  assertEquals(envelopes[0].attrs?.prompt_tokens, 1000);
  assertEquals(envelopes[0].attrs?.completion_tokens, 200);
  assertEquals(envelopes[0].attrs?.cache_ratio, 0.8);
});

Deno.test("recordLLMResponseMeta (2) cache miss produces cache_ratio = 0", () => {
  const { envelopes, logEvent } = makeCapture();
  recordLLMResponseMeta(
    logEvent,
    new Response(""),
    {
      prompt_tokens: 1000,
      completion_tokens: 200,
      prompt_tokens_details: { cached_tokens: 0 },
    },
    { model: "openai/gpt-4" },
  );
  assertEquals(envelopes[0].attrs?.cache_ratio, 0);
  assertEquals(envelopes[0].attrs?.cached_tokens, 0);
});

Deno.test("recordLLMResponseMeta (3) divide-by-zero safety — prompt_tokens=0 → cache_ratio=0", () => {
  const { envelopes, logEvent } = makeCapture();
  recordLLMResponseMeta(
    logEvent,
    new Response(""),
    { prompt_tokens: 0, completion_tokens: 0 },
    { model: "openai/gpt-4" },
  );
  assertEquals(envelopes[0].attrs?.cache_ratio, 0);
  assert(!Number.isNaN(envelopes[0].attrs?.cache_ratio as number));
});

Deno.test("recordLLMResponseMeta (4) missing usage fields default to 0", () => {
  const { envelopes, logEvent } = makeCapture();
  recordLLMResponseMeta(logEvent, new Response(""), {}, { model: "openai/gpt-4" });
  assertEquals(envelopes[0].attrs?.cached_tokens, 0);
  assertEquals(envelopes[0].attrs?.prompt_tokens, 0);
  assertEquals(envelopes[0].attrs?.completion_tokens, 0);
  assertEquals(envelopes[0].attrs?.cache_ratio, 0);
});

Deno.test("recordLLMResponseMeta (5) missing rate-limit headers pass through as null", () => {
  const { envelopes, logEvent } = makeCapture();
  recordLLMResponseMeta(
    logEvent,
    new Response(""), // no headers
    { prompt_tokens: 100 },
    { model: "openai/gpt-4" },
  );
  assertEquals(envelopes[0].attrs?.rate_remaining, null);
  assertEquals(envelopes[0].attrs?.rate_reset, null);
});

Deno.test('recordLLMResponseMeta (6) service defaults to "openrouter"', () => {
  const { envelopes, logEvent } = makeCapture();
  recordLLMResponseMeta(
    logEvent,
    new Response(""),
    { prompt_tokens: 100 },
    { model: "openai/gpt-4" },
  );
  assertEquals(envelopes[0].attrs?.service, "openrouter");
});

Deno.test("recordLLMResponseMeta (7) service override respected", () => {
  const { envelopes, logEvent } = makeCapture();
  recordLLMResponseMeta(
    logEvent,
    new Response(""),
    { prompt_tokens: 100 },
    { model: "llama-3.1-70b", service: "groq" },
  );
  assertEquals(envelopes[0].attrs?.service, "groq");
});
