/**
 * cron-monitor.test.ts — withCronMonitor contract suite (ts-cloudflare-pages).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the Sentry Crons heartbeat wrapper contract from phase-22 CONTEXT.md:
 *   D1  — separate-wrapper export
 *   D5c — Pages Functions have no scheduled handler; wrapper accepts a generic
 *         () => Promise<R> and is invoked externally (no standard composition).
 *   D6  — 3-source slug resolution (explicit > env > auto-derive)
 *         Pages auto-shape: `${SERVICE_NAME}:${handlerName ?? "scheduled"}`.
 *   D12 — schedule + maxRuntimeSeconds forwarded as Sentry monitorConfig (3rd
 *         arg to Sentry.withMonitor)
 *
 * Phase 23 / ADR-0029 — Guarded Shape A refactor:
 *   D-08 — withCronMonitor now composes Sentry.withMonitor instead of hand-rolling
 *           captureCheckIn lifecycle. Tests updated to assert withMonitor invocation
 *           contract + handlerStarted guard behaviour.
 *
 * Sentry SDK is mocked at the module boundary so SDK shape doesn't matter at
 * test-time — only the invocation contract does.
 */

import { describe, it, expect, vi, beforeEach, expectTypeOf } from "vitest";
// MonitorConfig lives in @sentry/core (not re-exported from @sentry/cloudflare's public API).
import type { MonitorConfig as SentryMonitorConfig } from "@sentry/core";
import { withCronMonitor, type CronMonitorSchedule } from "./cron-monitor";

const withMonitor = vi.fn();
vi.mock("@sentry/cloudflare", () => ({
  withMonitor: (...args: unknown[]) => withMonitor(...args),
}));

beforeEach(() => {
  withMonitor.mockReset();
  // Default: withMonitor calls its callback and returns the result.
  withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => cb());
});

describe("withCronMonitor — Guarded Shape A (ADR-0029 / D-08)", () => {
  it("calls Sentry.withMonitor with resolved slug and monitorConfig on happy path", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "fxsa-ingest-15min",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });
    await wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" });

    expect(withMonitor).toHaveBeenCalledOnce();
    expect(withMonitor).toHaveBeenCalledWith(
      "fxsa-ingest-15min",
      expect.any(Function),
      { schedule: { type: "crontab", value: "*/15 * * * *" }, maxRuntime: 240 },
    );
    expect(handler).toHaveBeenCalledOnce();
  });

  it("handler return value propagates through withMonitor callback", async () => {
    const handler = vi.fn(async () => "result-value");
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    const result = await wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" });
    expect(result).toBe("result-value");
  });

  it("handler exception re-throws from withMonitor (post-callback error propagates)", async () => {
    const boom = new Error("handler exploded");
    const handler = vi.fn(async () => { throw boom; });
    withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => cb());
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await expect(
      wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" }),
    ).rejects.toBe(boom);

    expect(handler).toHaveBeenCalledOnce();
  });

  it("no-ops cleanly when SENTRY_DSN is unset (R02 fail-safe preserved)", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });

    await wrapped({} as Record<string, unknown>);

    expect(handler).toHaveBeenCalledOnce();
    expect(withMonitor).not.toHaveBeenCalled();
  });

  // Guarded Shape A — core guard: pre-callback transport throw → handler runs unmonitored.
  it("D-08 guard: withMonitor throws BEFORE callback runs → handler still executes unmonitored", async () => {
    const handler = vi.fn(async () => {});
    // withMonitor throws without ever invoking the callback.
    withMonitor.mockRejectedValue(new Error("Sentry transport failure"));

    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    // Must NOT throw — falls back to unmonitored handler.
    await wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" });

    expect(handler).toHaveBeenCalledOnce();
  });

  it("D-08 guard: withMonitor throws AFTER callback ran → error propagates (post-callback)", async () => {
    const handler = vi.fn(async () => {});
    // withMonitor calls callback then throws.
    withMonitor.mockImplementation(async (_slug: unknown, cb: () => unknown) => {
      await cb(); // callback ran — handlerStarted = true
      throw new Error("post-callback transport failure");
    });

    const wrapped = withCronMonitor(handler, { monitorSlug: "fxsa-ingest-15min" });
    await expect(
      wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" }),
    ).rejects.toThrow("post-callback transport failure");

    expect(handler).toHaveBeenCalledOnce();
  });
});

describe("withCronMonitor — slug resolution (D6)", () => {
  it("uses explicit config.monitorSlug above all sources", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "explicit-wins" });

    await wrapped({
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_SCHEDULED: "env-loses",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>);

    expect(withMonitor).toHaveBeenCalledWith("explicit-wins", expect.any(Function), undefined);
  });

  it("falls back to SENTRY_CRON_MONITOR_SLUG_<handler> env when explicit absent", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { handlerName: "ingest-15min" });

    await wrapped({
      SENTRY_DSN: "https://stub@sentry.io/1",
      SENTRY_CRON_MONITOR_SLUG_INGEST_15MIN: "env-wins",
      SERVICE_NAME: "auto-loses",
    } as Record<string, unknown>);

    expect(withMonitor).toHaveBeenCalledWith("env-wins", expect.any(Function), undefined);
  });

  it("falls back to auto-derived ${SERVICE_NAME}:${handlerName} (default 'scheduled') when neither set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler);

    await wrapped({
      SENTRY_DSN: "https://stub@sentry.io/1",
      SERVICE_NAME: "fxsa-pages",
    } as Record<string, unknown>);

    expect(withMonitor).toHaveBeenCalledWith("fxsa-pages:scheduled", expect.any(Function), undefined);
  });
});

describe("withCronMonitor — monitorConfig forwarding (D12 / ADR-0029)", () => {
  it("passes monitorConfig as 3rd arg to withMonitor when schedule + maxRuntimeSeconds set", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, {
      monitorSlug: "x",
      schedule: { type: "crontab", value: "*/15 * * * *" },
      maxRuntimeSeconds: 240,
    });

    await wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" });

    expect(withMonitor).toHaveBeenCalledWith(
      "x",
      expect.any(Function),
      { schedule: { type: "crontab", value: "*/15 * * * *" }, maxRuntime: 240 },
    );
  });

  it("passes undefined as 3rd arg when neither schedule nor maxRuntimeSeconds configured", async () => {
    const handler = vi.fn(async () => {});
    const wrapped = withCronMonitor(handler, { monitorSlug: "x" });
    await wrapped({ SENTRY_DSN: "https://stub@sentry.io/1" });
    expect(withMonitor).toHaveBeenCalledWith("x", expect.any(Function), undefined);
  });
});

// ─── Phase 25 D-16 — type-level firewall (Pitfall 4 / ADR-0032) ─────────────
// D-03 firewall only — D-05 is NOT applied to cf-pages (codex H-3: signature is
// `<R>(handler: () => Promise<R>, ...): (env: Record<string, unknown>) => Promise<R>`;
// `<R>` is return type, not env type). No CallbotEnv strict-Env test here.

describe("CronMonitorSchedule — D-16 type-level firewall (Pitfall 4)", () => {
  it("crontab variant accepts { type: 'crontab', value: string } (regression)", () => {
    const schedule: CronMonitorSchedule = { type: "crontab", value: "*/15 * * * *" };
    expect(schedule.type).toBe("crontab");
  });

  it("interval variant requires value: number + unit (D-03 / ADR-0032)", () => {
    type IntervalVariant = Extract<CronMonitorSchedule, { type: "interval" }>;
    expectTypeOf<IntervalVariant>().toHaveProperty("value").toBeNumber();
    expectTypeOf<IntervalVariant>().toHaveProperty("unit").toEqualTypeOf<
      "minute" | "hour" | "day" | "week" | "month" | "year"
    >();
  });

  it("interval variant REJECTS value: string at typecheck time (D-03 firewall)", () => {
    // @ts-expect-error — interval requires value: number, not string. If this
    // line ever stops erroring, D-03 has regressed (CronMonitorSchedule reverted
    // to the broken interface shape).
    const bad: CronMonitorSchedule = { type: "interval", value: "5", unit: "minute" };
    void bad;
  });

  it("is structurally assignable to SentryMonitorConfig['schedule'] (Pitfall 4 pin)", () => {
    // Explicit firewall against the harness's skipLibCheck blind spot.
    // Uses @sentry/core MonitorConfig (where the type lives).
    const ourCrontab: CronMonitorSchedule = { type: "crontab", value: "*/15 * * * *" };
    const ourInterval: CronMonitorSchedule = { type: "interval", value: 5, unit: "minute" };
    const _checkCrontab: SentryMonitorConfig["schedule"] = ourCrontab;
    const _checkInterval: SentryMonitorConfig["schedule"] = ourInterval;
    void _checkCrontab;
    void _checkInterval;
  });
});
