/**
 * healthz-snippet.test.ts — healthz handler contract suite (ts-cloudflare-pages).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests the COPY-ONLY healthz template's contract per phase-22 CONTEXT.md
 * and PLAN.md REVISIONS R06 + R07:
 *
 *   D9  — healthz NOT wrapped by withObservability (no span overhead on the
 *         health endpoint).
 *   R06 — fail-closed on zero probes configured.
 *   R07 — top-of-file multi-line WARNING block on every snippet.
 *
 * Pages uses Functions-style export — `onRequest` is a PagesFunction, not a
 * bare handler. The test invokes it the same way the runtime does: passing
 * an `EventContext`-shaped object with `request` and `env`.
 *
 * Pages bindings used as adaptation targets:
 *   - OBSERVABILITY_KV  — KV namespace; probe = `get("healthz-probe")`
 *   - DB                — D1 database; probe = `prepare("SELECT 1").first()`
 */

import { describe, it, expect, vi } from "vitest";
import { onRequest } from "./healthz-snippet";

/** Minimal stand-in for Pages' EventContext — only request + env are read. */
function makeCtx(env: Record<string, unknown>): {
  request: Request;
  env: Record<string, unknown>;
} {
  return { request: new Request("https://stub/healthz"), env };
}

describe("onRequest (healthz) — fail-closed default (R06)", () => {
  it("returns 503 status:degraded with reason when no probes configured", async () => {
    // deno-lint-ignore no-explicit-any
    const res = await (onRequest as any)(makeCtx({}));
    expect(res.status).toBe(503);
    expect(res.headers.get("content-type")).toMatch(/application\/json/);
    const body = await res.json();
    expect(body).toEqual({
      status: "degraded",
      reason: "no probes configured — adapt healthz-snippet.ts to your dependencies",
      checks: {},
    });
  });
});

describe("onRequest (healthz) — all probes pass", () => {
  it("returns 200 status:ok when KV probe succeeds", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockResolvedValue(null) },
    };
    // deno-lint-ignore no-explicit-any
    const res = await (onRequest as any)(makeCtx(env));
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({ status: "ok", checks: { kv: true } });
  });

  it("returns 200 status:ok when both KV and D1 probes pass", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockResolvedValue(null) },
      DB: {
        prepare: vi.fn().mockReturnValue({
          first: vi.fn().mockResolvedValue({ "1": 1 }),
        }),
      },
    };
    // deno-lint-ignore no-explicit-any
    const res = await (onRequest as any)(makeCtx(env));
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toEqual({ status: "ok", checks: { kv: true, db: true } });
    // Sanity-check the canonical D1 probe shape: SELECT 1.
    expect(env.DB.prepare).toHaveBeenCalledWith("SELECT 1");
  });
});

describe("onRequest (healthz) — any probe failure → degraded", () => {
  it("returns 503 status:degraded with breakdown when D1 throws", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockResolvedValue(null) },
      DB: {
        prepare: vi.fn().mockReturnValue({
          first: vi.fn().mockRejectedValue(new Error("d1 down")),
        }),
      },
    };
    // deno-lint-ignore no-explicit-any
    const res = await (onRequest as any)(makeCtx(env));
    expect(res.status).toBe(503);
    const body = await res.json();
    expect(body).toEqual({ status: "degraded", checks: { kv: true, db: false } });
  });

  it("treats KV throw as a failed probe", async () => {
    const env = {
      OBSERVABILITY_KV: { get: vi.fn().mockRejectedValue(new Error("kv down")) },
    };
    // deno-lint-ignore no-explicit-any
    const res = await (onRequest as any)(makeCtx(env));
    expect(res.status).toBe(503);
    const body = await res.json();
    expect(body).toEqual({ status: "degraded", checks: { kv: false } });
  });

  it("treats prepare-throw (synchronous D1 failure) as a failed probe", async () => {
    const env = {
      DB: {
        prepare: vi.fn(() => {
          throw new Error("prepare exploded");
        }),
      },
    };
    // deno-lint-ignore no-explicit-any
    const res = await (onRequest as any)(makeCtx(env));
    expect(res.status).toBe(503);
    const body = await res.json();
    expect(body).toEqual({ status: "degraded", checks: { db: false } });
  });
});
