/**
 * Observability wrapper — AgenticApps spec §10 v0.2.1 (browser/React)
 *
 * Service:     {{SERVICE_NAME}}
 * Destination: {{DESTINATION}}
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong below the "Project-specific extensions" section.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)     non-blocking emission of a structured event
 *  - captureError(err, env) record an error with envelope context
 *  - startSpan(name, attrs) open a span representing a unit of work
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 *
 * BROWSER NOTES (differences from server-side wrappers):
 *
 * - No AsyncLocalStorage: trace context is held in module-level state
 *   with a push/pop stack discipline. Concurrent async operations may
 *   interleave and read from the wrong span — for strict correlation,
 *   pass the span explicitly to nested calls.
 * - Init is called once at React-root mount time, not per-request.
 * - Outbound fetch is monkey-patched globally at init so every fetch
 *   call propagates the active traceparent without app-code changes.
 * - The DSN is exposed to client code by design — Sentry browser DSNs
 *   are public keys.
 */

import { buildRegistry, resolveConfig, type Registry } from "./destinations/registry";
import { SENTRY_RESERVED_ATTRS } from "./destinations/sentry";

// Re-export the React error boundary so consumers can import both `init`
// and `ObservabilityErrorBoundary` from this module (per INIT.md Phase 5
// detail line 632-634 and the canonical post-init shape at INIT.md
// line 605-619). The boundary itself is implemented in ./ErrorBoundary.tsx.
export { ObservabilityErrorBoundary } from "./ErrorBoundary";

// ─── Types ─────────────────────────────────────────────────────────────────

export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";

export interface Envelope {
  event: string;
  severity?: Severity;
  attrs?: Record<string, unknown>;
}

export interface Span {
  setAttribute(key: string, value: unknown): void;
  setStatus(status: SpanStatus): void;
  end(opts?: { status?: SpanStatus }): void;
  readonly traceId: string;
  readonly spanId: string;
}

export interface TraceContext {
  traceId: string;       // 32 hex chars (W3C trace-id)
  spanId: string;        // 16 hex chars (W3C span-id of current span)
  parentSpanId?: string; // 16 hex chars (W3C parent-id)
  flags: number;         // W3C trace flags byte
}

interface InternalSpanContext extends TraceContext {
  startedAt: number;
  name: string;
  attributes: Record<string, unknown>;
  status: SpanStatus | "unset";
}

// ─── Static config (parameterized at generation time) ─────────────────────

const SERVICE_DEFAULT = "{{SERVICE_NAME}}";
const DEBUG_SAMPLE_RATE = {{DEBUG_SAMPLE_RATE}};
const TRACE_SAMPLE_RATE = {{TRACE_SAMPLE_RATE}};

const REDACTED_KEYS: ReadonlyArray<string> = [
  {{REDACTED_KEYS}}
];

// ─── Module state ─────────────────────────────────────────────────────────

// Browser is single-threaded but async-interleaved. We use a stack so
// nested startSpan calls produce parent-child relationships, but readers
// (logEvent, captureError, the fetch interceptor) only ever read the
// top of the stack. This is approximate under concurrent Promise chains.
const spanStack: InternalSpanContext[] = [];

let initialized = false;
let serviceName: string = SERVICE_DEFAULT;
let deployEnv: string = "dev";
let originalFetch: typeof fetch | null = null;

/** @internal — test-only seam. Never set in production code. */
let _testEnv: InitEnv | null = null;

// Role-based destination registry, built once in `init`. logEvent dispatches
// to the LOGS adapter; captureError to the ERRORS adapter. Null until init
// runs. All SDK-specific behaviour (Sentry init/capture/breadcrumb, Axiom
// proxy POST) now lives behind the adapters; this wrapper owns the console
// mirror + sampling + dispatch.
let registry: Registry | null = null;

// ─── Initialization ───────────────────────────────────────────────────────

/**
 * The configuration source the destination adapters read. The wrapper
 * assembles it from `import.meta.env` (VITE_-prefixed vars only). CRITICAL:
 * the Axiom browser adapter reads ONLY `AXIOM_PROXY_URL` (from
 * `VITE_AXIOM_PROXY_URL`) — NEVER an ingest token. SENTRY_DSN is a public
 * browser key by design.
 */
export interface InitEnv {
  SENTRY_DSN?: string;
  DEPLOY_ENV?: string;
  SERVICE_NAME?: string;
  AXIOM_PROXY_URL?: string;
  OBS_DESTINATIONS?: string;
  [key: string]: unknown;
}

export interface InitOptions {
  /**
   * Initial trace context to bind. If omitted, a fresh root context is
   * generated lazily on the first emission. Provide explicitly when the
   * SPA loads with a known trace ID (e.g. from a server-rendered cookie).
   */
  initialContext?: TraceContext;
}

/**
 * Reset module state and inject a test environment override. Call this
 * BEFORE `init()` in each test case so the next `init()` rebuilds the
 * registry with the injected env instead of reading `import.meta.env`.
 *
 * @internal — test-only export. Never call from production code.
 */
export function _resetForTest(env?: InitEnv): void {
  _testEnv = env ?? null;
  initialized = false;
  registry = null;
  // #49 gap 5: a partial reset leaks state across test suites. Clear the span
  // stack, reset service identity to its documented defaults, and un-instrument
  // window.fetch so the next init() re-patches a clean global (init only patches
  // when originalFetch === null).
  spanStack.length = 0;
  serviceName = SERVICE_DEFAULT;
  deployEnv = "dev";
  if (originalFetch !== null && typeof window !== "undefined") {
    window.fetch = originalFetch;
  }
  originalFetch = null;
}

/** Assemble an InitEnv from import.meta.env (VITE_-prefixed vars only). */
function envFromImportMeta(): InitEnv {
  const env = (import.meta as ImportMeta & { env: Record<string, string> }).env ?? {};
  return {
    SENTRY_DSN: env.{{ENV_VAR_DSN}},
    DEPLOY_ENV: env.{{ENV_VAR_ENV}},
    SERVICE_NAME: env.{{ENV_VAR_SERVICE}},
    // Browser HARD RULE: only a same-origin PROXY url, never an ingest token.
    AXIOM_PROXY_URL: env.VITE_AXIOM_PROXY_URL,
    OBS_DESTINATIONS: env.VITE_OBS_DESTINATIONS,
  };
}

/**
 * Initialize the wrapper. Called once at React-root mount time, BEFORE
 * `createRoot(...).render(...)`. Idempotent.
 *
 * Reads from import.meta.env (Vite). Vite exposes only VITE_-prefixed
 * vars to client code at build time. Builds the role-based destination
 * registry: the Sentry adapter calls `Sentry.init` when VITE_SENTRY_DSN is
 * present; the Axiom adapter posts to VITE_AXIOM_PROXY_URL (no token). There
 * is no Cloudflare `ctx` in the browser. resolveConfig is fail-closed.
 */
export function init(opts: InitOptions = {}): void {
  if (initialized) return;

  const env = _testEnv ?? envFromImportMeta();
  serviceName = env.SERVICE_NAME ?? SERVICE_DEFAULT;
  deployEnv = env.DEPLOY_ENV ?? "dev";

  registry = buildRegistry(resolveConfig(env), env);

  // Monkey-patch global fetch so all outbound requests carry traceparent.
  // Keep the ORIGINAL reference (not a bound copy) so _resetForTest can restore
  // window.fetch to exactly what it was; the interceptor receives a window-bound
  // copy as its base so the call site keeps the correct `this`.
  if (typeof window !== "undefined" && originalFetch === null) {
    originalFetch = window.fetch;
    window.fetch = instrumentedFetch(originalFetch.bind(window));
  }

  if (opts.initialContext) {
    spanStack.push({
      ...opts.initialContext,
      startedAt: Date.now(),
      name: "root",
      attributes: {},
      status: "unset",
    });
  }

  initialized = true;
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

const TRACEPARENT_RE = /^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/i;

function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Parse an inbound traceparent header. Useful when bootstrapping the SPA
 * with a server-supplied trace ID (e.g. from a meta tag set during SSR).
 */
export function parseTraceparent(header: string | null | undefined): TraceContext | null {
  if (!header) return null;
  const m = TRACEPARENT_RE.exec(header.trim());
  if (!m) return null;
  const version = m[1].toLowerCase();
  const traceId = m[2].toLowerCase();
  const parentId = m[3].toLowerCase();
  // #49 gap 4: the regex gates shape; these gate W3C semantics — reject the
  // reserved "ff" version and the all-zero trace-id / parent-id that downstream
  // collectors (Sentry/Tempo/Honeycomb) discard or mis-attribute. Higher
  // versions (01–fe) stay forward-compatible: parse the known v0 fields rather
  // than drop the inbound trace.
  if (version === "ff") return null;
  if (/^0+$/.test(traceId) || /^0+$/.test(parentId)) return null;
  return {
    traceId,
    spanId: randHex(8),
    parentSpanId: parentId,
    flags: parseInt(m[4], 16),
  };
}

/** Generate a fresh root TraceContext. */
export function newRootContext(): TraceContext {
  return {
    traceId: randHex(16),
    spanId: randHex(8),
    flags: 1,
  };
}

/** Format a TraceContext for outbound traceparent header. */
export function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string {
  return `00-${c.traceId}-${c.spanId}-${c.flags.toString(16).padStart(2, "0")}`;
}

// ─── Active context ───────────────────────────────────────────────────────

/** Read the active TraceContext, or null if no span is active. */
export function getActiveContext(): TraceContext | null {
  const top = spanStack[spanStack.length - 1];
  return top ? { traceId: top.traceId, spanId: top.spanId, parentSpanId: top.parentSpanId, flags: top.flags } : null;
}

// ─── startSpan ────────────────────────────────────────────────────────────

/**
 * Open a span representing a unit of work. The returned Span MUST be
 * .end()-ed; ending pops the span from the stack and emits a span event.
 *
 * Use cases:
 * - Wrap a user action (click handler, form submit) at its top level.
 * - Wrap a route change in a router's beforeEach hook.
 * - Wrap an async operation (data fetch, mutation) for explicit timing.
 *
 * Note: nested startSpan creates a parent-child relationship via the
 * stack. Concurrent async operations may interleave on the stack — this
 * is a known limitation of module-level state (see file header). For
 * strict correlation, prefer one root span per user interaction and pass
 * trace IDs explicitly to deeply-nested async work.
 */
export function startSpan(name: string, attributes: Record<string, unknown> = {}): Span {
  const parent = spanStack[spanStack.length - 1];
  const ctx: InternalSpanContext = parent
    ? {
        traceId: parent.traceId,
        spanId: randHex(8),
        parentSpanId: parent.spanId,
        flags: parent.flags,
        startedAt: Date.now(),
        name,
        attributes: {},
        status: "unset",
      }
    : { ...newRootContext(), startedAt: Date.now(), name, attributes: {}, status: "unset" };

  for (const [k, v] of Object.entries(attributes)) ctx.attributes[k] = redactValue(k, v);

  spanStack.push(ctx);

  let ended = false;
  const span: Span = {
    setAttribute(key, value) {
      ctx.attributes[key] = redactValue(key, value);
    },
    setStatus(s) {
      ctx.status = s;
    },
    end(opts) {
      if (ended) return;
      ended = true;
      if (opts?.status) ctx.status = opts.status;
      const finalStatus: SpanStatus = ctx.status === "unset" ? "ok" : ctx.status;
      // Pop this specific span from the stack (not blindly the top — defensive
      // against out-of-order ends).
      const idx = spanStack.indexOf(ctx);
      if (idx !== -1) spanStack.splice(idx, 1);
      const enriched = emit(
        {
          event: name,
          severity: finalStatus === "error" ? "error" : "info",
          attrs: { ...ctx.attributes, duration_ms: Date.now() - ctx.startedAt, span_status: finalStatus },
        },
        ctx,
      );
      // Spans stay Sentry-native: a span-end breadcrumb on the ERRORS
      // destination, NEVER routed to the Axiom logs sink. No-op when errors is
      // unconfigured / non-Sentry.
      if (enriched) registry?.forRole("errors")?.emit(enriched);
    },
    get traceId() { return ctx.traceId; },
    get spanId() { return ctx.spanId; },
  };
  return span;
}

// ─── logEvent ─────────────────────────────────────────────────────────────

export function logEvent(envelope: Envelope): void {
  const enriched = emit(envelope, spanStack[spanStack.length - 1] ?? null);
  if (!enriched) return;
  // Dispatch to the LOGS destination (Axiom same-origin proxy POST). No-op when
  // logs is "none" or no VITE_AXIOM_PROXY_URL is set (browser HARD RULE: no
  // token, so without a proxy the Axiom adapter is unconfigured → console-only).
  registry?.forRole("logs")?.emit(enriched);
  // Breadcrumb on the ERRORS destination (Sentry) so the next captureException
  // carries this context. No-op when errors is unconfigured / non-Sentry.
  registry?.forRole("errors")?.emit(enriched);
}

// ─── captureError ─────────────────────────────────────────────────────────

export function captureError(err: unknown, envelope: Envelope): void {
  const top = spanStack[spanStack.length - 1];
  if (top) top.status = "error";

  // #49 gap 2: captureError must be visible regardless of caller severity.
  // Coerce to "error" (preserving an explicit "fatal") so emit's sample-rate
  // gate can never silently drop the exception.
  const severity: Severity = envelope.severity === "fatal" ? "fatal" : "error";
  const enriched = emit({ ...envelope, severity }, top ?? null);

  // Dispatch to the ERRORS destination (Sentry scoped captureException). No-op
  // when errors is unconfigured. By the fail-closed registry contract this can
  // NEVER reach the logs-only Axiom adapter (its captureException is a no-op
  // anyway). The enriched envelope carries service/env/trace under reserved
  // attrs so the adapter can rebuild Sentry scope tags.
  if (enriched) registry?.forRole("errors")?.captureException(err, enriched);
}

// ─── Outbound fetch interceptor ──────────────────────────────────────────

/**
 * Wrap a fetch implementation so all outbound requests carry the
 * active `traceparent`. Applied automatically to `window.fetch` at
 * `init()` time. Exported for advanced use (e.g. wrapping a custom
 * fetch in a non-DOM worker).
 */
export function instrumentedFetch(base: typeof fetch): typeof fetch {
  return ((input, init) => {
    const ctx = getActiveContext();
    if (!ctx) return base(input, init);

    const headers = new Headers(init?.headers ?? (input instanceof Request ? input.headers : undefined));
    headers.set("traceparent", formatTraceparent(ctx));

    if (input instanceof Request) {
      return base(new Request(input, { ...init, headers }));
    }
    return base(input, { ...init, headers });
  }) as typeof fetch;
}

// ─── Internal: emit ───────────────────────────────────────────────────────
//
// Owns the console mirror + sampling, and builds the enriched+redacted
// envelope handed to destination adapters. Returns null when the event was
// sampled out (so callers skip dispatch). All SDK-specific egress (Sentry
// breadcrumb/capture, Axiom proxy POST) lives in the adapters.

function emit(envelope: Envelope, ctx: TraceContext | null): Envelope | null {
  const severity: Severity = envelope.severity ?? "info";

  if (severity === "debug" && Math.random() > DEBUG_SAMPLE_RATE) return null;

  const traceId = ctx?.traceId ?? randHex(16);
  const spanId = ctx?.spanId ?? randHex(8);
  const redactedAttrs = redactObject(envelope.attrs ?? {});

  const event = {
    trace_id: traceId,
    span_id: spanId,
    service: serviceName,
    env: deployEnv,
    event: envelope.event,
    severity,
    attrs: redactedAttrs,
    ts: Date.now(),
  };

  // Console mirror — useful in dev tools and for E2E test logs.
  const line = JSON.stringify(event);
  if (severity === "error" || severity === "fatal") console.error(line);
  else if (severity === "warn") console.warn(line);
  else console.log(line);

  // Enriched envelope for adapter dispatch: redacted user attrs plus reserved
  // correlation keys (service/env/trace) the Sentry adapter reads for scope
  // tags. The reserved keys also give Axiom log/trace correlation for free.
  return {
    event: envelope.event,
    severity,
    attrs: {
      ...redactedAttrs,
      [SENTRY_RESERVED_ATTRS.service]: serviceName,
      [SENTRY_RESERVED_ATTRS.env]: deployEnv,
      [SENTRY_RESERVED_ATTRS.traceId]: traceId,
      [SENTRY_RESERVED_ATTRS.spanId]: spanId,
    },
  };
}

// ─── Redaction ────────────────────────────────────────────────────────────

function redactValue(key: string, value: unknown, seen: WeakSet<object> = new WeakSet()): unknown {
  const k = key.toLowerCase();
  if (REDACTED_KEYS.some((r) => k.includes(r))) return "[redacted]";
  return redactDeep(value, seen);
}

// #49 gap 1: recurse into plain objects and arrays so secrets nested below the
// top level (attrs.request.headers.secret, arrays of objects) are scrubbed too.
// null and non-plain objects (Date, class instances) pass through unchanged; new
// containers are constructed, so the caller's input is never mutated. `seen` is
// an ancestor stack (add before recursing, delete after) so a true cycle
// short-circuits to "[circular]" instead of overflowing the stack, while shared
// (DAG) references are still fully redacted.
function redactDeep(value: unknown, seen: WeakSet<object>): unknown {
  if (value === null || typeof value !== "object") return value;
  if (seen.has(value)) return "[circular]";
  seen.add(value);
  try {
    if (Array.isArray(value)) return value.map((v) => redactDeep(v, seen));
    if (isPlainObject(value)) return redactObject(value, seen);
    return value;
  } finally {
    seen.delete(value);
  }
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
  const proto = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function redactObject(obj: Record<string, unknown>, seen: WeakSet<object> = new WeakSet()): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = redactValue(k, v, seen);
  return out;
}

// ─── Utility: instrument a callback as a span ─────────────────────────────

/**
 * Convenience: run `fn` inside a span. Automatically ends the span when
 * `fn` returns (sync or async) and sets status=error if `fn` throws.
 *
 * Useful for click handlers and async user actions:
 *
 *   const onSubmit = () => withSpan("ui.signup.submit", {role: "debtor"}, async () => {
 *     await api.signup(...)
 *     navigate("/dashboard")
 *   })
 */
export function withSpan<T>(
  name: string,
  attrs: Record<string, unknown>,
  fn: () => T | Promise<T>,
): Promise<T> {
  const span = startSpan(name, attrs);
  return Promise.resolve()
    .then(fn)
    .then((result) => {
      span.end();
      return result;
    })
    .catch((err) => {
      captureError(err, { event: name, severity: "error", attrs });
      span.end({ status: "error" });
      throw err;
    });
}

// ─── Project-specific extensions ──────────────────────────────────────────
// Add project-specific helpers below this line. The generator never edits
// below this comment when re-running init.
