/**
 * Contract roundtrip test for the observability wrapper (browser/React).
 *
 * Generated by the add-observability skill; lives in the project after
 * scaffold so future regenerations can detect breakage.
 *
 * Tests verify the spec §10 contract WITHOUT requiring Sentry init —
 * the wrapper must work standalone (console-only) when VITE_SENTRY_DSN
 * is unset.
 *
 * Test runner: vitest. Tests run in vitest's default jsdom or happy-dom
 * environment; window.fetch is monkey-patched at init.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  parseTraceparent,
  newRootContext,
  formatTraceparent,
  startSpan,
  logEvent,
  captureError,
  getActiveContext,
  withSpan,
  instrumentedFetch,
} from "./index";

// ─── §10.3 traceparent roundtrip ────────────────────────────────────────────

describe("§10.3 traceparent", () => {
  it("roundtrips: format → parse → identical trace_id and parent_id", () => {
    const root = newRootContext();
    const header = formatTraceparent(root);
    const parsed = parseTraceparent(header);
    expect(parsed).not.toBeNull();
    expect(parsed!.traceId).toBe(root.traceId);
    expect(parsed!.parentSpanId).toBe(root.spanId);
  });

  it("rejects malformed inputs", () => {
    for (const header of [
      "",
      "not-a-traceparent",
      "00-tooshort-tooshort-01",
      "00-XYZ-not-hex-01",
    ]) {
      expect(parseTraceparent(header), `expected reject for ${header}`).toBeNull();
    }
  });

  it("accepts the canonical W3C example", () => {
    const header = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";
    const tc = parseTraceparent(header);
    expect(tc).not.toBeNull();
    expect(tc!.traceId).toBe("4bf92f3577b34da6a3ce929d0e0e4736");
    expect(tc!.parentSpanId).toBe("00f067aa0ba902b7");
    expect(tc!.spanId).toHaveLength(16);
  });
});

// ─── §10.5 fail-safe ────────────────────────────────────────────────────────

describe("§10.5 fail-safe", () => {
  it("logEvent does not throw without init", () => {
    expect(() => logEvent({ event: "test", severity: "info" })).not.toThrow();
  });

  it("captureError does not throw with a real Error", () => {
    expect(() =>
      captureError(new Error("boom"), { event: "test", severity: "error" }),
    ).not.toThrow();
  });

  it("captureError does not throw with a non-Error value", () => {
    expect(() => captureError("string error", { event: "test" })).not.toThrow();
    expect(() => captureError({ weird: "object" }, { event: "test" })).not.toThrow();
    expect(() => captureError(undefined, { event: "test" })).not.toThrow();
  });
});

// ─── §10.1 span lifecycle ───────────────────────────────────────────────────

describe("§10.1 startSpan", () => {
  it("returns a span with traceId and spanId", () => {
    const span = startSpan("test", { k: "v" });
    expect(span.traceId).toMatch(/^[0-9a-f]{32}$/);
    expect(span.spanId).toMatch(/^[0-9a-f]{16}$/);
    span.end();
  });

  it("end() is idempotent", () => {
    const span = startSpan("test");
    span.end();
    expect(() => span.end()).not.toThrow();
  });

  it("nested spans share trace_id, differ in span_id, parent links", () => {
    const outer = startSpan("outer");
    const inner = startSpan("inner");
    expect(inner.traceId).toBe(outer.traceId);
    expect(inner.spanId).not.toBe(outer.spanId);
    inner.end();
    outer.end();
  });

  it("setStatus + end emits without throwing", () => {
    const span = startSpan("test");
    span.setStatus("error");
    expect(() => span.end()).not.toThrow();
  });

  it("setAttribute redacts known keys", () => {
    const span = startSpan("test");
    expect(() => span.setAttribute("password", "leaked")).not.toThrow();
    span.end();
  });
});

// ─── §10.3 active context (stack) ──────────────────────────────────────────

describe("§10.3 active context (browser stack model)", () => {
  it("getActiveContext returns null with no active span", () => {
    expect(getActiveContext()).toBeNull();
  });

  it("getActiveContext returns the currently-active span", () => {
    const span = startSpan("test");
    const active = getActiveContext();
    expect(active).not.toBeNull();
    expect(active!.traceId).toBe(span.traceId);
    expect(active!.spanId).toBe(span.spanId);
    span.end();
    expect(getActiveContext()).toBeNull();
  });

  it("nested spans expose the innermost as active", () => {
    const outer = startSpan("outer");
    const inner = startSpan("inner");
    expect(getActiveContext()!.spanId).toBe(inner.spanId);
    inner.end();
    expect(getActiveContext()!.spanId).toBe(outer.spanId);
    outer.end();
  });

  it("out-of-order ends pop the correct span", () => {
    const a = startSpan("a");
    const b = startSpan("b");
    const c = startSpan("c");
    // End b before c — defensive splice should still leave c active.
    b.end();
    expect(getActiveContext()!.spanId).toBe(c.spanId);
    c.end();
    a.end();
  });
});

// ─── §10.3 outbound fetch interceptor ───────────────────────────────────────

describe("§10.3 instrumentedFetch", () => {
  it("propagates traceparent when an active span exists", async () => {
    const captured: { url: string; headers: Headers }[] = [];
    const fakeFetch = vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
      const headers = new Headers(init?.headers);
      captured.push({ url, headers });
      return new Response("ok", { status: 200 });
    });
    const wrapped = instrumentedFetch(fakeFetch as typeof fetch);
    const span = startSpan("test");
    await wrapped("https://example.com/api");
    span.end();
    expect(captured).toHaveLength(1);
    const tp = captured[0].headers.get("traceparent");
    expect(tp).not.toBeNull();
    expect(tp).toMatch(/^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$/);
  });

  it("does not add traceparent when no span is active", async () => {
    let capturedInit: RequestInit | undefined;
    const fakeFetch = vi.fn(async (_input: RequestInfo | URL, init?: RequestInit) => {
      capturedInit = init;
      return new Response("ok", { status: 200 });
    });
    const wrapped = instrumentedFetch(fakeFetch as typeof fetch);
    await wrapped("https://example.com/api");
    const headers = new Headers(capturedInit?.headers);
    expect(headers.get("traceparent")).toBeNull();
  });
});

// ─── §10.1 withSpan helper ─────────────────────────────────────────────────

describe("§10.1 withSpan", () => {
  it("ends the span on success and returns the value", async () => {
    const result = await withSpan("test", { k: "v" }, async () => 42);
    expect(result).toBe(42);
    expect(getActiveContext()).toBeNull(); // span was popped
  });

  it("ends the span on error and re-throws", async () => {
    const err = new Error("boom");
    await expect(withSpan("test", {}, async () => { throw err; })).rejects.toBe(err);
    expect(getActiveContext()).toBeNull(); // span was popped despite error
  });

  it("works with sync callbacks", async () => {
    const result = await withSpan("test", {}, () => "sync");
    expect(result).toBe("sync");
  });
});

// ─── §10.5 console mirror smoke test ────────────────────────────────────────

describe("§10.5 stdout mirror", () => {
  it("error severity writes to console.error", () => {
    const spy = vi.spyOn(console, "error").mockImplementation(() => {});
    logEvent({ event: "test_error", severity: "error" });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });

  it("info severity writes to console.log", () => {
    const spy = vi.spyOn(console, "log").mockImplementation(() => {});
    logEvent({ event: "test_info", severity: "info" });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });
});
