/**
 * Observability wrapper — AgenticApps spec §10 v0.2.1 (browser/React)
 *
 * Service:     {{SERVICE_NAME}}
 * Destination: {{DESTINATION}}
 *
 * Generated by `add-observability` skill. Edits to this file should be
 * mirrored into the skill template if they're general; project-specific
 * tweaks belong below the "Project-specific extensions" section.
 *
 * CONTRACT (per spec §10):
 *
 *  - logEvent(envelope)     non-blocking emission of a structured event
 *  - captureError(err, env) record an error with envelope context
 *  - startSpan(name, attrs) open a span representing a unit of work
 *
 * Application code MUST NOT import @sentry/* directly. Use the three
 * exports above. See policy.md for redaction and sampling rules.
 *
 * BROWSER NOTES (differences from server-side wrappers):
 *
 * - No AsyncLocalStorage: trace context is held in module-level state
 *   with a push/pop stack discipline. Concurrent async operations may
 *   interleave and read from the wrong span — for strict correlation,
 *   pass the span explicitly to nested calls.
 * - Init is called once at React-root mount time, not per-request.
 * - Outbound fetch is monkey-patched globally at init so every fetch
 *   call propagates the active traceparent without app-code changes.
 * - The DSN is exposed to client code by design — Sentry browser DSNs
 *   are public keys.
 */

import * as Sentry from "@sentry/react";

// Re-export the React error boundary so consumers can import both `init`
// and `ObservabilityErrorBoundary` from this module (per INIT.md Phase 5
// detail line 632-634 and the canonical post-init shape at INIT.md
// line 605-619). The boundary itself is implemented in ./ErrorBoundary.tsx.
export { ObservabilityErrorBoundary } from "./ErrorBoundary";

// ─── Types ─────────────────────────────────────────────────────────────────

export type Severity = "debug" | "info" | "warn" | "error" | "fatal";
export type SpanStatus = "ok" | "error";

export interface Envelope {
  event: string;
  severity?: Severity;
  attrs?: Record<string, unknown>;
}

export interface Span {
  setAttribute(key: string, value: unknown): void;
  setStatus(status: SpanStatus): void;
  end(opts?: { status?: SpanStatus }): void;
  readonly traceId: string;
  readonly spanId: string;
}

export interface TraceContext {
  traceId: string;       // 32 hex chars (W3C trace-id)
  spanId: string;        // 16 hex chars (W3C span-id of current span)
  parentSpanId?: string; // 16 hex chars (W3C parent-id)
  flags: number;         // W3C trace flags byte
}

interface InternalSpanContext extends TraceContext {
  startedAt: number;
  name: string;
  attributes: Record<string, unknown>;
  status: SpanStatus | "unset";
}

// ─── Static config (parameterized at generation time) ─────────────────────

const SERVICE_DEFAULT = "{{SERVICE_NAME}}";
const DEBUG_SAMPLE_RATE = {{DEBUG_SAMPLE_RATE}};
const TRACE_SAMPLE_RATE = {{TRACE_SAMPLE_RATE}};

const REDACTED_KEYS: ReadonlyArray<string> = [
  {{REDACTED_KEYS}}
];

// ─── Module state ─────────────────────────────────────────────────────────

// Browser is single-threaded but async-interleaved. We use a stack so
// nested startSpan calls produce parent-child relationships, but readers
// (logEvent, captureError, the fetch interceptor) only ever read the
// top of the stack. This is approximate under concurrent Promise chains.
const spanStack: InternalSpanContext[] = [];

let initialized = false;
let serviceName: string = SERVICE_DEFAULT;
let deployEnv: string = "dev";
let originalFetch: typeof fetch | null = null;

// ─── Initialization ───────────────────────────────────────────────────────

export interface InitOptions {
  /**
   * Initial trace context to bind. If omitted, a fresh root context is
   * generated lazily on the first emission. Provide explicitly when the
   * SPA loads with a known trace ID (e.g. from a server-rendered cookie).
   */
  initialContext?: TraceContext;
}

/**
 * Initialize the wrapper. Called once at React-root mount time, BEFORE
 * `createRoot(...).render(...)`. Idempotent.
 *
 * Reads from import.meta.env (Vite). Vite exposes only VITE_-prefixed
 * vars to client code at build time.
 */
export function init(opts: InitOptions = {}): void {
  if (initialized) return;

  const env = (import.meta as ImportMeta & { env: Record<string, string> }).env;
  serviceName = env.{{ENV_VAR_SERVICE}} ?? SERVICE_DEFAULT;
  deployEnv = env.{{ENV_VAR_ENV}} ?? "dev";
  const dsn = env.{{ENV_VAR_DSN}};

  if (dsn) {
    Sentry.init({
      dsn,
      environment: deployEnv,
      release: serviceName,
      tracesSampleRate: TRACE_SAMPLE_RATE,
      sendDefaultPii: false,
      // BrowserTracing integration is included by @sentry/react default.
      // If you want to opt out, override `integrations: []` here.
    });
  }

  // Monkey-patch global fetch so all outbound requests carry traceparent.
  if (typeof window !== "undefined" && originalFetch === null) {
    originalFetch = window.fetch.bind(window);
    window.fetch = instrumentedFetch(originalFetch);
  }

  if (opts.initialContext) {
    spanStack.push({
      ...opts.initialContext,
      startedAt: Date.now(),
      name: "root",
      attributes: {},
      status: "unset",
    });
  }

  initialized = true;
}

// ─── traceparent helpers (W3C Trace Context Level 1) ──────────────────────

const TRACEPARENT_RE = /^([0-9a-f]{2})-([0-9a-f]{32})-([0-9a-f]{16})-([0-9a-f]{2})$/i;

function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Parse an inbound traceparent header. Useful when bootstrapping the SPA
 * with a server-supplied trace ID (e.g. from a meta tag set during SSR).
 */
export function parseTraceparent(header: string | null | undefined): TraceContext | null {
  if (!header) return null;
  const m = TRACEPARENT_RE.exec(header.trim());
  if (!m) return null;
  return {
    traceId: m[2].toLowerCase(),
    spanId: randHex(8),
    parentSpanId: m[3].toLowerCase(),
    flags: parseInt(m[4], 16),
  };
}

/** Generate a fresh root TraceContext. */
export function newRootContext(): TraceContext {
  return {
    traceId: randHex(16),
    spanId: randHex(8),
    flags: 1,
  };
}

/** Format a TraceContext for outbound traceparent header. */
export function formatTraceparent(c: Pick<TraceContext, "traceId" | "spanId" | "flags">): string {
  return `00-${c.traceId}-${c.spanId}-${c.flags.toString(16).padStart(2, "0")}`;
}

// ─── Active context ───────────────────────────────────────────────────────

/** Read the active TraceContext, or null if no span is active. */
export function getActiveContext(): TraceContext | null {
  const top = spanStack[spanStack.length - 1];
  return top ? { traceId: top.traceId, spanId: top.spanId, parentSpanId: top.parentSpanId, flags: top.flags } : null;
}

// ─── startSpan ────────────────────────────────────────────────────────────

/**
 * Open a span representing a unit of work. The returned Span MUST be
 * .end()-ed; ending pops the span from the stack and emits a span event.
 *
 * Use cases:
 * - Wrap a user action (click handler, form submit) at its top level.
 * - Wrap a route change in a router's beforeEach hook.
 * - Wrap an async operation (data fetch, mutation) for explicit timing.
 *
 * Note: nested startSpan creates a parent-child relationship via the
 * stack. Concurrent async operations may interleave on the stack — this
 * is a known limitation of module-level state (see file header). For
 * strict correlation, prefer one root span per user interaction and pass
 * trace IDs explicitly to deeply-nested async work.
 */
export function startSpan(name: string, attributes: Record<string, unknown> = {}): Span {
  const parent = spanStack[spanStack.length - 1];
  const ctx: InternalSpanContext = parent
    ? {
        traceId: parent.traceId,
        spanId: randHex(8),
        parentSpanId: parent.spanId,
        flags: parent.flags,
        startedAt: Date.now(),
        name,
        attributes: {},
        status: "unset",
      }
    : { ...newRootContext(), startedAt: Date.now(), name, attributes: {}, status: "unset" };

  for (const [k, v] of Object.entries(attributes)) ctx.attributes[k] = redactValue(k, v);

  spanStack.push(ctx);

  let ended = false;
  const span: Span = {
    setAttribute(key, value) {
      ctx.attributes[key] = redactValue(key, value);
    },
    setStatus(s) {
      ctx.status = s;
    },
    end(opts) {
      if (ended) return;
      ended = true;
      if (opts?.status) ctx.status = opts.status;
      const finalStatus: SpanStatus = ctx.status === "unset" ? "ok" : ctx.status;
      // Pop this specific span from the stack (not blindly the top — defensive
      // against out-of-order ends).
      const idx = spanStack.indexOf(ctx);
      if (idx !== -1) spanStack.splice(idx, 1);
      emit(
        {
          event: name,
          severity: finalStatus === "error" ? "error" : "info",
          attrs: { ...ctx.attributes, duration_ms: Date.now() - ctx.startedAt, span_status: finalStatus },
        },
        ctx,
      );
    },
    get traceId() { return ctx.traceId; },
    get spanId() { return ctx.spanId; },
  };
  return span;
}

// ─── logEvent ─────────────────────────────────────────────────────────────

export function logEvent(envelope: Envelope): void {
  emit(envelope, spanStack[spanStack.length - 1] ?? null);
}

// ─── captureError ─────────────────────────────────────────────────────────

export function captureError(err: unknown, envelope: Envelope): void {
  const top = spanStack[spanStack.length - 1];
  if (top) top.status = "error";

  if (initialized && err instanceof Error) {
    safeFireAndForget(() => {
      Sentry.withScope((scope) => {
        scope.setTag("event", envelope.event);
        scope.setTag("service", serviceName);
        scope.setTag("env", deployEnv);
        if (top) {
          scope.setTag("trace_id", top.traceId);
          scope.setTag("span_id", top.spanId);
        }
        if (envelope.attrs) {
          scope.setContext("attrs", redactObject(envelope.attrs));
        }
        Sentry.captureException(err);
      });
    });
  }

  emit({ ...envelope, severity: envelope.severity ?? "error" }, top ?? null);
}

// ─── Outbound fetch interceptor ──────────────────────────────────────────

/**
 * Wrap a fetch implementation so all outbound requests carry the
 * active `traceparent`. Applied automatically to `window.fetch` at
 * `init()` time. Exported for advanced use (e.g. wrapping a custom
 * fetch in a non-DOM worker).
 */
export function instrumentedFetch(base: typeof fetch): typeof fetch {
  return ((input, init) => {
    const ctx = getActiveContext();
    if (!ctx) return base(input, init);

    const headers = new Headers(init?.headers ?? (input instanceof Request ? input.headers : undefined));
    headers.set("traceparent", formatTraceparent(ctx));

    if (input instanceof Request) {
      return base(new Request(input, { ...init, headers }));
    }
    return base(input, { ...init, headers });
  }) as typeof fetch;
}

// ─── Internal: emit ───────────────────────────────────────────────────────

function emit(envelope: Envelope, ctx: TraceContext | null): void {
  const severity: Severity = envelope.severity ?? "info";

  if (severity === "debug" && Math.random() > DEBUG_SAMPLE_RATE) return;

  const event = {
    trace_id: ctx?.traceId ?? randHex(16),
    span_id: ctx?.spanId ?? randHex(8),
    service: serviceName,
    env: deployEnv,
    event: envelope.event,
    severity,
    attrs: redactObject(envelope.attrs ?? {}),
    ts: Date.now(),
  };

  // Console mirror — useful in dev tools and for E2E test logs.
  const line = JSON.stringify(event);
  if (severity === "error" || severity === "fatal") console.error(line);
  else if (severity === "warn") console.warn(line);
  else console.log(line);

  if (initialized && severity !== "debug") {
    safeFireAndForget(() => {
      Sentry.addBreadcrumb({
        category: event.event,
        level: sentryLevel(severity),
        data: event.attrs as { [k: string]: unknown },
      });
    });
  }
}

function sentryLevel(s: Severity): Sentry.SeverityLevel {
  return s === "warn" ? "warning" : (s as Sentry.SeverityLevel);
}

function safeFireAndForget(fn: () => void): void {
  try {
    Promise.resolve().then(fn).catch(() => {
      /* observability MUST NOT throw */
    });
  } catch {
    /* swallow */
  }
}

// ─── Redaction ────────────────────────────────────────────────────────────

function redactValue(key: string, value: unknown): unknown {
  const k = key.toLowerCase();
  if (REDACTED_KEYS.some((r) => k.includes(r))) return "[redacted]";
  return value;
}

function redactObject(obj: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) out[k] = redactValue(k, v);
  return out;
}

// ─── Utility: instrument a callback as a span ─────────────────────────────

/**
 * Convenience: run `fn` inside a span. Automatically ends the span when
 * `fn` returns (sync or async) and sets status=error if `fn` throws.
 *
 * Useful for click handlers and async user actions:
 *
 *   const onSubmit = () => withSpan("ui.signup.submit", {role: "debtor"}, async () => {
 *     await api.signup(...)
 *     navigate("/dashboard")
 *   })
 */
export function withSpan<T>(
  name: string,
  attrs: Record<string, unknown>,
  fn: () => T | Promise<T>,
): Promise<T> {
  const span = startSpan(name, attrs);
  return Promise.resolve()
    .then(fn)
    .then((result) => {
      span.end();
      return result;
    })
    .catch((err) => {
      captureError(err, { event: name, severity: "error", attrs });
      span.end({ status: "error" });
      throw err;
    });
}

// ─── Project-specific extensions ──────────────────────────────────────────
// Add project-specific helpers below this line. The generator never edits
// below this comment when re-running init.
